# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `actionmailer` gem.
# Please instead update this file by running `bin/tapioca gem actionmailer`.


# source://actionmailer//lib/action_mailer/gem_version.rb#3
module ActionMailer
  extend ::ActiveSupport::Autoload

  class << self
    # source://actionmailer//lib/action_mailer/message_delivery.rb#9
    def deliver_all_later(*deliveries, **options); end

    # source://actionmailer//lib/action_mailer/message_delivery.rb#17
    def deliver_all_later!(*deliveries, **options); end

    # source://actionmailer//lib/action_mailer/deprecator.rb#4
    def deprecator; end

    # source://actionmailer//lib/action_mailer.rb#61
    def eager_load!; end

    # source://actionmailer//lib/action_mailer/gem_version.rb#5
    def gem_version; end

    # source://actionmailer//lib/action_mailer/version.rb#8
    def version; end

    private

    # source://actionmailer//lib/action_mailer/message_delivery.rb#22
    def _deliver_all_later(delivery_method, *deliveries, **options); end
  end
end

# source://actionmailer//lib/action_mailer/base.rb#477
class ActionMailer::Base < ::AbstractController::Base
  include ::ActionMailer::Callbacks
  include ::ActiveSupport::Callbacks
  include ::ActionMailer::DeliveryMethods
  include ::ActionMailer::QueuedDelivery
  include ::ActiveSupport::Rescuable
  include ::ActionMailer::Rescuable
  include ::ActionMailer::Parameterized
  include ::ActionMailer::Previews
  include ::ActionMailer::FormBuilder
  include ::ActionView::ViewPaths
  include ::AbstractController::Rendering
  include ::AbstractController::Logger
  include ::ActiveSupport::Benchmarkable
  include ::AbstractController::Helpers
  include ::AbstractController::Translation
  include ::AbstractController::AssetPaths
  include ::AbstractController::Callbacks
  include ::AbstractController::Caching::Fragments
  include ::AbstractController::Caching::ConfigMethods
  include ::AbstractController::Caching
  include ::ActionView::Rendering
  include ::ActionView::Layouts
  extend ::ActionMailer::Callbacks::ClassMethods
  extend ::ActiveSupport::Callbacks::ClassMethods
  extend ::ActionMailer::DeliveryMethods::ClassMethods
  extend ::ActiveSupport::Rescuable::ClassMethods
  extend ::ActionMailer::Rescuable::ClassMethods
  extend ::ActionMailer::Parameterized::ClassMethods
  extend ::ActionMailer::Previews::ClassMethods
  extend ::ActionMailer::FormBuilder::ClassMethods
  extend ::ActionView::ViewPaths::ClassMethods
  extend ::AbstractController::Helpers::Resolution
  extend ::AbstractController::Helpers::ClassMethods
  extend ::AbstractController::Callbacks::ClassMethods
  extend ::AbstractController::Caching::Fragments::ClassMethods
  extend ::AbstractController::Caching::ClassMethods
  extend ::AbstractController::Caching::ConfigMethods
  extend ::ActionView::Rendering::ClassMethods
  extend ::ActionView::Layouts::ClassMethods

  # source://actionmailer//lib/action_mailer/base.rb#639
  def initialize; end

  # source://actionmailer//lib/action_mailer/base.rb#478
  def __callbacks; end

  # source://actionmailer//lib/action_mailer/base.rb#478
  def _deliver_callbacks; end

  # source://actionmailer//lib/action_mailer/base.rb#491
  def _helper_methods; end

  # source://actionmailer//lib/action_mailer/base.rb#491
  def _helper_methods=(_arg0); end

  # source://actionmailer//lib/action_mailer/base.rb#491
  def _helper_methods?; end

  # source://actionmailer//lib/action_mailer/base.rb#497
  def _layout_conditions; end

  # source://actionmailer//lib/action_mailer/base.rb#497
  def _layout_conditions?; end

  # source://actionmailer//lib/action_mailer/base.rb#494
  def _process_action_callbacks; end

  # source://actionmailer//lib/action_mailer/base.rb#478
  def _run_deliver_callbacks; end

  # source://actionmailer//lib/action_mailer/base.rb#478
  def _run_deliver_callbacks!(&block); end

  # source://actionmailer//lib/action_mailer/base.rb#494
  def _run_process_action_callbacks(&block); end

  # source://actionmailer//lib/action_mailer/base.rb#494
  def _run_process_action_callbacks!(&block); end

  # source://actionmailer//lib/action_mailer/base.rb#495
  def _view_cache_dependencies; end

  # source://actionmailer//lib/action_mailer/base.rb#495
  def _view_cache_dependencies=(_arg0); end

  # source://actionmailer//lib/action_mailer/base.rb#495
  def _view_cache_dependencies?; end

  # source://actionmailer//lib/action_mailer/base.rb#493
  def asset_host(*_arg0, **_arg1, &_arg2); end

  # source://actionmailer//lib/action_mailer/base.rb#493
  def asset_host=(arg); end

  # source://actionmailer//lib/action_mailer/base.rb#493
  def assets_dir(*_arg0, **_arg1, &_arg2); end

  # source://actionmailer//lib/action_mailer/base.rb#493
  def assets_dir=(arg); end

  # source://actionmailer//lib/action_mailer/base.rb#756
  def attachments; end

  # source://actionmailer//lib/action_mailer/base.rb#493
  def default_asset_host_protocol(*_arg0, **_arg1, &_arg2); end

  # source://actionmailer//lib/action_mailer/base.rb#493
  def default_asset_host_protocol=(arg); end

  # source://actionmailer//lib/action_mailer/base.rb#503
  def default_params; end

  # source://actionmailer//lib/action_mailer/base.rb#503
  def default_params=(_arg0); end

  # source://actionmailer//lib/action_mailer/base.rb#503
  def default_params?; end

  # source://actionmailer//lib/action_mailer/base.rb#495
  def default_static_extension(*_arg0, **_arg1, &_arg2); end

  # source://actionmailer//lib/action_mailer/base.rb#495
  def default_static_extension=(arg); end

  # source://actionmailer//lib/action_mailer/base.rb#480
  def deliver_later_queue_name; end

  # source://actionmailer//lib/action_mailer/base.rb#480
  def deliver_later_queue_name=(_arg0); end

  # source://actionmailer//lib/action_mailer/base.rb#480
  def deliver_later_queue_name?; end

  # source://actionmailer//lib/action_mailer/base.rb#480
  def delivery_job; end

  # source://actionmailer//lib/action_mailer/base.rb#480
  def delivery_job=(_arg0); end

  # source://actionmailer//lib/action_mailer/base.rb#480
  def delivery_job?; end

  # source://actionmailer//lib/action_mailer/base.rb#479
  def delivery_method; end

  # source://actionmailer//lib/action_mailer/base.rb#479
  def delivery_method=(_arg0); end

  # source://actionmailer//lib/action_mailer/base.rb#479
  def delivery_method?; end

  # source://actionmailer//lib/action_mailer/base.rb#479
  def delivery_methods; end

  # source://actionmailer//lib/action_mailer/base.rb#479
  def delivery_methods=(_arg0); end

  # source://actionmailer//lib/action_mailer/base.rb#479
  def delivery_methods?; end

  # source://actionmailer//lib/action_mailer/base.rb#680
  def email_address_with_name(address, name); end

  # source://actionmailer//lib/action_mailer/base.rb#495
  def enable_fragment_cache_logging(*_arg0, **_arg1, &_arg2); end

  # source://actionmailer//lib/action_mailer/base.rb#495
  def enable_fragment_cache_logging=(arg); end

  # source://actionmailer//lib/action_mailer/base.rb#479
  def file_settings; end

  # source://actionmailer//lib/action_mailer/base.rb#479
  def file_settings=(_arg0); end

  # source://actionmailer//lib/action_mailer/base.rb#479
  def file_settings?; end

  # source://actionmailer//lib/action_mailer/base.rb#495
  def fragment_cache_keys; end

  # source://actionmailer//lib/action_mailer/base.rb#495
  def fragment_cache_keys=(_arg0); end

  # source://actionmailer//lib/action_mailer/base.rb#495
  def fragment_cache_keys?; end

  # source://actionmailer//lib/action_mailer/base.rb#718
  def headers(args = T.unsafe(nil)); end

  # source://actionmailer//lib/action_mailer/base.rb#493
  def javascripts_dir(*_arg0, **_arg1, &_arg2); end

  # source://actionmailer//lib/action_mailer/base.rb#493
  def javascripts_dir=(arg); end

  # source://actionmailer//lib/action_mailer/base.rb#490
  def logger(*_arg0, **_arg1, &_arg2); end

  # source://actionmailer//lib/action_mailer/base.rb#490
  def logger=(arg); end

  # source://actionmailer//lib/action_mailer/base.rb#865
  def mail(headers = T.unsafe(nil), &block); end

  # source://actionmailer//lib/action_mailer/base.rb#673
  def mailer_name; end

  # source://actionmailer//lib/action_mailer/base.rb#637
  def message; end

  # source://actionmailer//lib/action_mailer/base.rb#637
  def message=(_arg0); end

  # source://actionmailer//lib/action_mailer/base.rb#482
  def params; end

  # source://actionmailer//lib/action_mailer/base.rb#482
  def params=(_arg0); end

  # source://actionmailer//lib/action_mailer/base.rb#495
  def perform_caching(*_arg0, **_arg1, &_arg2); end

  # source://actionmailer//lib/action_mailer/base.rb#495
  def perform_caching=(arg); end

  # source://actionmailer//lib/action_mailer/base.rb#479
  def perform_deliveries; end

  # source://actionmailer//lib/action_mailer/base.rb#479
  def perform_deliveries=(val); end

  # source://actionmailer//lib/action_mailer/base.rb#483
  def preview_interceptors; end

  # source://actionmailer//lib/action_mailer/base.rb#483
  def preview_paths; end

  # source://actionmailer//lib/action_mailer/base.rb#645
  def process(method_name, *args, **_arg2); end

  # source://actionmailer//lib/action_mailer/base.rb#479
  def raise_delivery_errors; end

  # source://actionmailer//lib/action_mailer/base.rb#479
  def raise_delivery_errors=(val); end

  # source://actionmailer//lib/action_mailer/base.rb#494
  def raise_on_missing_callback_actions; end

  # source://actionmailer//lib/action_mailer/base.rb#494
  def raise_on_missing_callback_actions=(val); end

  # source://actionmailer//lib/action_mailer/base.rb#493
  def relative_url_root(*_arg0, **_arg1, &_arg2); end

  # source://actionmailer//lib/action_mailer/base.rb#493
  def relative_url_root=(arg); end

  # source://actionmailer//lib/action_mailer/base.rb#481
  def rescue_handlers; end

  # source://actionmailer//lib/action_mailer/base.rb#481
  def rescue_handlers=(_arg0); end

  # source://actionmailer//lib/action_mailer/base.rb#481
  def rescue_handlers?; end

  # source://actionmailer//lib/action_mailer/base.rb#479
  def sendmail_settings; end

  # source://actionmailer//lib/action_mailer/base.rb#479
  def sendmail_settings=(_arg0); end

  # source://actionmailer//lib/action_mailer/base.rb#479
  def sendmail_settings?; end

  # source://actionmailer//lib/action_mailer/base.rb#483
  def show_previews; end

  # source://actionmailer//lib/action_mailer/base.rb#479
  def smtp_settings; end

  # source://actionmailer//lib/action_mailer/base.rb#479
  def smtp_settings=(_arg0); end

  # source://actionmailer//lib/action_mailer/base.rb#479
  def smtp_settings?; end

  # source://actionmailer//lib/action_mailer/base.rb#493
  def stylesheets_dir(*_arg0, **_arg1, &_arg2); end

  # source://actionmailer//lib/action_mailer/base.rb#493
  def stylesheets_dir=(arg); end

  # source://actionmailer//lib/action_mailer/base.rb#479
  def test_settings; end

  # source://actionmailer//lib/action_mailer/base.rb#479
  def test_settings=(_arg0); end

  # source://actionmailer//lib/action_mailer/base.rb#479
  def test_settings?; end

  private

  # source://actionmailer//lib/action_mailer/base.rb#497
  def _layout(lookup_context, formats, keys); end

  # source://actionmailer//lib/action_mailer/base.rb#1066
  def _protected_ivars; end

  # source://actionmailer//lib/action_mailer/base.rb#942
  def apply_defaults(headers); end

  # source://actionmailer//lib/action_mailer/base.rb#962
  def assign_headers_to_message(message, headers); end

  # source://actionmailer//lib/action_mailer/base.rb#968
  def collect_responses(headers, &block); end

  # source://actionmailer//lib/action_mailer/base.rb#978
  def collect_responses_from_block(headers); end

  # source://actionmailer//lib/action_mailer/base.rb#992
  def collect_responses_from_templates(headers); end

  # source://actionmailer//lib/action_mailer/base.rb#985
  def collect_responses_from_text(headers); end

  # source://actionmailer//lib/action_mailer/base.rb#952
  def compute_default(value); end

  # source://actionmailer//lib/action_mailer/base.rb#1035
  def create_parts_from_responses(m, responses); end

  # source://actionmailer//lib/action_mailer/base.rb#932
  def default_i18n_subject(interpolations = T.unsafe(nil)); end

  # source://actionmailer//lib/action_mailer/base.rb#1005
  def each_template(paths, name, &block); end

  # source://actionmailer//lib/action_mailer/base.rb#1048
  def insert_part(container, response, charset); end

  # source://actionmailer//lib/action_mailer/base.rb#1062
  def instrument_name; end

  # source://actionmailer//lib/action_mailer/base.rb#1055
  def instrument_payload(key); end

  # source://actionmailer//lib/action_mailer/base.rb#910
  def set_content_type(m, user_content_type, class_default); end

  # source://actionmailer//lib/action_mailer/base.rb#1014
  def wrap_inline_attachments(message); end

  class << self
    # source://actionmailer//lib/action_mailer/base.rb#478
    def __callbacks; end

    # source://actionmailer//lib/action_mailer/base.rb#478
    def __callbacks=(value); end

    # source://actionmailer//lib/action_mailer/base.rb#484
    def _default_form_builder; end

    # source://actionmailer//lib/action_mailer/base.rb#484
    def _default_form_builder=(value); end

    # source://actionmailer//lib/action_mailer/base.rb#484
    def _default_form_builder?; end

    # source://actionmailer//lib/action_mailer/base.rb#478
    def _deliver_callbacks; end

    # source://actionmailer//lib/action_mailer/base.rb#478
    def _deliver_callbacks=(value); end

    # source://actionmailer//lib/action_mailer/base.rb#491
    def _helper_methods; end

    # source://actionmailer//lib/action_mailer/base.rb#491
    def _helper_methods=(value); end

    # source://actionmailer//lib/action_mailer/base.rb#491
    def _helper_methods?; end

    # source://actionmailer//lib/action_mailer/base.rb#491
    def _helpers; end

    # source://actionmailer//lib/action_mailer/base.rb#497
    def _layout; end

    # source://actionmailer//lib/action_mailer/base.rb#497
    def _layout=(value); end

    # source://actionmailer//lib/action_mailer/base.rb#497
    def _layout?; end

    # source://actionmailer//lib/action_mailer/base.rb#497
    def _layout_conditions; end

    # source://actionmailer//lib/action_mailer/base.rb#497
    def _layout_conditions=(value); end

    # source://actionmailer//lib/action_mailer/base.rb#497
    def _layout_conditions?; end

    # source://actionmailer//lib/action_mailer/base.rb#494
    def _process_action_callbacks; end

    # source://actionmailer//lib/action_mailer/base.rb#494
    def _process_action_callbacks=(value); end

    # source://actionmailer//lib/action_mailer/base.rb#495
    def _view_cache_dependencies; end

    # source://actionmailer//lib/action_mailer/base.rb#495
    def _view_cache_dependencies=(value); end

    # source://actionmailer//lib/action_mailer/base.rb#495
    def _view_cache_dependencies?; end

    # source://actionmailer//lib/action_mailer/base.rb#493
    def asset_host(*_arg0, **_arg1, &_arg2); end

    # source://actionmailer//lib/action_mailer/base.rb#493
    def asset_host=(arg); end

    # source://actionmailer//lib/action_mailer/base.rb#493
    def assets_dir(*_arg0, **_arg1, &_arg2); end

    # source://actionmailer//lib/action_mailer/base.rb#493
    def assets_dir=(arg); end

    # source://actionmailer//lib/action_mailer/base.rb#576
    def controller_path; end

    # source://actionmailer//lib/action_mailer/base.rb#581
    def default(value = T.unsafe(nil)); end

    # source://actionmailer//lib/action_mailer/base.rb#493
    def default_asset_host_protocol(*_arg0, **_arg1, &_arg2); end

    # source://actionmailer//lib/action_mailer/base.rb#493
    def default_asset_host_protocol=(arg); end

    # source://actionmailer//lib/action_mailer/base.rb#585
    def default_options=(value = T.unsafe(nil)); end

    # source://actionmailer//lib/action_mailer/base.rb#503
    def default_params; end

    # source://actionmailer//lib/action_mailer/base.rb#503
    def default_params=(value); end

    # source://actionmailer//lib/action_mailer/base.rb#503
    def default_params?; end

    # source://actionmailer//lib/action_mailer/base.rb#495
    def default_static_extension(*_arg0, **_arg1, &_arg2); end

    # source://actionmailer//lib/action_mailer/base.rb#495
    def default_static_extension=(arg); end

    # source://actionmailer//lib/action_mailer/base.rb#480
    def deliver_later_queue_name; end

    # source://actionmailer//lib/action_mailer/base.rb#480
    def deliver_later_queue_name=(value); end

    # source://actionmailer//lib/action_mailer/base.rb#480
    def deliver_later_queue_name?; end

    # source://actionmailer//lib/action_mailer/base.rb#593
    def deliver_mail(mail); end

    # source://actionmailer//lib/action_mailer/base.rb#480
    def delivery_job; end

    # source://actionmailer//lib/action_mailer/base.rb#480
    def delivery_job=(value); end

    # source://actionmailer//lib/action_mailer/base.rb#480
    def delivery_job?; end

    # source://actionmailer//lib/action_mailer/base.rb#479
    def delivery_method; end

    # source://actionmailer//lib/action_mailer/base.rb#479
    def delivery_method=(value); end

    # source://actionmailer//lib/action_mailer/base.rb#479
    def delivery_method?; end

    # source://actionmailer//lib/action_mailer/base.rb#479
    def delivery_methods; end

    # source://actionmailer//lib/action_mailer/base.rb#479
    def delivery_methods=(value); end

    # source://actionmailer//lib/action_mailer/base.rb#479
    def delivery_methods?; end

    # source://actionmailer//lib/action_mailer/base.rb#603
    def email_address_with_name(address, name); end

    # source://actionmailer//lib/action_mailer/base.rb#495
    def enable_fragment_cache_logging(*_arg0, **_arg1, &_arg2); end

    # source://actionmailer//lib/action_mailer/base.rb#495
    def enable_fragment_cache_logging=(arg); end

    # source://actionmailer//lib/action_mailer/base.rb#479
    def file_settings; end

    # source://actionmailer//lib/action_mailer/base.rb#479
    def file_settings=(value); end

    # source://actionmailer//lib/action_mailer/base.rb#479
    def file_settings?; end

    # source://actionmailer//lib/action_mailer/base.rb#495
    def fragment_cache_keys; end

    # source://actionmailer//lib/action_mailer/base.rb#495
    def fragment_cache_keys=(value); end

    # source://actionmailer//lib/action_mailer/base.rb#495
    def fragment_cache_keys?; end

    # source://actionmailer//lib/action_mailer/base.rb#493
    def javascripts_dir(*_arg0, **_arg1, &_arg2); end

    # source://actionmailer//lib/action_mailer/base.rb#493
    def javascripts_dir=(arg); end

    # source://actionmailer//lib/action_mailer/base.rb#490
    def logger(*_arg0, **_arg1, &_arg2); end

    # source://actionmailer//lib/action_mailer/base.rb#490
    def logger=(arg); end

    # source://actionmailer//lib/action_mailer/base.rb#571
    def mailer_name; end

    # source://actionmailer//lib/action_mailer/base.rb#575
    def mailer_name=(_arg0); end

    # source://actionmailer//lib/action_mailer/base.rb#495
    def perform_caching(*_arg0, **_arg1, &_arg2); end

    # source://actionmailer//lib/action_mailer/base.rb#495
    def perform_caching=(arg); end

    # source://actionmailer//lib/action_mailer/base.rb#479
    def perform_deliveries; end

    # source://actionmailer//lib/action_mailer/base.rb#479
    def perform_deliveries=(val); end

    # source://actionmailer//lib/action_mailer/base.rb#483
    def preview_interceptors; end

    # source://actionmailer//lib/action_mailer/base.rb#483
    def preview_interceptors=(val); end

    # source://actionmailer//lib/action_mailer/base.rb#483
    def preview_paths; end

    # source://actionmailer//lib/action_mailer/base.rb#483
    def preview_paths=(val); end

    # source://actionmailer//lib/action_mailer/base.rb#479
    def raise_delivery_errors; end

    # source://actionmailer//lib/action_mailer/base.rb#479
    def raise_delivery_errors=(val); end

    # source://actionmailer//lib/action_mailer/base.rb#494
    def raise_on_missing_callback_actions; end

    # source://actionmailer//lib/action_mailer/base.rb#494
    def raise_on_missing_callback_actions=(val); end

    # source://actionmailer//lib/action_mailer/base.rb#548
    def register_interceptor(interceptor); end

    # source://actionmailer//lib/action_mailer/base.rb#522
    def register_interceptors(*interceptors); end

    # source://actionmailer//lib/action_mailer/base.rb#534
    def register_observer(observer); end

    # source://actionmailer//lib/action_mailer/base.rb#512
    def register_observers(*observers); end

    # source://actionmailer//lib/action_mailer/base.rb#493
    def relative_url_root(*_arg0, **_arg1, &_arg2); end

    # source://actionmailer//lib/action_mailer/base.rb#493
    def relative_url_root=(arg); end

    # source://actionmailer//lib/action_mailer/base.rb#481
    def rescue_handlers; end

    # source://actionmailer//lib/action_mailer/base.rb#481
    def rescue_handlers=(value); end

    # source://actionmailer//lib/action_mailer/base.rb#481
    def rescue_handlers?; end

    # source://actionmailer//lib/action_mailer/base.rb#479
    def sendmail_settings; end

    # source://actionmailer//lib/action_mailer/base.rb#479
    def sendmail_settings=(value); end

    # source://actionmailer//lib/action_mailer/base.rb#479
    def sendmail_settings?; end

    # source://actionmailer//lib/action_mailer/base.rb#483
    def show_previews; end

    # source://actionmailer//lib/action_mailer/base.rb#483
    def show_previews=(val); end

    # source://actionmailer//lib/action_mailer/base.rb#479
    def smtp_settings; end

    # source://actionmailer//lib/action_mailer/base.rb#479
    def smtp_settings=(value); end

    # source://actionmailer//lib/action_mailer/base.rb#479
    def smtp_settings?; end

    # source://actionmailer//lib/action_mailer/base.rb#493
    def stylesheets_dir(*_arg0, **_arg1, &_arg2); end

    # source://actionmailer//lib/action_mailer/base.rb#493
    def stylesheets_dir=(arg); end

    # source://actionmailer//lib/action_mailer/base.rb#938
    def supports_path?; end

    # source://actionmailer//lib/action_mailer/base.rb#479
    def test_settings; end

    # source://actionmailer//lib/action_mailer/base.rb#479
    def test_settings=(value); end

    # source://actionmailer//lib/action_mailer/base.rb#479
    def test_settings?; end

    # source://actionmailer//lib/action_mailer/base.rb#555
    def unregister_interceptor(interceptor); end

    # source://actionmailer//lib/action_mailer/base.rb#527
    def unregister_interceptors(*interceptors); end

    # source://actionmailer//lib/action_mailer/base.rb#541
    def unregister_observer(observer); end

    # source://actionmailer//lib/action_mailer/base.rb#517
    def unregister_observers(*observers); end

    private

    # source://actionmailer//lib/action_mailer/base.rb#478
    def __class_attr___callbacks; end

    # source://actionmailer//lib/action_mailer/base.rb#478
    def __class_attr___callbacks=(new_value); end

    # source://actionmailer//lib/action_mailer/base.rb#484
    def __class_attr__default_form_builder; end

    # source://actionmailer//lib/action_mailer/base.rb#484
    def __class_attr__default_form_builder=(new_value); end

    # source://actionmailer//lib/action_mailer/base.rb#491
    def __class_attr__helper_methods; end

    # source://actionmailer//lib/action_mailer/base.rb#491
    def __class_attr__helper_methods=(new_value); end

    # source://actionmailer//lib/action_mailer/base.rb#497
    def __class_attr__layout; end

    # source://actionmailer//lib/action_mailer/base.rb#497
    def __class_attr__layout=(new_value); end

    # source://actionmailer//lib/action_mailer/base.rb#497
    def __class_attr__layout_conditions; end

    # source://actionmailer//lib/action_mailer/base.rb#497
    def __class_attr__layout_conditions=(new_value); end

    # source://actionmailer//lib/action_mailer/base.rb#495
    def __class_attr__view_cache_dependencies; end

    # source://actionmailer//lib/action_mailer/base.rb#495
    def __class_attr__view_cache_dependencies=(new_value); end

    # source://actionmailer//lib/action_mailer/base.rb#477
    def __class_attr_config; end

    # source://actionmailer//lib/action_mailer/base.rb#477
    def __class_attr_config=(new_value); end

    # source://actionmailer//lib/action_mailer/base.rb#503
    def __class_attr_default_params; end

    # source://actionmailer//lib/action_mailer/base.rb#503
    def __class_attr_default_params=(new_value); end

    # source://actionmailer//lib/action_mailer/base.rb#480
    def __class_attr_deliver_later_queue_name; end

    # source://actionmailer//lib/action_mailer/base.rb#480
    def __class_attr_deliver_later_queue_name=(new_value); end

    # source://actionmailer//lib/action_mailer/base.rb#480
    def __class_attr_delivery_job; end

    # source://actionmailer//lib/action_mailer/base.rb#480
    def __class_attr_delivery_job=(new_value); end

    # source://actionmailer//lib/action_mailer/base.rb#479
    def __class_attr_delivery_method; end

    # source://actionmailer//lib/action_mailer/base.rb#479
    def __class_attr_delivery_method=(new_value); end

    # source://actionmailer//lib/action_mailer/base.rb#479
    def __class_attr_delivery_methods; end

    # source://actionmailer//lib/action_mailer/base.rb#479
    def __class_attr_delivery_methods=(new_value); end

    # source://actionmailer//lib/action_mailer/base.rb#479
    def __class_attr_file_settings; end

    # source://actionmailer//lib/action_mailer/base.rb#479
    def __class_attr_file_settings=(new_value); end

    # source://actionmailer//lib/action_mailer/base.rb#495
    def __class_attr_fragment_cache_keys; end

    # source://actionmailer//lib/action_mailer/base.rb#495
    def __class_attr_fragment_cache_keys=(new_value); end

    # source://actionmailer//lib/action_mailer/base.rb#481
    def __class_attr_rescue_handlers; end

    # source://actionmailer//lib/action_mailer/base.rb#481
    def __class_attr_rescue_handlers=(new_value); end

    # source://actionmailer//lib/action_mailer/base.rb#479
    def __class_attr_sendmail_settings; end

    # source://actionmailer//lib/action_mailer/base.rb#479
    def __class_attr_sendmail_settings=(new_value); end

    # source://actionmailer//lib/action_mailer/base.rb#479
    def __class_attr_smtp_settings; end

    # source://actionmailer//lib/action_mailer/base.rb#479
    def __class_attr_smtp_settings=(new_value); end

    # source://actionmailer//lib/action_mailer/base.rb#479
    def __class_attr_test_settings; end

    # source://actionmailer//lib/action_mailer/base.rb#479
    def __class_attr_test_settings=(new_value); end

    # source://actionmailer//lib/action_mailer/base.rb#624
    def method_missing(method_name, *_arg1, **_arg2, &_arg3); end

    # source://actionmailer//lib/action_mailer/base.rb#559
    def observer_class_for(value); end

    # source://actionmailer//lib/action_mailer/base.rb#632
    def respond_to_missing?(method, include_all = T.unsafe(nil)); end

    # source://actionmailer//lib/action_mailer/base.rb#611
    def set_payload_for_mail(payload, mail); end
  end
end

# source://actionmailer//lib/action_mailer/base.rb#491
module ActionMailer::Base::HelperMethods
  include ::ActionMailer::MailHelper
  include ::ActionText::ContentHelper
  include ::ActionText::TagHelper

  # source://actionmailer//lib/action_mailer/base.rb#495
  def combined_fragment_cache_key(*_arg0, **_arg1, &_arg2); end

  # source://actionmailer//lib/action_mailer/base.rb#495
  def view_cache_dependencies(*_arg0, **_arg1, &_arg2); end
end

# source://actionmailer//lib/action_mailer/base.rb#764
class ActionMailer::Base::LateAttachmentsProxy < ::SimpleDelegator
  # source://actionmailer//lib/action_mailer/base.rb#766
  def []=(_name, _content); end

  # source://actionmailer//lib/action_mailer/base.rb#765
  def inline; end

  private

  # source://actionmailer//lib/action_mailer/base.rb#769
  def _raise_error; end
end

# source://actionmailer//lib/action_mailer/base.rb#659
class ActionMailer::Base::NullMail
  # source://actionmailer//lib/action_mailer/base.rb#660
  def body; end

  # source://actionmailer//lib/action_mailer/base.rb#661
  def header; end

  # source://actionmailer//lib/action_mailer/base.rb#667
  def method_missing(*_arg0, **_arg1, &_arg2); end

  # source://actionmailer//lib/action_mailer/base.rb#663
  def respond_to?(string, include_all = T.unsafe(nil)); end
end

# source://actionmailer//lib/action_mailer/base.rb#499
ActionMailer::Base::PROTECTED_IVARS = T.let(T.unsafe(nil), Array)

# source://actionmailer//lib/action_mailer/callbacks.rb#4
module ActionMailer::Callbacks
  extend ::ActiveSupport::Concern
  include GeneratedInstanceMethods
  include ::ActiveSupport::Callbacks

  mixes_in_class_methods GeneratedClassMethods
  mixes_in_class_methods ::ActionMailer::Callbacks::ClassMethods
  mixes_in_class_methods ::ActiveSupport::Callbacks::ClassMethods
  mixes_in_class_methods ::ActiveSupport::DescendantsTracker

  module GeneratedClassMethods
    def __callbacks; end
    def __callbacks=(value); end
  end

  module GeneratedInstanceMethods
    def __callbacks; end
  end
end

# source://actionmailer//lib/action_mailer/callbacks.rb#14
module ActionMailer::Callbacks::ClassMethods
  # source://actionmailer//lib/action_mailer/callbacks.rb#23
  def after_deliver(*filters, &blk); end

  # source://actionmailer//lib/action_mailer/callbacks.rb#28
  def around_deliver(*filters, &blk); end

  # source://actionmailer//lib/action_mailer/callbacks.rb#17
  def before_deliver(*filters, &blk); end

  # source://actionmailer//lib/action_mailer/callbacks.rb#32
  def internal_methods; end
end

# source://actionmailer//lib/action_mailer/callbacks.rb#7
ActionMailer::Callbacks::DEFAULT_INTERNAL_METHODS = T.let(T.unsafe(nil), Array)

# source://actionmailer//lib/action_mailer/collector.rb#8
class ActionMailer::Collector
  include ::AbstractController::Collector

  # source://actionmailer//lib/action_mailer/collector.rb#12
  def initialize(context, &block); end

  # source://actionmailer//lib/action_mailer/collector.rb#23
  def all(*args, &block); end

  # source://actionmailer//lib/action_mailer/collector.rb#18
  def any(*args, &block); end

  # source://actionmailer//lib/action_mailer/collector.rb#25
  def custom(mime, options = T.unsafe(nil)); end

  # source://actionmailer//lib/action_mailer/collector.rb#10
  def responses; end
end

# source://actionmailer//lib/action_mailer/delivery_methods.rb#10
module ActionMailer::DeliveryMethods
  extend ::ActiveSupport::Concern
  include GeneratedInstanceMethods

  mixes_in_class_methods GeneratedClassMethods
  mixes_in_class_methods ::ActionMailer::DeliveryMethods::ClassMethods

  # source://actionmailer//lib/action_mailer/delivery_methods.rb#79
  def wrap_delivery_behavior!(*args); end

  module GeneratedClassMethods
    def delivery_method; end
    def delivery_method=(value); end
    def delivery_method?; end
    def delivery_methods; end
    def delivery_methods=(value); end
    def delivery_methods?; end
    def file_settings; end
    def file_settings=(value); end
    def file_settings?; end
    def sendmail_settings; end
    def sendmail_settings=(value); end
    def sendmail_settings?; end
    def smtp_settings; end
    def smtp_settings=(value); end
    def smtp_settings?; end
    def test_settings; end
    def test_settings=(value); end
    def test_settings?; end
  end

  module GeneratedInstanceMethods
    def delivery_method; end
    def delivery_method=(value); end
    def delivery_method?; end
    def delivery_methods; end
    def delivery_methods=(value); end
    def delivery_methods?; end
    def file_settings; end
    def file_settings=(value); end
    def file_settings?; end
    def sendmail_settings; end
    def sendmail_settings=(value); end
    def sendmail_settings?; end
    def smtp_settings; end
    def smtp_settings=(value); end
    def smtp_settings?; end
    def test_settings; end
    def test_settings=(value); end
    def test_settings?; end
  end
end

# source://actionmailer//lib/action_mailer/delivery_methods.rb#41
module ActionMailer::DeliveryMethods::ClassMethods
  # source://actionmailer//lib/action_mailer/delivery_methods.rb#51
  def add_delivery_method(symbol, klass, default_options = T.unsafe(nil)); end

  # source://actionmailer//lib/action_mailer/delivery_methods.rb#43
  def deliveries(&_arg0); end

  # source://actionmailer//lib/action_mailer/delivery_methods.rb#43
  def deliveries=(arg); end

  # source://actionmailer//lib/action_mailer/delivery_methods.rb#57
  def wrap_delivery_behavior(mail, method = T.unsafe(nil), options = T.unsafe(nil)); end
end

# source://actionmailer//lib/action_mailer/form_builder.rb#14
module ActionMailer::FormBuilder
  extend ::ActiveSupport::Concern
  include GeneratedInstanceMethods

  mixes_in_class_methods GeneratedClassMethods
  mixes_in_class_methods ::ActionMailer::FormBuilder::ClassMethods

  # source://actionmailer//lib/action_mailer/form_builder.rb#33
  def default_form_builder; end

  module GeneratedClassMethods
    def _default_form_builder; end
    def _default_form_builder=(value); end
    def _default_form_builder?; end
  end

  module GeneratedInstanceMethods; end
end

# source://actionmailer//lib/action_mailer/form_builder.rb#21
module ActionMailer::FormBuilder::ClassMethods
  # source://actionmailer//lib/action_mailer/form_builder.rb#27
  def default_form_builder(builder); end
end

# source://actionmailer//lib/action_mailer/inline_preview_interceptor.rb#17
class ActionMailer::InlinePreviewInterceptor
  include ::Base64

  # source://actionmailer//lib/action_mailer/inline_preview_interceptor.rb#26
  def initialize(message); end

  # source://actionmailer//lib/action_mailer/inline_preview_interceptor.rb#30
  def transform!; end

  private

  # source://actionmailer//lib/action_mailer/inline_preview_interceptor.rb#51
  def data_url(part); end

  # source://actionmailer//lib/action_mailer/inline_preview_interceptor.rb#55
  def find_part(cid); end

  # source://actionmailer//lib/action_mailer/inline_preview_interceptor.rb#47
  def html_part; end

  # source://actionmailer//lib/action_mailer/inline_preview_interceptor.rb#45
  def message; end

  class << self
    # source://actionmailer//lib/action_mailer/inline_preview_interceptor.rb#22
    def previewing_email(message); end
  end
end

# source://actionmailer//lib/action_mailer/inline_preview_interceptor.rb#18
ActionMailer::InlinePreviewInterceptor::PATTERN = T.let(T.unsafe(nil), Regexp)

# source://actionmailer//lib/action_mailer/log_subscriber.rb#7
class ActionMailer::LogSubscriber < ::ActiveSupport::LogSubscriber
  # source://actionmailer//lib/action_mailer/log_subscriber.rb#8
  def deliver(event); end

  # source://actionmailer//lib/action_mailer/log_subscriber.rb#34
  def logger; end

  # source://actionmailer//lib/action_mailer/log_subscriber.rb#24
  def process(event); end

  class << self
    private

    # source://actionmailer//lib/action_mailer/log_subscriber.rb#21
    def __class_attr_log_levels; end

    # source://actionmailer//lib/action_mailer/log_subscriber.rb#21
    def __class_attr_log_levels=(new_value); end
  end
end

# source://actionmailer//lib/action_mailer/mail_delivery_job.rb#13
class ActionMailer::MailDeliveryJob < ::ActiveJob::Base
  # source://actionmailer//lib/action_mailer/mail_delivery_job.rb#21
  def perform(mailer, mail_method, delivery_method, args:, kwargs: T.unsafe(nil), params: T.unsafe(nil)); end

  private

  # source://actionmailer//lib/action_mailer/mail_delivery_job.rb#40
  def handle_exception_with_mailer_class(exception); end

  # source://actionmailer//lib/action_mailer/mail_delivery_job.rb#34
  def mailer_class; end

  class << self
    private

    # source://actionmailer//lib/action_mailer/mail_delivery_job.rb#14
    def __class_attr_queue_name; end

    # source://actionmailer//lib/action_mailer/mail_delivery_job.rb#14
    def __class_attr_queue_name=(new_value); end

    # source://actionmailer//lib/action_mailer/mail_delivery_job.rb#19
    def __class_attr_rescue_handlers; end

    # source://actionmailer//lib/action_mailer/mail_delivery_job.rb#19
    def __class_attr_rescue_handlers=(new_value); end
  end
end

# source://actionmailer//lib/action_mailer/mail_helper.rb#9
module ActionMailer::MailHelper
  # source://actionmailer//lib/action_mailer/mail_helper.rb#53
  def attachments; end

  # source://actionmailer//lib/action_mailer/mail_helper.rb#22
  def block_format(text); end

  # source://actionmailer//lib/action_mailer/mail_helper.rb#65
  def format_paragraph(text, len = T.unsafe(nil), indent = T.unsafe(nil)); end

  # source://actionmailer//lib/action_mailer/mail_helper.rb#43
  def mailer; end

  # source://actionmailer//lib/action_mailer/mail_helper.rb#48
  def message; end
end

# source://actionmailer//lib/action_mailer/message_delivery.rb#51
class ActionMailer::MessageDelivery
  # source://actionmailer//lib/action_mailer/message_delivery.rb#54
  def initialize(mailer_class, action, *args, **_arg3); end

  # source://actionmailer//lib/action_mailer/message_delivery.rb#65
  def __getobj__; end

  # source://actionmailer//lib/action_mailer/message_delivery.rb#70
  def __setobj__(mail_message); end

  # source://actionmailer//lib/action_mailer/message_delivery.rb#52
  def action; end

  # source://actionmailer//lib/action_mailer/message_delivery.rb#52
  def args; end

  # source://actionmailer//lib/action_mailer/message_delivery.rb#136
  def deliver_later(options = T.unsafe(nil)); end

  # source://actionmailer//lib/action_mailer/message_delivery.rb#109
  def deliver_later!(options = T.unsafe(nil)); end

  # source://actionmailer//lib/action_mailer/message_delivery.rb#157
  def deliver_now; end

  # source://actionmailer//lib/action_mailer/message_delivery.rb#145
  def deliver_now!; end

  # source://actionmailer//lib/action_mailer/message_delivery.rb#52
  def mailer_class; end

  # source://actionmailer//lib/action_mailer/message_delivery.rb#75
  def message; end

  # source://actionmailer//lib/action_mailer/message_delivery.rb#52
  def params; end

  # source://actionmailer//lib/action_mailer/message_delivery.rb#80
  def processed?; end

  private

  # source://actionmailer//lib/action_mailer/message_delivery.rb#174
  def enqueue_delivery(delivery_method, options = T.unsafe(nil)); end

  # source://actionmailer//lib/action_mailer/message_delivery.rb#168
  def processed_mailer; end
end

# source://actionmailer//lib/action_mailer/test_case.rb#7
class ActionMailer::NonInferrableMailerError < ::StandardError
  # source://actionmailer//lib/action_mailer/test_case.rb#8
  def initialize(name); end
end

# source://actionmailer//lib/action_mailer/parameterized.rb#89
module ActionMailer::Parameterized
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::ActionMailer::Parameterized::ClassMethods
end

# source://actionmailer//lib/action_mailer/parameterized.rb#100
module ActionMailer::Parameterized::ClassMethods
  # source://actionmailer//lib/action_mailer/parameterized.rb#106
  def with(params); end
end

# source://actionmailer//lib/action_mailer/parameterized.rb#111
class ActionMailer::Parameterized::Mailer
  # source://actionmailer//lib/action_mailer/parameterized.rb#112
  def initialize(mailer, params); end

  private

  # source://actionmailer//lib/action_mailer/parameterized.rb#117
  def method_missing(method_name, *_arg1, **_arg2, &_arg3); end

  # source://actionmailer//lib/action_mailer/parameterized.rb#125
  def respond_to_missing?(method, include_all = T.unsafe(nil)); end
end

# source://actionmailer//lib/action_mailer/parameterized.rb#130
class ActionMailer::Parameterized::MessageDelivery < ::ActionMailer::MessageDelivery
  # source://actionmailer//lib/action_mailer/parameterized.rb#131
  def initialize(mailer_class, action, params, *_arg3, **_arg4, &_arg5); end

  private

  # source://actionmailer//lib/action_mailer/parameterized.rb#144
  def enqueue_delivery(delivery_method, options = T.unsafe(nil)); end

  # source://actionmailer//lib/action_mailer/parameterized.rb#137
  def processed_mailer; end
end

# source://actionmailer//lib/action_mailer/preview.rb#69
class ActionMailer::Preview
  extend ::ActiveSupport::DescendantsTracker

  # source://actionmailer//lib/action_mailer/preview.rb#74
  def initialize(params = T.unsafe(nil)); end

  # source://actionmailer//lib/action_mailer/preview.rb#72
  def params; end

  class << self
    # source://actionmailer//lib/action_mailer/preview.rb#80
    def all; end

    # source://actionmailer//lib/action_mailer/preview.rb#88
    def call(email, params = T.unsafe(nil)); end

    # source://actionmailer//lib/action_mailer/preview.rb#101
    def email_exists?(email); end

    # source://actionmailer//lib/action_mailer/preview.rb#96
    def emails; end

    # source://actionmailer//lib/action_mailer/preview.rb#106
    def exists?(preview); end

    # source://actionmailer//lib/action_mailer/preview.rb#111
    def find(preview); end

    # source://actionmailer//lib/action_mailer/preview.rb#116
    def preview_name; end

    private

    # source://actionmailer//lib/action_mailer/preview.rb#135
    def inform_preview_interceptors(message); end

    # source://actionmailer//lib/action_mailer/preview.rb#121
    def load_previews; end

    # source://actionmailer//lib/action_mailer/preview.rb#127
    def preview_paths; end

    # source://actionmailer//lib/action_mailer/preview.rb#131
    def show_previews; end
  end
end

# source://actionmailer//lib/action_mailer/preview.rb#6
module ActionMailer::Previews
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::ActionMailer::Previews::ClassMethods
end

# source://actionmailer//lib/action_mailer/preview.rb#28
module ActionMailer::Previews::ClassMethods
  # source://actionmailer//lib/action_mailer/preview.rb#42
  def register_preview_interceptor(interceptor); end

  # source://actionmailer//lib/action_mailer/preview.rb#30
  def register_preview_interceptors(*interceptors); end

  # source://actionmailer//lib/action_mailer/preview.rb#53
  def unregister_preview_interceptor(interceptor); end

  # source://actionmailer//lib/action_mailer/preview.rb#35
  def unregister_preview_interceptors(*interceptors); end

  private

  # source://actionmailer//lib/action_mailer/preview.rb#58
  def interceptor_class_for(interceptor); end
end

# source://actionmailer//lib/action_mailer/queued_delivery.rb#4
module ActionMailer::QueuedDelivery
  extend ::ActiveSupport::Concern
  include GeneratedInstanceMethods

  mixes_in_class_methods GeneratedClassMethods

  module GeneratedClassMethods
    def deliver_later_queue_name; end
    def deliver_later_queue_name=(value); end
    def deliver_later_queue_name?; end
    def delivery_job; end
    def delivery_job=(value); end
    def delivery_job?; end
  end

  module GeneratedInstanceMethods
    def deliver_later_queue_name; end
    def deliver_later_queue_name=(value); end
    def deliver_later_queue_name?; end
    def delivery_job; end
    def delivery_job=(value); end
    def delivery_job?; end
  end
end

# source://actionmailer//lib/action_mailer/railtie.rb#9
class ActionMailer::Railtie < ::Rails::Railtie; end

# source://actionmailer//lib/action_mailer/rescuable.rb#10
module ActionMailer::Rescuable
  extend ::ActiveSupport::Concern
  include GeneratedInstanceMethods
  include ::ActiveSupport::Rescuable

  mixes_in_class_methods GeneratedClassMethods
  mixes_in_class_methods ::ActiveSupport::Rescuable::ClassMethods
  mixes_in_class_methods ::ActionMailer::Rescuable::ClassMethods

  # source://actionmailer//lib/action_mailer/rescuable.rb#20
  def handle_exceptions; end

  private

  # source://actionmailer//lib/action_mailer/rescuable.rb#27
  def process(*_arg0, **_arg1, &_arg2); end

  module GeneratedClassMethods
    def rescue_handlers; end
    def rescue_handlers=(value); end
    def rescue_handlers?; end
  end

  module GeneratedInstanceMethods
    def rescue_handlers; end
    def rescue_handlers=(value); end
    def rescue_handlers?; end
  end
end

# source://actionmailer//lib/action_mailer/rescuable.rb#14
module ActionMailer::Rescuable::ClassMethods
  # source://actionmailer//lib/action_mailer/rescuable.rb#15
  def handle_exception(exception); end
end

# source://actionmailer//lib/action_mailer/structured_event_subscriber.rb#7
class ActionMailer::StructuredEventSubscriber < ::ActiveSupport::StructuredEventSubscriber
  # source://actionmailer//lib/action_mailer/structured_event_subscriber.rb#8
  def deliver(event); end

  # source://actionmailer//lib/action_mailer/structured_event_subscriber.rb#27
  def process(event); end
end

# source://actionmailer//lib/action_mailer/test_case.rb#15
class ActionMailer::TestCase < ::ActiveSupport::TestCase
  include ::ActiveSupport::Testing::ConstantLookup
  include ::ActiveJob::TestHelper
  include ::ActionMailer::TestHelper
  include ::Rails::Dom::Testing::Assertions::SelectorAssertions
  include ::Rails::Dom::Testing::Assertions::DomAssertions
  include ::ActionMailer::TestCase::Behavior
  extend ::ActiveSupport::Testing::ConstantLookup::ClassMethods
  extend ::ActionMailer::TestCase::Behavior::ClassMethods

  # source://actionmailer//lib/action_mailer/test_case.rb#41
  def _mailer_class; end

  # source://actionmailer//lib/action_mailer/test_case.rb#41
  def _mailer_class=(_arg0); end

  # source://actionmailer//lib/action_mailer/test_case.rb#41
  def _mailer_class?; end

  # source://actionmailer//lib/action_mailer/test_case.rb#42
  def _run_setup_callbacks(&block); end

  # source://actionmailer//lib/action_mailer/test_case.rb#44
  def _run_teardown_callbacks(&block); end

  class << self
    # source://actionmailer//lib/action_mailer/test_case.rb#41
    def _mailer_class; end

    # source://actionmailer//lib/action_mailer/test_case.rb#41
    def _mailer_class=(value); end

    # source://actionmailer//lib/action_mailer/test_case.rb#41
    def _mailer_class?; end

    private

    # source://actionmailer//lib/action_mailer/test_case.rb#42
    def __class_attr___callbacks; end

    # source://actionmailer//lib/action_mailer/test_case.rb#42
    def __class_attr___callbacks=(new_value); end

    # source://actionmailer//lib/action_mailer/test_case.rb#41
    def __class_attr__mailer_class; end

    # source://actionmailer//lib/action_mailer/test_case.rb#41
    def __class_attr__mailer_class=(new_value); end
  end
end

# source://actionmailer//lib/action_mailer/test_case.rb#32
module ActionMailer::TestCase::Behavior
  include ::ActiveSupport::Testing::Assertions
  include ::ActiveJob::TestHelper
  include ::ActionMailer::TestHelper
  include ::Rails::Dom::Testing::Assertions::SelectorAssertions
  include ::Rails::Dom::Testing::Assertions::DomAssertions
  extend ::ActiveSupport::Concern
  include GeneratedInstanceMethods
  include ::ActiveSupport::Testing::ConstantLookup

  mixes_in_class_methods GeneratedClassMethods
  mixes_in_class_methods ::ActiveSupport::Testing::ConstantLookup::ClassMethods
  mixes_in_class_methods ::ActionMailer::TestCase::Behavior::ClassMethods

  # source://actionmailer//lib/action_mailer/test_case.rb#82
  def read_fixture(action); end

  private

  # source://actionmailer//lib/action_mailer/test_case.rb#115
  def charset; end

  # source://actionmailer//lib/action_mailer/test_case.rb#119
  def encode(subject); end

  # source://actionmailer//lib/action_mailer/test_case.rb#87
  def initialize_test_deliveries; end

  # source://actionmailer//lib/action_mailer/test_case.rb#104
  def restore_delivery_method; end

  # source://actionmailer//lib/action_mailer/test_case.rb#94
  def restore_test_deliveries; end

  # source://actionmailer//lib/action_mailer/test_case.rb#99
  def set_delivery_method(method); end

  # source://actionmailer//lib/action_mailer/test_case.rb#109
  def set_expected_mail; end

  module GeneratedClassMethods
    def _mailer_class; end
    def _mailer_class=(value); end
    def _mailer_class?; end
  end

  module GeneratedInstanceMethods
    def _mailer_class; end
    def _mailer_class=(value); end
    def _mailer_class?; end
  end
end

# source://actionmailer//lib/action_mailer/test_case.rb#48
module ActionMailer::TestCase::Behavior::ClassMethods
  # source://actionmailer//lib/action_mailer/test_case.rb#68
  def determine_default_mailer(name); end

  # source://actionmailer//lib/action_mailer/test_case.rb#60
  def mailer_class; end

  # source://actionmailer//lib/action_mailer/test_case.rb#49
  def tests(mailer); end
end

# source://actionmailer//lib/action_mailer/test_case.rb#16
module ActionMailer::TestCase::ClearTestDeliveries
  extend ::ActiveSupport::Concern

  private

  # source://actionmailer//lib/action_mailer/test_case.rb#25
  def clear_test_deliveries; end
end

# source://actionmailer//lib/action_mailer/test_helper.rb#9
module ActionMailer::TestHelper
  include ::ActiveSupport::Testing::Assertions
  include ::ActiveJob::TestHelper

  # source://actionmailer//lib/action_mailer/test_helper.rb#35
  def assert_emails(number, &block); end

  # source://actionmailer//lib/action_mailer/test_helper.rb#157
  def assert_enqueued_email_with(mailer, method, params: T.unsafe(nil), args: T.unsafe(nil), queue: T.unsafe(nil), &block); end

  # source://actionmailer//lib/action_mailer/test_helper.rb#91
  def assert_enqueued_emails(number, &block); end

  # source://actionmailer//lib/action_mailer/test_helper.rb#63
  def assert_no_emails(&block); end

  # source://actionmailer//lib/action_mailer/test_helper.rb#191
  def assert_no_enqueued_emails(&block); end

  # source://actionmailer//lib/action_mailer/test_helper.rb#249
  def capture_emails(&block); end

  # source://actionmailer//lib/action_mailer/test_helper.rb#231
  def deliver_enqueued_emails(queue: T.unsafe(nil), at: T.unsafe(nil), &block); end

  private

  # source://actionmailer//lib/action_mailer/test_helper.rb#258
  def delivery_job_filter(job); end
end

# source://actionmailer//lib/action_mailer/gem_version.rb#9
module ActionMailer::VERSION; end

# source://actionmailer//lib/action_mailer/gem_version.rb#10
ActionMailer::VERSION::MAJOR = T.let(T.unsafe(nil), Integer)

# source://actionmailer//lib/action_mailer/gem_version.rb#11
ActionMailer::VERSION::MINOR = T.let(T.unsafe(nil), Integer)

# source://actionmailer//lib/action_mailer/gem_version.rb#13
ActionMailer::VERSION::PRE = T.let(T.unsafe(nil), T.untyped)

# source://actionmailer//lib/action_mailer/gem_version.rb#15
ActionMailer::VERSION::STRING = T.let(T.unsafe(nil), String)

# source://actionmailer//lib/action_mailer/gem_version.rb#12
ActionMailer::VERSION::TINY = T.let(T.unsafe(nil), Integer)
