# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `activejob` gem.
# Please instead update this file by running `bin/tapioca gem activejob`.


# source://activejob//lib/active_job/gem_version.rb#3
module ActiveJob
  extend ::ActiveSupport::Autoload

  class << self
    # source://activejob//lib/active_job/queue_adapter.rb#7
    def adapter_name(adapter); end

    # source://activejob//lib/active_job/deprecator.rb#4
    def deprecator; end

    # source://activejob//lib/active_job/gem_version.rb#5
    def gem_version; end

    # source://activejob//lib/active_job/enqueuing.rb#14
    def perform_all_later(*jobs); end

    # source://activejob//lib/active_job.rb#60
    def verbose_enqueue_logs; end

    # source://activejob//lib/active_job.rb#60
    def verbose_enqueue_logs=(_arg0); end

    # source://activejob//lib/active_job/version.rb#7
    def version; end

    private

    # source://activejob//lib/active_job/instrumentation.rb#6
    def instrument_enqueue_all(queue_adapter, jobs); end
  end
end

# source://activejob//lib/active_job/arguments.rb#28
module ActiveJob::Arguments
  extend ::ActiveJob::Arguments

  # source://activejob//lib/active_job/arguments.rb#82
  def deserialize(arguments); end

  # source://activejob//lib/active_job/arguments.rb#34
  def serialize(arguments); end

  # source://activejob//lib/active_job/arguments.rb#38
  def serialize_argument(argument); end

  private

  # source://activejob//lib/active_job/arguments.rb#193
  def convert_to_global_id_hash(argument); end

  # source://activejob//lib/active_job/arguments.rb#138
  def custom_serialized?(hash); end

  # source://activejob//lib/active_job/arguments.rb#111
  def deserialize_argument(argument); end

  # source://activejob//lib/active_job/arguments.rb#134
  def deserialize_global_id(hash); end

  # source://activejob//lib/active_job/arguments.rb#148
  def deserialize_hash(serialized_hash); end

  # source://activejob//lib/active_job/arguments.rb#142
  def serialize_hash(argument); end

  # source://activejob//lib/active_job/arguments.rb#161
  def serialize_hash_key(key); end

  # source://activejob//lib/active_job/arguments.rb#174
  def serialize_indifferent_hash(indifferent_hash); end

  # source://activejob//lib/active_job/arguments.rb#130
  def serialized_global_id?(hash); end

  # source://activejob//lib/active_job/arguments.rb#180
  def transform_symbol_keys(hash, symbol_keys); end
end

# source://activejob//lib/active_job/arguments.rb#90
ActiveJob::Arguments::GLOBALID_KEY = T.let(T.unsafe(nil), String)

# source://activejob//lib/active_job/arguments.rb#98
ActiveJob::Arguments::OBJECT_SERIALIZER_KEY = T.let(T.unsafe(nil), String)

# source://activejob//lib/active_job/arguments.rb#101
ActiveJob::Arguments::RESERVED_KEYS = T.let(T.unsafe(nil), Set)

# source://activejob//lib/active_job/arguments.rb#94
ActiveJob::Arguments::RUBY2_KEYWORDS_KEY = T.let(T.unsafe(nil), String)

# source://activejob//lib/active_job/arguments.rb#92
ActiveJob::Arguments::SYMBOL_KEYS_KEY = T.let(T.unsafe(nil), String)

# source://activejob//lib/active_job/arguments.rb#96
ActiveJob::Arguments::WITH_INDIFFERENT_ACCESS_KEY = T.let(T.unsafe(nil), String)

# source://activejob//lib/active_job/base.rb#63
class ActiveJob::Base
  include ::ActiveJob::Core
  include ::ActiveJob::QueueAdapter
  include ::ActiveJob::QueueName
  include ::ActiveJob::QueuePriority
  include ::ActiveJob::Enqueuing
  include ::ActiveSupport::Rescuable
  include ::ActiveJob::Execution
  include ::ActiveSupport::Callbacks
  include ::ActiveJob::Callbacks
  include ::ActiveJob::Exceptions
  include ::ActiveJob::Instrumentation
  include ::ActiveJob::Logging
  include ::ActiveJob::ExecutionState
  include ::ActiveJob::ConcurrencyControls
  include ::ActiveJob::TestHelper::TestQueueAdapter
  extend ::ActiveJob::Core::ClassMethods
  extend ::ActiveJob::QueueAdapter::ClassMethods
  extend ::ActiveJob::QueueName::ClassMethods
  extend ::ActiveJob::QueuePriority::ClassMethods
  extend ::ActiveJob::Enqueuing::ClassMethods
  extend ::ActiveSupport::Rescuable::ClassMethods
  extend ::ActiveJob::Execution::ClassMethods
  extend ::ActiveSupport::Callbacks::ClassMethods
  extend ::ActiveSupport::DescendantsTracker
  extend ::ActiveJob::Callbacks::ClassMethods
  extend ::ActiveJob::Exceptions::ClassMethods
  extend ::ActiveJob::ConcurrencyControls::ClassMethods
  extend ::ActiveJob::TestHelper::TestQueueAdapter::ClassMethods

  # source://activejob//lib/active_job/base.rb#70
  def __callbacks; end

  # source://activejob//lib/active_job/base.rb#70
  def _enqueue_callbacks; end

  # source://activejob//lib/active_job/base.rb#70
  def _perform_callbacks; end

  # source://activejob//lib/active_job/base.rb#70
  def _run_enqueue_callbacks(&block); end

  # source://activejob//lib/active_job/base.rb#70
  def _run_enqueue_callbacks!(&block); end

  # source://activejob//lib/active_job/base.rb#70
  def _run_perform_callbacks; end

  # source://activejob//lib/active_job/base.rb#70
  def _run_perform_callbacks!(&block); end

  # source://activejob//lib/active_job/base.rb#71
  def after_discard_procs; end

  # source://activejob//lib/active_job/base.rb#71
  def after_discard_procs=(_arg0); end

  # source://activejob//lib/active_job/base.rb#71
  def after_discard_procs?; end

  # source://activejob//lib/active_job/base.rb#76
  def concurrency_duration; end

  # source://activejob//lib/active_job/base.rb#76
  def concurrency_duration=(_arg0); end

  # source://activejob//lib/active_job/base.rb#76
  def concurrency_duration?; end

  # source://activejob//lib/active_job/base.rb#76
  def concurrency_limit; end

  # source://activejob//lib/active_job/base.rb#76
  def concurrency_limit=(_arg0); end

  # source://activejob//lib/active_job/base.rb#76
  def concurrency_limit?; end

  # source://activejob//lib/active_job/base.rb#76
  def concurrency_on_conflict; end

  # source://activejob//lib/active_job/base.rb#76
  def concurrency_on_conflict=(_arg0); end

  # source://activejob//lib/active_job/base.rb#76
  def concurrency_on_conflict?; end

  # source://activejob//lib/active_job/base.rb#73
  def logger; end

  # source://activejob//lib/active_job/base.rb#73
  def logger=(val); end

  # source://activejob//lib/active_job/base.rb#65
  def queue_adapter(&_arg0); end

  # source://activejob//lib/active_job/base.rb#66
  def queue_name_prefix; end

  # source://activejob//lib/active_job/base.rb#66
  def queue_name_prefix=(_arg0); end

  # source://activejob//lib/active_job/base.rb#66
  def queue_name_prefix?; end

  # source://activejob//lib/active_job/base.rb#69
  def rescue_handlers; end

  # source://activejob//lib/active_job/base.rb#69
  def rescue_handlers=(_arg0); end

  # source://activejob//lib/active_job/base.rb#69
  def rescue_handlers?; end

  class << self
    # source://activejob//lib/active_job/base.rb#70
    def __callbacks; end

    # source://activejob//lib/active_job/base.rb#70
    def __callbacks=(value); end

    # source://activejob//lib/active_job/base.rb#70
    def _enqueue_callbacks; end

    # source://activejob//lib/active_job/base.rb#70
    def _enqueue_callbacks=(value); end

    # source://activejob//lib/active_job/base.rb#70
    def _perform_callbacks; end

    # source://activejob//lib/active_job/base.rb#70
    def _perform_callbacks=(value); end

    # source://activejob//lib/active_job/base.rb#65
    def _queue_adapter; end

    # source://activejob//lib/active_job/base.rb#65
    def _queue_adapter=(value); end

    # source://activejob//lib/active_job/base.rb#65
    def _queue_adapter_name; end

    # source://activejob//lib/active_job/base.rb#65
    def _queue_adapter_name=(value); end

    # source://activejob//lib/active_job/test_helper.rb#19
    def _test_adapter; end

    # source://activejob//lib/active_job/test_helper.rb#19
    def _test_adapter=(value); end

    # source://activejob//lib/active_job/base.rb#71
    def after_discard_procs; end

    # source://activejob//lib/active_job/base.rb#71
    def after_discard_procs=(value); end

    # source://activejob//lib/active_job/base.rb#71
    def after_discard_procs?; end

    # source://activejob//lib/active_job/base.rb#76
    def concurrency_duration; end

    # source://activejob//lib/active_job/base.rb#76
    def concurrency_duration=(value); end

    # source://activejob//lib/active_job/base.rb#76
    def concurrency_duration?; end

    # source://activejob//lib/active_job/base.rb#76
    def concurrency_group; end

    # source://activejob//lib/active_job/base.rb#76
    def concurrency_group=(value); end

    # source://activejob//lib/active_job/base.rb#76
    def concurrency_group?; end

    # source://activejob//lib/active_job/base.rb#76
    def concurrency_key; end

    # source://activejob//lib/active_job/base.rb#76
    def concurrency_key=(value); end

    # source://activejob//lib/active_job/base.rb#76
    def concurrency_key?; end

    # source://activejob//lib/active_job/base.rb#76
    def concurrency_limit; end

    # source://activejob//lib/active_job/base.rb#76
    def concurrency_limit=(value); end

    # source://activejob//lib/active_job/base.rb#76
    def concurrency_limit?; end

    # source://activejob//lib/active_job/base.rb#76
    def concurrency_on_conflict; end

    # source://activejob//lib/active_job/base.rb#76
    def concurrency_on_conflict=(value); end

    # source://activejob//lib/active_job/base.rb#76
    def concurrency_on_conflict?; end

    # source://activejob//lib/active_job/base.rb#68
    def enqueue_after_transaction_commit; end

    # source://activejob//lib/active_job/base.rb#68
    def enqueue_after_transaction_commit=(value); end

    # source://activejob//lib/active_job/base.rb#73
    def log_arguments; end

    # source://activejob//lib/active_job/base.rb#73
    def log_arguments=(value); end

    # source://activejob//lib/active_job/base.rb#73
    def log_arguments?; end

    # source://activejob//lib/active_job/base.rb#73
    def logger; end

    # source://activejob//lib/active_job/base.rb#73
    def logger=(val); end

    # source://activejob//lib/active_job/base.rb#67
    def priority; end

    # source://activejob//lib/active_job/base.rb#67
    def priority=(value); end

    # source://activejob//lib/active_job/base.rb#67
    def priority?; end

    # source://activejob//lib/active_job/base.rb#66
    def queue_name; end

    # source://activejob//lib/active_job/base.rb#66
    def queue_name=(value); end

    # source://activejob//lib/active_job/base.rb#66
    def queue_name?; end

    # source://activejob//lib/active_job/base.rb#66
    def queue_name_delimiter; end

    # source://activejob//lib/active_job/base.rb#66
    def queue_name_delimiter=(value); end

    # source://activejob//lib/active_job/base.rb#66
    def queue_name_delimiter?; end

    # source://activejob//lib/active_job/base.rb#66
    def queue_name_prefix; end

    # source://activejob//lib/active_job/base.rb#66
    def queue_name_prefix=(value); end

    # source://activejob//lib/active_job/base.rb#66
    def queue_name_prefix?; end

    # source://activejob//lib/active_job/base.rb#69
    def rescue_handlers; end

    # source://activejob//lib/active_job/base.rb#69
    def rescue_handlers=(value); end

    # source://activejob//lib/active_job/base.rb#69
    def rescue_handlers?; end

    # source://activejob//lib/active_job/base.rb#71
    def retry_jitter; end

    # source://activejob//lib/active_job/base.rb#71
    def retry_jitter=(value); end

    private

    # source://activejob//lib/active_job/base.rb#70
    def __class_attr___callbacks; end

    # source://activejob//lib/active_job/base.rb#70
    def __class_attr___callbacks=(new_value); end

    # source://activejob//lib/active_job/base.rb#65
    def __class_attr__queue_adapter; end

    # source://activejob//lib/active_job/base.rb#65
    def __class_attr__queue_adapter=(new_value); end

    # source://activejob//lib/active_job/base.rb#65
    def __class_attr__queue_adapter_name; end

    # source://activejob//lib/active_job/base.rb#65
    def __class_attr__queue_adapter_name=(new_value); end

    # source://activejob//lib/active_job/test_helper.rb#19
    def __class_attr__test_adapter; end

    # source://activejob//lib/active_job/test_helper.rb#19
    def __class_attr__test_adapter=(new_value); end

    # source://activejob//lib/active_job/base.rb#71
    def __class_attr_after_discard_procs; end

    # source://activejob//lib/active_job/base.rb#71
    def __class_attr_after_discard_procs=(new_value); end

    # source://activejob//lib/active_job/base.rb#76
    def __class_attr_concurrency_duration; end

    # source://activejob//lib/active_job/base.rb#76
    def __class_attr_concurrency_duration=(new_value); end

    # source://activejob//lib/active_job/base.rb#76
    def __class_attr_concurrency_group; end

    # source://activejob//lib/active_job/base.rb#76
    def __class_attr_concurrency_group=(new_value); end

    # source://activejob//lib/active_job/base.rb#76
    def __class_attr_concurrency_key; end

    # source://activejob//lib/active_job/base.rb#76
    def __class_attr_concurrency_key=(new_value); end

    # source://activejob//lib/active_job/base.rb#76
    def __class_attr_concurrency_limit; end

    # source://activejob//lib/active_job/base.rb#76
    def __class_attr_concurrency_limit=(new_value); end

    # source://activejob//lib/active_job/base.rb#76
    def __class_attr_concurrency_on_conflict; end

    # source://activejob//lib/active_job/base.rb#76
    def __class_attr_concurrency_on_conflict=(new_value); end

    # source://activejob//lib/active_job/base.rb#68
    def __class_attr_enqueue_after_transaction_commit; end

    # source://activejob//lib/active_job/base.rb#68
    def __class_attr_enqueue_after_transaction_commit=(new_value); end

    # source://activejob//lib/active_job/base.rb#73
    def __class_attr_log_arguments; end

    # source://activejob//lib/active_job/base.rb#73
    def __class_attr_log_arguments=(new_value); end

    # source://activejob//lib/active_job/base.rb#67
    def __class_attr_priority; end

    # source://activejob//lib/active_job/base.rb#67
    def __class_attr_priority=(new_value); end

    # source://activejob//lib/active_job/base.rb#66
    def __class_attr_queue_name; end

    # source://activejob//lib/active_job/base.rb#66
    def __class_attr_queue_name=(new_value); end

    # source://activejob//lib/active_job/base.rb#66
    def __class_attr_queue_name_delimiter; end

    # source://activejob//lib/active_job/base.rb#66
    def __class_attr_queue_name_delimiter=(new_value); end

    # source://activejob//lib/active_job/base.rb#66
    def __class_attr_queue_name_prefix; end

    # source://activejob//lib/active_job/base.rb#66
    def __class_attr_queue_name_prefix=(new_value); end

    # source://activejob//lib/active_job/base.rb#69
    def __class_attr_rescue_handlers; end

    # source://activejob//lib/active_job/base.rb#69
    def __class_attr_rescue_handlers=(new_value); end

    # source://activejob//lib/active_job/base.rb#71
    def __class_attr_retry_jitter; end

    # source://activejob//lib/active_job/base.rb#71
    def __class_attr_retry_jitter=(new_value); end
  end
end

# source://activejob//lib/active_job/callbacks.rb#18
module ActiveJob::Callbacks
  extend ::ActiveSupport::Concern
  extend ::ActiveSupport::Callbacks
  include GeneratedInstanceMethods
  include ::ActiveSupport::Callbacks

  mixes_in_class_methods GeneratedClassMethods
  mixes_in_class_methods ::ActiveSupport::Callbacks::ClassMethods
  mixes_in_class_methods ::ActiveSupport::DescendantsTracker
  mixes_in_class_methods ::ActiveJob::Callbacks::ClassMethods

  class << self
    # source://activejob//lib/active_job/callbacks.rb#23
    def __callbacks; end

    # source://activejob//lib/active_job/callbacks.rb#24
    def _execute_callbacks; end

    # source://activejob//lib/active_job/callbacks.rb#24
    def _run_execute_callbacks; end

    # source://activejob//lib/active_job/callbacks.rb#24
    def _run_execute_callbacks!(&block); end

    private

    # source://activejob//lib/active_job/callbacks.rb#23
    def __class_attr___callbacks; end
  end

  module GeneratedClassMethods
    def __callbacks; end
    def __callbacks=(value); end
  end

  module GeneratedInstanceMethods
    def __callbacks; end
  end
end

# source://activejob//lib/active_job/callbacks.rb#34
module ActiveJob::Callbacks::ClassMethods
  # source://activejob//lib/active_job/callbacks.rb#141
  def after_enqueue(*filters, &blk); end

  # source://activejob//lib/active_job/callbacks.rb#69
  def after_perform(*filters, &blk); end

  # source://activejob//lib/active_job/callbacks.rb#162
  def around_enqueue(*filters, &blk); end

  # source://activejob//lib/active_job/callbacks.rb#102
  def around_perform(*filters, &blk); end

  # source://activejob//lib/active_job/callbacks.rb#121
  def before_enqueue(*filters, &blk); end

  # source://activejob//lib/active_job/callbacks.rb#50
  def before_perform(*filters, &blk); end
end

# source://activejob//lib/active_job/configured_job.rb#4
class ActiveJob::ConfiguredJob
  # source://activejob//lib/active_job/configured_job.rb#5
  def initialize(job_class, options = T.unsafe(nil)); end

  # source://activejob//lib/active_job/configured_job.rb#14
  def perform_later(*_arg0, **_arg1, &_arg2); end

  # source://activejob//lib/active_job/configured_job.rb#10
  def perform_now(*_arg0, **_arg1, &_arg2); end
end

# source://activejob//lib/active_job/continuable.rb#13
module ActiveJob::Continuable
  extend ::ActiveSupport::Concern
  include GeneratedInstanceMethods

  mixes_in_class_methods GeneratedClassMethods

  # source://activejob//lib/active_job/continuable.rb#62
  def checkpoint!; end

  # source://activejob//lib/active_job/continuable.rb#33
  def continuation; end

  # source://activejob//lib/active_job/continuable.rb#33
  def continuation=(_arg0); end

  # source://activejob//lib/active_job/continuable.rb#56
  def deserialize(job_data); end

  # source://activejob//lib/active_job/continuable.rb#66
  def interrupt!(reason:); end

  # source://activejob//lib/active_job/continuable.rb#31
  def resumptions; end

  # source://activejob//lib/active_job/continuable.rb#31
  def resumptions=(_arg0); end

  # source://activejob//lib/active_job/continuable.rb#52
  def serialize; end

  # source://activejob//lib/active_job/continuable.rb#36
  def step(step_name, start: T.unsafe(nil), isolated: T.unsafe(nil), &block); end

  private

  # source://activejob//lib/active_job/continuable.rb#72
  def continue(&block); end

  # source://activejob//lib/active_job/continuable.rb#91
  def resume_job(exception); end

  module GeneratedClassMethods
    def max_resumptions; end
    def max_resumptions=(value); end
    def max_resumptions?; end
    def resume_errors_after_advancing; end
    def resume_errors_after_advancing=(value); end
    def resume_errors_after_advancing?; end
    def resume_options; end
    def resume_options=(value); end
    def resume_options?; end
  end

  module GeneratedInstanceMethods
    def max_resumptions; end
    def max_resumptions?; end
    def resume_errors_after_advancing; end
    def resume_errors_after_advancing?; end
    def resume_options; end
    def resume_options?; end
  end
end

# source://activejob//lib/active_job/continuation.rb#186
class ActiveJob::Continuation
  include ::ActiveJob::Continuation::Validation
  extend ::ActiveSupport::Autoload

  # source://activejob//lib/active_job/continuation.rb#214
  def initialize(job, serialized_progress); end

  # source://activejob//lib/active_job/continuation.rb#256
  def advanced?; end

  # source://activejob//lib/active_job/continuation.rb#242
  def description; end

  # source://activejob//lib/active_job/continuation.rb#260
  def instrumentation; end

  # source://activejob//lib/active_job/continuation.rb#252
  def started?; end

  # source://activejob//lib/active_job/continuation.rb#224
  def step(name, **options, &block); end

  # source://activejob//lib/active_job/continuation.rb#235
  def to_h; end

  private

  # source://activejob//lib/active_job/continuation.rb#267
  def completed; end

  # source://activejob//lib/active_job/continuation.rb#277
  def completed?(name); end

  # source://activejob//lib/active_job/continuation.rb#267
  def current; end

  # source://activejob//lib/active_job/continuation.rb#267
  def encountered; end

  # source://activejob//lib/active_job/continuation.rb#326
  def instrument(*_arg0, **_arg1, &_arg2); end

  # source://activejob//lib/active_job/continuation.rb#315
  def instrumenting_step(step, &block); end

  # source://activejob//lib/active_job/continuation.rb#273
  def isolating?; end

  # source://activejob//lib/active_job/continuation.rb#267
  def job; end

  # source://activejob//lib/active_job/continuation.rb#281
  def new_step(*args, **options); end

  # source://activejob//lib/active_job/continuation.rb#289
  def run_step(name, start:, isolated:, &block); end

  # source://activejob//lib/active_job/continuation.rb#299
  def run_step_inline(name, start:, **options, &block); end

  # source://activejob//lib/active_job/continuation.rb#269
  def running_step?; end

  # source://activejob//lib/active_job/continuation.rb#285
  def skip_step(name); end
end

# source://activejob//lib/active_job/continuation.rb#203
class ActiveJob::Continuation::CheckpointError < ::ActiveJob::Continuation::Error; end

# source://activejob//lib/active_job/continuation.rb#197
class ActiveJob::Continuation::Error < ::StandardError; end

# source://activejob//lib/active_job/continuation.rb#194
class ActiveJob::Continuation::Interrupt < ::Exception; end

# source://activejob//lib/active_job/continuation.rb#200
class ActiveJob::Continuation::InvalidStepError < ::ActiveJob::Continuation::Error; end

# source://activejob//lib/active_job/continuation.rb#210
class ActiveJob::Continuation::ResumeLimitError < ::ActiveJob::Continuation::Error; end

# source://activejob//lib/active_job/continuation/step.rb#18
class ActiveJob::Continuation::Step
  # source://activejob//lib/active_job/continuation/step.rb#25
  def initialize(name, cursor, job:, resumed:); end

  # source://activejob//lib/active_job/continuation/step.rb#49
  def advance!(from: T.unsafe(nil)); end

  # source://activejob//lib/active_job/continuation/step.rb#67
  def advanced?; end

  # source://activejob//lib/active_job/continuation/step.rb#35
  def checkpoint!; end

  # source://activejob//lib/active_job/continuation/step.rb#23
  def cursor; end

  # source://activejob//lib/active_job/continuation/step.rb#75
  def description; end

  # source://activejob//lib/active_job/continuation/step.rb#20
  def name; end

  # source://activejob//lib/active_job/continuation/step.rb#62
  def resumed?; end

  # source://activejob//lib/active_job/continuation/step.rb#40
  def set!(cursor); end

  # source://activejob//lib/active_job/continuation/step.rb#71
  def to_a; end

  private

  # source://activejob//lib/active_job/continuation/step.rb#80
  def initial_cursor; end

  # source://activejob//lib/active_job/continuation/step.rb#80
  def job; end
end

# source://activejob//lib/active_job/continuation.rb#206
class ActiveJob::Continuation::UnadvanceableCursorError < ::ActiveJob::Continuation::Error; end

# source://activejob//lib/active_job/continuation/validation.rb#5
module ActiveJob::Continuation::Validation
  private

  # source://activejob//lib/active_job/continuation/validation.rb#45
  def raise_step_error!(message); end

  # source://activejob//lib/active_job/continuation/validation.rb#7
  def validate_step!(name); end

  # source://activejob//lib/active_job/continuation/validation.rb#39
  def validate_step_expected_order!(name); end

  # source://activejob//lib/active_job/continuation/validation.rb#21
  def validate_step_not_encountered!(name); end

  # source://activejob//lib/active_job/continuation/validation.rb#27
  def validate_step_not_nested!(name); end

  # source://activejob//lib/active_job/continuation/validation.rb#33
  def validate_step_resume_expected!(name); end

  # source://activejob//lib/active_job/continuation/validation.rb#15
  def validate_step_symbol!(name); end
end

# source://activejob//lib/active_job/core.rb#15
module ActiveJob::Core
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::ActiveJob::Core::ClassMethods

  # source://activejob//lib/active_job/core.rb#103
  def initialize(*arguments, **_arg1); end

  # source://activejob//lib/active_job/core.rb#19
  def arguments; end

  # source://activejob//lib/active_job/core.rb#19
  def arguments=(_arg0); end

  # source://activejob//lib/active_job/core.rb#160
  def deserialize(job_data); end

  # source://activejob//lib/active_job/core.rb#63
  def enqueue_error; end

  # source://activejob//lib/active_job/core.rb#63
  def enqueue_error=(_arg0); end

  # source://activejob//lib/active_job/core.rb#53
  def enqueued_at; end

  # source://activejob//lib/active_job/core.rb#53
  def enqueued_at=(_arg0); end

  # source://activejob//lib/active_job/core.rb#44
  def exception_executions; end

  # source://activejob//lib/active_job/core.rb#44
  def exception_executions=(_arg0); end

  # source://activejob//lib/active_job/core.rb#38
  def executions; end

  # source://activejob//lib/active_job/core.rb#38
  def executions=(_arg0); end

  # source://activejob//lib/active_job/core.rb#26
  def job_id; end

  # source://activejob//lib/active_job/core.rb#26
  def job_id=(_arg0); end

  # source://activejob//lib/active_job/core.rb#47
  def locale; end

  # source://activejob//lib/active_job/core.rb#47
  def locale=(_arg0); end

  # source://activejob//lib/active_job/core.rb#32
  def priority=(_arg0); end

  # source://activejob//lib/active_job/core.rb#35
  def provider_job_id; end

  # source://activejob//lib/active_job/core.rb#35
  def provider_job_id=(_arg0); end

  # source://activejob//lib/active_job/core.rb#29
  def queue_name=(_arg0); end

  # source://activejob//lib/active_job/core.rb#23
  def scheduled_at; end

  # source://activejob//lib/active_job/core.rb#23
  def scheduled_at=(_arg0); end

  # source://activejob//lib/active_job/core.rb#117
  def serialize; end

  # source://activejob//lib/active_job/core.rb#20
  def serialized_arguments=(_arg0); end

  # source://activejob//lib/active_job/core.rb#175
  def set(options = T.unsafe(nil)); end

  # source://activejob//lib/active_job/core.rb#56
  def successfully_enqueued=(_arg0); end

  # source://activejob//lib/active_job/core.rb#58
  def successfully_enqueued?; end

  # source://activejob//lib/active_job/core.rb#50
  def timezone; end

  # source://activejob//lib/active_job/core.rb#50
  def timezone=(_arg0); end

  private

  # source://activejob//lib/active_job/core.rb#208
  def arguments_serialized?; end

  # source://activejob//lib/active_job/core.rb#204
  def deserialize_arguments(serialized_args); end

  # source://activejob//lib/active_job/core.rb#193
  def deserialize_arguments_if_needed; end

  # source://activejob//lib/active_job/core.rb#212
  def deserialize_time(time); end

  # source://activejob//lib/active_job/core.rb#200
  def serialize_arguments(arguments); end

  # source://activejob//lib/active_job/core.rb#185
  def serialize_arguments_if_needed(arguments); end
end

# source://activejob//lib/active_job/core.rb#67
module ActiveJob::Core::ClassMethods
  # source://activejob//lib/active_job/core.rb#69
  def deserialize(job_data); end

  # source://activejob//lib/active_job/core.rb#96
  def set(options = T.unsafe(nil)); end
end

# source://activejob//lib/active_job/arguments.rb#10
class ActiveJob::DeserializationError < ::StandardError
  # source://activejob//lib/active_job/arguments.rb#11
  def initialize; end
end

# source://activejob//lib/active_job/enqueue_after_transaction_commit.rb#4
module ActiveJob::EnqueueAfterTransactionCommit
  private

  # source://activejob//lib/active_job/enqueue_after_transaction_commit.rb#6
  def raw_enqueue; end
end

# source://activejob//lib/active_job/enqueuing.rb#8
class ActiveJob::EnqueueError < ::StandardError; end

# source://activejob//lib/active_job/enqueuing.rb#40
module ActiveJob::Enqueuing
  extend ::ActiveSupport::Concern
  include GeneratedInstanceMethods

  mixes_in_class_methods GeneratedClassMethods
  mixes_in_class_methods ::ActiveJob::Enqueuing::ClassMethods

  # source://activejob//lib/active_job/enqueuing.rb#112
  def enqueue(options = T.unsafe(nil)); end

  private

  # source://activejob//lib/active_job/enqueuing.rb#132
  def _raw_enqueue; end

  # source://activejob//lib/active_job/enqueuing.rb#126
  def raw_enqueue; end

  module GeneratedClassMethods
    def enqueue_after_transaction_commit; end
    def enqueue_after_transaction_commit=(value); end
  end

  module GeneratedInstanceMethods; end
end

# source://activejob//lib/active_job/enqueuing.rb#57
module ActiveJob::Enqueuing::ClassMethods
  # source://activejob//lib/active_job/enqueuing.rb#81
  def perform_later(*_arg0, **_arg1, &_arg2); end

  private

  # source://activejob//lib/active_job/enqueuing.rb#91
  def job_or_instantiate(*args, **_arg1, &_arg2); end
end

# source://activejob//lib/active_job/exceptions.rb#7
module ActiveJob::Exceptions
  extend ::ActiveSupport::Concern
  include GeneratedInstanceMethods

  mixes_in_class_methods GeneratedClassMethods
  mixes_in_class_methods ::ActiveJob::Exceptions::ClassMethods

  # source://activejob//lib/active_job/exceptions.rb#158
  def retry_job(options = T.unsafe(nil)); end

  private

  # source://activejob//lib/active_job/exceptions.rb#171
  def determine_delay(seconds_or_duration_or_algorithm:, executions:, jitter: T.unsafe(nil)); end

  # source://activejob//lib/active_job/exceptions.rb#192
  def determine_jitter_for_delay(delay, jitter); end

  # source://activejob//lib/active_job/exceptions.rb#197
  def executions_for(exceptions); end

  # source://activejob//lib/active_job/exceptions.rb#206
  def run_after_discard_procs(exception); end

  module GeneratedClassMethods
    def after_discard_procs; end
    def after_discard_procs=(value); end
    def after_discard_procs?; end
    def retry_jitter; end
    def retry_jitter=(value); end
  end

  module GeneratedInstanceMethods
    def after_discard_procs; end
    def after_discard_procs=(value); end
    def after_discard_procs?; end
  end
end

# source://activejob//lib/active_job/exceptions.rb#15
module ActiveJob::Exceptions::ClassMethods
  # source://activejob//lib/active_job/exceptions.rb#131
  def after_discard(&blk); end

  # source://activejob//lib/active_job/exceptions.rb#109
  def discard_on(*exceptions, report: T.unsafe(nil)); end

  # source://activejob//lib/active_job/exceptions.rb#64
  def retry_on(*exceptions, wait: T.unsafe(nil), attempts: T.unsafe(nil), queue: T.unsafe(nil), priority: T.unsafe(nil), jitter: T.unsafe(nil), report: T.unsafe(nil)); end
end

# source://activejob//lib/active_job/exceptions.rb#168
ActiveJob::Exceptions::JITTER_DEFAULT = T.let(T.unsafe(nil), Object)

# source://activejob//lib/active_job/execution.rb#12
module ActiveJob::Execution
  extend ::ActiveSupport::Concern
  include GeneratedInstanceMethods
  include ::ActiveSupport::Rescuable

  mixes_in_class_methods GeneratedClassMethods
  mixes_in_class_methods ::ActiveSupport::Rescuable::ClassMethods
  mixes_in_class_methods ::ActiveJob::Execution::ClassMethods

  # source://activejob//lib/active_job/execution.rb#60
  def perform(*_arg0); end

  # source://activejob//lib/active_job/execution.rb#45
  def perform_now; end

  private

  # source://activejob//lib/active_job/execution.rb#65
  def _perform_job; end

  module GeneratedClassMethods
    def rescue_handlers; end
    def rescue_handlers=(value); end
    def rescue_handlers?; end
  end

  module GeneratedInstanceMethods
    def rescue_handlers; end
    def rescue_handlers=(value); end
    def rescue_handlers?; end
  end
end

# source://activejob//lib/active_job/execution.rb#17
module ActiveJob::Execution::ClassMethods
  # source://activejob//lib/active_job/execution.rb#26
  def execute(job_data); end

  # source://activejob//lib/active_job/execution.rb#22
  def perform_now(*_arg0, **_arg1, &_arg2); end
end

# source://activejob//lib/active_job/execution_state.rb#4
module ActiveJob::ExecutionState
  # source://activejob//lib/active_job/execution_state.rb#5
  def perform_now; end
end

# source://activejob//lib/active_job/instrumentation.rb#16
module ActiveJob::Instrumentation
  extend ::ActiveSupport::Concern

  # source://activejob//lib/active_job/instrumentation.rb#29
  def instrument(operation, payload = T.unsafe(nil), &block); end

  # source://activejob//lib/active_job/instrumentation.rb#25
  def perform_now; end

  private

  # source://activejob//lib/active_job/instrumentation.rb#42
  def _perform_job; end

  # source://activejob//lib/active_job/instrumentation.rb#47
  def halted_callback_hook(*_arg0); end
end

# source://activejob//lib/active_job/log_subscriber.rb#6
class ActiveJob::LogSubscriber < ::ActiveSupport::LogSubscriber
  # source://activejob//lib/active_job/log_subscriber.rb#7
  def backtrace_cleaner; end

  # source://activejob//lib/active_job/log_subscriber.rb#7
  def backtrace_cleaner=(_arg0); end

  # source://activejob//lib/active_job/log_subscriber.rb#7
  def backtrace_cleaner?; end

  # source://activejob//lib/active_job/log_subscriber.rb#131
  def discard(event); end

  # source://activejob//lib/active_job/log_subscriber.rb#9
  def enqueue(event); end

  # source://activejob//lib/active_job/log_subscriber.rb#49
  def enqueue_all(event); end

  # source://activejob//lib/active_job/log_subscriber.rb#29
  def enqueue_at(event); end

  # source://activejob//lib/active_job/log_subscriber.rb#106
  def enqueue_retry(event); end

  # source://activejob//lib/active_job/log_subscriber.rb#141
  def interrupt(event); end

  # source://activejob//lib/active_job/log_subscriber.rb#86
  def perform(event); end

  # source://activejob//lib/active_job/log_subscriber.rb#76
  def perform_start(event); end

  # source://activejob//lib/active_job/log_subscriber.rb#149
  def resume(event); end

  # source://activejob//lib/active_job/log_subscriber.rb#121
  def retry_stopped(event); end

  # source://activejob//lib/active_job/log_subscriber.rb#178
  def step(event); end

  # source://activejob//lib/active_job/log_subscriber.rb#157
  def step_skipped(event); end

  # source://activejob//lib/active_job/log_subscriber.rb#165
  def step_started(event); end

  private

  # source://activejob//lib/active_job/log_subscriber.rb#204
  def args_info(job); end

  # source://activejob//lib/active_job/log_subscriber.rb#258
  def enqueue_source_location; end

  # source://activejob//lib/active_job/log_subscriber.rb#262
  def enqueued_jobs_message(adapter, enqueued_jobs); end

  # source://activejob//lib/active_job/log_subscriber.rb#242
  def error(progname = T.unsafe(nil), &block); end

  # source://activejob//lib/active_job/log_subscriber.rb#213
  def format(arg); end

  # source://activejob//lib/active_job/log_subscriber.rb#234
  def info(progname = T.unsafe(nil), &block); end

  # source://activejob//lib/active_job/log_subscriber.rb#250
  def log_enqueue_source; end

  # source://activejob//lib/active_job/log_subscriber.rb#230
  def logger; end

  # source://activejob//lib/active_job/log_subscriber.rb#200
  def queue_name(event); end

  # source://activejob//lib/active_job/log_subscriber.rb#226
  def scheduled_at(event); end

  class << self
    # source://activejob//lib/active_job/log_subscriber.rb#7
    def backtrace_cleaner; end

    # source://activejob//lib/active_job/log_subscriber.rb#7
    def backtrace_cleaner=(value); end

    # source://activejob//lib/active_job/log_subscriber.rb#7
    def backtrace_cleaner?; end

    private

    # source://activejob//lib/active_job/log_subscriber.rb#7
    def __class_attr_backtrace_cleaner; end

    # source://activejob//lib/active_job/log_subscriber.rb#7
    def __class_attr_backtrace_cleaner=(new_value); end

    # source://activejob//lib/active_job/log_subscriber.rb#27
    def __class_attr_log_levels; end

    # source://activejob//lib/active_job/log_subscriber.rb#27
    def __class_attr_log_levels=(new_value); end
  end
end

# source://activejob//lib/active_job/logging.rb#7
module ActiveJob::Logging
  extend ::ActiveSupport::Concern
  include GeneratedInstanceMethods

  mixes_in_class_methods GeneratedClassMethods

  # source://activejob//lib/active_job/logging.rb#31
  def perform_now; end

  private

  # source://activejob//lib/active_job/logging.rb#45
  def logger_tagged_by_active_job?; end

  # source://activejob//lib/active_job/logging.rb#36
  def tag_logger(*tags, &block); end

  module GeneratedClassMethods
    def log_arguments; end
    def log_arguments=(value); end
    def log_arguments?; end
  end

  module GeneratedInstanceMethods; end
end

# source://activejob//lib/active_job/queue_adapter.rb#20
module ActiveJob::QueueAdapter
  extend ::ActiveSupport::Concern
  include GeneratedInstanceMethods

  mixes_in_class_methods GeneratedClassMethods
  mixes_in_class_methods ::ActiveJob::QueueAdapter::ClassMethods

  module GeneratedClassMethods
    def _queue_adapter; end
    def _queue_adapter=(value); end
    def _queue_adapter_name; end
    def _queue_adapter_name=(value); end
  end

  module GeneratedInstanceMethods; end
end

# source://activejob//lib/active_job/queue_adapter.rb#31
module ActiveJob::QueueAdapter::ClassMethods
  # source://activejob//lib/active_job/queue_adapter.rb#34
  def queue_adapter; end

  # source://activejob//lib/active_job/queue_adapter.rb#49
  def queue_adapter=(name_or_adapter); end

  # source://activejob//lib/active_job/queue_adapter.rb#41
  def queue_adapter_name; end

  private

  # source://activejob//lib/active_job/queue_adapter.rb#66
  def assign_adapter(adapter_name, queue_adapter); end

  # source://activejob//lib/active_job/queue_adapter.rb#73
  def queue_adapter?(object); end
end

# source://activejob//lib/active_job/queue_adapter.rb#71
ActiveJob::QueueAdapter::ClassMethods::QUEUE_ADAPTER_METHODS = T.let(T.unsafe(nil), Array)

# source://activejob//lib/active_job/queue_adapters.rb#112
module ActiveJob::QueueAdapters
  extend ::ActiveSupport::Autoload

  class << self
    # source://activejob//lib/active_job/queue_adapters.rb#135
    def lookup(name); end
  end
end

# source://activejob//lib/active_job/queue_adapters.rb#127
ActiveJob::QueueAdapters::ADAPTER = T.let(T.unsafe(nil), String)

# source://activejob//lib/active_job/queue_adapters/abstract_adapter.rb#9
class ActiveJob::QueueAdapters::AbstractAdapter
  # source://activejob//lib/active_job/queue_adapters/abstract_adapter.rb#12
  def enqueue(job); end

  # source://activejob//lib/active_job/queue_adapters/abstract_adapter.rb#16
  def enqueue_at(job, timestamp); end

  # source://activejob//lib/active_job/queue_adapters/abstract_adapter.rb#10
  def stopping; end

  # source://activejob//lib/active_job/queue_adapters/abstract_adapter.rb#10
  def stopping=(_arg0); end

  # source://activejob//lib/active_job/queue_adapters/abstract_adapter.rb#20
  def stopping?; end
end

# source://activejob//lib/active_job/queue_adapters/async_adapter.rb#33
class ActiveJob::QueueAdapters::AsyncAdapter < ::ActiveJob::QueueAdapters::AbstractAdapter
  # source://activejob//lib/active_job/queue_adapters/async_adapter.rb#35
  def initialize(**executor_options); end

  # source://activejob//lib/active_job/queue_adapters/async_adapter.rb#39
  def enqueue(job); end

  # source://activejob//lib/active_job/queue_adapters/async_adapter.rb#43
  def enqueue_at(job, timestamp); end

  # source://activejob//lib/active_job/queue_adapters/async_adapter.rb#55
  def immediate=(immediate); end

  # source://activejob//lib/active_job/queue_adapters/async_adapter.rb#50
  def shutdown(wait: T.unsafe(nil)); end
end

# source://activejob//lib/active_job/queue_adapters/async_adapter.rb#63
class ActiveJob::QueueAdapters::AsyncAdapter::JobWrapper
  # source://activejob//lib/active_job/queue_adapters/async_adapter.rb#64
  def initialize(job); end

  # source://activejob//lib/active_job/queue_adapters/async_adapter.rb#69
  def perform; end
end

# source://activejob//lib/active_job/queue_adapters/async_adapter.rb#74
class ActiveJob::QueueAdapters::AsyncAdapter::Scheduler
  # source://activejob//lib/active_job/queue_adapters/async_adapter.rb#86
  def initialize(**options); end

  # source://activejob//lib/active_job/queue_adapters/async_adapter.rb#96
  def enqueue(job, queue_name:); end

  # source://activejob//lib/active_job/queue_adapters/async_adapter.rb#100
  def enqueue_at(job, timestamp, queue_name:); end

  # source://activejob//lib/active_job/queue_adapters/async_adapter.rb#114
  def executor; end

  # source://activejob//lib/active_job/queue_adapters/async_adapter.rb#84
  def immediate; end

  # source://activejob//lib/active_job/queue_adapters/async_adapter.rb#84
  def immediate=(_arg0); end

  # source://activejob//lib/active_job/queue_adapters/async_adapter.rb#109
  def shutdown(wait: T.unsafe(nil)); end
end

# source://activejob//lib/active_job/queue_adapters/async_adapter.rb#75
ActiveJob::QueueAdapters::AsyncAdapter::Scheduler::DEFAULT_EXECUTOR_OPTIONS = T.let(T.unsafe(nil), Hash)

# source://activejob//lib/active_job/queue_adapters/inline_adapter.rb#13
class ActiveJob::QueueAdapters::InlineAdapter < ::ActiveJob::QueueAdapters::AbstractAdapter
  # source://activejob//lib/active_job/queue_adapters/inline_adapter.rb#14
  def enqueue(job); end

  # source://activejob//lib/active_job/queue_adapters/inline_adapter.rb#18
  def enqueue_at(*_arg0); end
end

# source://activejob//lib/active_job/queue_adapters/test_adapter.rb#14
class ActiveJob::QueueAdapters::TestAdapter < ::ActiveJob::QueueAdapters::AbstractAdapter
  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#15
  def at; end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#15
  def at=(_arg0); end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#28
  def enqueue(job); end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#33
  def enqueue_at(job, timestamp); end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#19
  def enqueued_jobs; end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#16
  def enqueued_jobs=(_arg0); end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#15
  def filter; end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#15
  def filter=(_arg0); end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#15
  def perform_enqueued_at_jobs; end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#15
  def perform_enqueued_at_jobs=(_arg0); end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#15
  def perform_enqueued_jobs; end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#15
  def perform_enqueued_jobs=(_arg0); end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#24
  def performed_jobs; end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#16
  def performed_jobs=(_arg0); end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#15
  def queue; end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#15
  def queue=(_arg0); end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#15
  def reject; end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#15
  def reject=(_arg0); end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#15
  def stopping; end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#15
  def stopping=(_arg0); end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#38
  def stopping?; end

  private

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#83
  def filter_as_proc(filter); end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#61
  def filtered?(job); end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#75
  def filtered_job_class?(job); end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#69
  def filtered_queue?(job); end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#65
  def filtered_time?(job); end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#43
  def job_to_hash(job, extras = T.unsafe(nil)); end

  # source://activejob//lib/active_job/queue_adapters/test_adapter.rb#52
  def perform_or_enqueue(perform, job, job_data); end
end

# source://activejob//lib/active_job/queue_name.rb#4
module ActiveJob::QueueName
  extend ::ActiveSupport::Concern
  include GeneratedInstanceMethods

  mixes_in_class_methods GeneratedClassMethods
  mixes_in_class_methods ::ActiveJob::QueueName::ClassMethods

  # source://activejob//lib/active_job/queue_name.rb#61
  def queue_name; end

  module GeneratedClassMethods
    def queue_name; end
    def queue_name=(value); end
    def queue_name?; end
    def queue_name_delimiter; end
    def queue_name_delimiter=(value); end
    def queue_name_delimiter?; end
    def queue_name_prefix; end
    def queue_name_prefix=(value); end
    def queue_name_prefix?; end
  end

  module GeneratedInstanceMethods
    def queue_name_prefix; end
    def queue_name_prefix=(value); end
    def queue_name_prefix?; end
  end
end

# source://activejob//lib/active_job/queue_name.rb#8
module ActiveJob::QueueName::ClassMethods
  # source://activejob//lib/active_job/queue_name.rb#9
  def default_queue_name; end

  # source://activejob//lib/active_job/queue_name.rb#9
  def default_queue_name=(val); end

  # source://activejob//lib/active_job/queue_name.rb#39
  def queue_as(part_name = T.unsafe(nil), &block); end

  # source://activejob//lib/active_job/queue_name.rb#47
  def queue_name_from_part(part_name); end

  class << self
    # source://activejob//lib/active_job/queue_name.rb#9
    def default_queue_name; end

    # source://activejob//lib/active_job/queue_name.rb#9
    def default_queue_name=(val); end
  end
end

# source://activejob//lib/active_job/queue_priority.rb#4
module ActiveJob::QueuePriority
  extend ::ActiveSupport::Concern
  include GeneratedInstanceMethods

  mixes_in_class_methods GeneratedClassMethods
  mixes_in_class_methods ::ActiveJob::QueuePriority::ClassMethods

  # source://activejob//lib/active_job/queue_priority.rb#53
  def priority; end

  module GeneratedClassMethods
    def priority; end
    def priority=(value); end
    def priority?; end
  end

  module GeneratedInstanceMethods; end
end

# source://activejob//lib/active_job/queue_priority.rb#8
module ActiveJob::QueuePriority::ClassMethods
  # source://activejob//lib/active_job/queue_priority.rb#9
  def default_priority; end

  # source://activejob//lib/active_job/queue_priority.rb#9
  def default_priority=(val); end

  # source://activejob//lib/active_job/queue_priority.rb#39
  def queue_with_priority(priority = T.unsafe(nil), &block); end

  class << self
    # source://activejob//lib/active_job/queue_priority.rb#9
    def default_priority; end

    # source://activejob//lib/active_job/queue_priority.rb#9
    def default_priority=(val); end
  end
end

# source://activejob//lib/active_job/railtie.rb#9
class ActiveJob::Railtie < ::Rails::Railtie; end

# source://activejob//lib/active_job/arguments.rb#26
class ActiveJob::SerializationError < ::ArgumentError; end

# source://activejob//lib/active_job/serializers.rb#8
module ActiveJob::Serializers
  extend ::ActiveSupport::Autoload

  class << self
    # source://activejob//lib/active_job/serializers.rb#60
    def add_serializers(*new_serializers); end

    # source://activejob//lib/active_job/serializers.rb#40
    def deserialize(argument); end

    # source://activejob//lib/active_job/serializers.rb#31
    def serialize(argument); end

    # source://activejob//lib/active_job/serializers.rb#51
    def serializers; end

    # source://activejob//lib/active_job/serializers.rb#53
    def serializers=(serializers); end

    private

    # source://activejob//lib/active_job/serializers.rb#66
    def add_new_serializers(new_serializers); end

    # source://activejob//lib/active_job/serializers.rb#80
    def index_serializers(new_serializers); end
  end
end

# source://activejob//lib/active_job/serializers/action_controller_parameters_serializer.rb#5
class ActiveJob::Serializers::ActionControllerParametersSerializer < ::ActiveJob::Serializers::ObjectSerializer
  # source://activejob//lib/active_job/serializers/action_controller_parameters_serializer.rb#10
  def deserialize(hash); end

  # source://activejob//lib/active_job/serializers/action_controller_parameters_serializer.rb#18
  def klass; end

  # source://activejob//lib/active_job/serializers/action_controller_parameters_serializer.rb#6
  def serialize(argument); end

  # source://activejob//lib/active_job/serializers/action_controller_parameters_serializer.rb#14
  def serialize?(argument); end
end

# source://activejob//lib/active_job/serializers/big_decimal_serializer.rb#7
class ActiveJob::Serializers::BigDecimalSerializer < ::ActiveJob::Serializers::ObjectSerializer
  # source://activejob//lib/active_job/serializers/big_decimal_serializer.rb#12
  def deserialize(hash); end

  # source://activejob//lib/active_job/serializers/big_decimal_serializer.rb#16
  def klass; end

  # source://activejob//lib/active_job/serializers/big_decimal_serializer.rb#8
  def serialize(big_decimal); end
end

# source://activejob//lib/active_job/serializers/date_serializer.rb#5
class ActiveJob::Serializers::DateSerializer < ::ActiveJob::Serializers::ObjectSerializer
  # source://activejob//lib/active_job/serializers/date_serializer.rb#10
  def deserialize(hash); end

  # source://activejob//lib/active_job/serializers/date_serializer.rb#14
  def klass; end

  # source://activejob//lib/active_job/serializers/date_serializer.rb#6
  def serialize(date); end
end

# source://activejob//lib/active_job/serializers/date_time_serializer.rb#5
class ActiveJob::Serializers::DateTimeSerializer < ::ActiveJob::Serializers::TimeObjectSerializer
  # source://activejob//lib/active_job/serializers/date_time_serializer.rb#6
  def deserialize(hash); end

  # source://activejob//lib/active_job/serializers/date_time_serializer.rb#10
  def klass; end
end

# source://activejob//lib/active_job/serializers/duration_serializer.rb#5
class ActiveJob::Serializers::DurationSerializer < ::ActiveJob::Serializers::ObjectSerializer
  # source://activejob//lib/active_job/serializers/duration_serializer.rb#12
  def deserialize(hash); end

  # source://activejob//lib/active_job/serializers/duration_serializer.rb#19
  def klass; end

  # source://activejob//lib/active_job/serializers/duration_serializer.rb#6
  def serialize(duration); end
end

# source://activejob//lib/active_job/serializers/module_serializer.rb#5
class ActiveJob::Serializers::ModuleSerializer < ::ActiveJob::Serializers::ObjectSerializer
  # source://activejob//lib/active_job/serializers/module_serializer.rb#11
  def deserialize(hash); end

  # source://activejob//lib/active_job/serializers/module_serializer.rb#15
  def klass; end

  # source://activejob//lib/active_job/serializers/module_serializer.rb#6
  def serialize(constant); end
end

# source://activejob//lib/active_job/serializers/object_serializer.rb#24
class ActiveJob::Serializers::ObjectSerializer
  include ::Singleton::SingletonInstanceMethods
  include ::Singleton
  extend ::Singleton::SingletonClassMethods

  # source://activejob//lib/active_job/serializers/object_serializer.rb#31
  def initialize; end

  # source://activejob//lib/active_job/serializers/object_serializer.rb#47
  def deserialize(hash); end

  # source://activejob//lib/active_job/serializers/object_serializer.rb#42
  def serialize(hash); end

  # source://activejob//lib/active_job/serializers/object_serializer.rb#37
  def serialize?(argument); end

  class << self
    # source://activejob//lib/active_job/serializers/object_serializer.rb#28
    def deserialize(*_arg0, **_arg1, &_arg2); end

    # source://activejob//lib/active_job/serializers/object_serializer.rb#28
    def serialize(*_arg0, **_arg1, &_arg2); end

    # source://activejob//lib/active_job/serializers/object_serializer.rb#28
    def serialize?(*_arg0, **_arg1, &_arg2); end

    private

    # source://activejob//lib/active_job/serializers/object_serializer.rb#25
    def allocate; end

    # source://activejob//lib/active_job/serializers/object_serializer.rb#25
    def new(*_arg0); end
  end
end

# source://activejob//lib/active_job/serializers/range_serializer.rb#5
class ActiveJob::Serializers::RangeSerializer < ::ActiveJob::Serializers::ObjectSerializer
  # source://activejob//lib/active_job/serializers/range_serializer.rb#14
  def deserialize(hash); end

  # source://activejob//lib/active_job/serializers/range_serializer.rb#18
  def klass; end

  # source://activejob//lib/active_job/serializers/range_serializer.rb#6
  def serialize(range); end
end

# source://activejob//lib/active_job/serializers/symbol_serializer.rb#5
class ActiveJob::Serializers::SymbolSerializer < ::ActiveJob::Serializers::ObjectSerializer
  # source://activejob//lib/active_job/serializers/symbol_serializer.rb#10
  def deserialize(argument); end

  # source://activejob//lib/active_job/serializers/symbol_serializer.rb#14
  def klass; end

  # source://activejob//lib/active_job/serializers/symbol_serializer.rb#6
  def serialize(argument); end
end

# source://activejob//lib/active_job/serializers/time_object_serializer.rb#5
class ActiveJob::Serializers::TimeObjectSerializer < ::ActiveJob::Serializers::ObjectSerializer
  # source://activejob//lib/active_job/serializers/time_object_serializer.rb#8
  def serialize(time); end
end

# source://activejob//lib/active_job/serializers/time_object_serializer.rb#6
ActiveJob::Serializers::TimeObjectSerializer::NANO_PRECISION = T.let(T.unsafe(nil), Integer)

# source://activejob//lib/active_job/serializers/time_serializer.rb#5
class ActiveJob::Serializers::TimeSerializer < ::ActiveJob::Serializers::TimeObjectSerializer
  # source://activejob//lib/active_job/serializers/time_serializer.rb#6
  def deserialize(hash); end

  # source://activejob//lib/active_job/serializers/time_serializer.rb#10
  def klass; end
end

# source://activejob//lib/active_job/serializers/time_with_zone_serializer.rb#5
class ActiveJob::Serializers::TimeWithZoneSerializer < ::ActiveJob::Serializers::ObjectSerializer
  # source://activejob//lib/active_job/serializers/time_with_zone_serializer.rb#15
  def deserialize(hash); end

  # source://activejob//lib/active_job/serializers/time_with_zone_serializer.rb#19
  def klass; end

  # source://activejob//lib/active_job/serializers/time_with_zone_serializer.rb#8
  def serialize(time_with_zone); end
end

# source://activejob//lib/active_job/serializers/time_with_zone_serializer.rb#6
ActiveJob::Serializers::TimeWithZoneSerializer::NANO_PRECISION = T.let(T.unsafe(nil), Integer)

# source://activejob//lib/active_job/structured_event_subscriber.rb#6
class ActiveJob::StructuredEventSubscriber < ::ActiveSupport::StructuredEventSubscriber
  # source://activejob//lib/active_job/structured_event_subscriber.rb#137
  def discard(event); end

  # source://activejob//lib/active_job/structured_event_subscriber.rb#7
  def enqueue(event); end

  # source://activejob//lib/active_job/structured_event_subscriber.rb#56
  def enqueue_all(event); end

  # source://activejob//lib/active_job/structured_event_subscriber.rb#31
  def enqueue_at(event); end

  # source://activejob//lib/active_job/structured_event_subscriber.rb#109
  def enqueue_retry(event); end

  # source://activejob//lib/active_job/structured_event_subscriber.rb#149
  def interrupt(event); end

  # source://activejob//lib/active_job/structured_event_subscriber.rb#87
  def perform(event); end

  # source://activejob//lib/active_job/structured_event_subscriber.rb#73
  def perform_start(event); end

  # source://activejob//lib/active_job/structured_event_subscriber.rb#162
  def resume(event); end

  # source://activejob//lib/active_job/structured_event_subscriber.rb#124
  def retry_stopped(event); end

  # source://activejob//lib/active_job/structured_event_subscriber.rb#197
  def step(event); end

  # source://activejob//lib/active_job/structured_event_subscriber.rb#173
  def step_skipped(event); end

  # source://activejob//lib/active_job/structured_event_subscriber.rb#184
  def step_started(event); end
end

# source://activejob//lib/active_job/test_case.rb#6
class ActiveJob::TestCase < ::ActiveSupport::TestCase
  include ::ActiveJob::TestHelper
end

# source://activejob//lib/active_job/test_helper.rb#8
module ActiveJob::TestHelper
  include ::ActiveSupport::Testing::Assertions

  # source://activejob//lib/active_job/test_helper.rb#56
  def after_teardown; end

  # source://activejob//lib/active_job/test_helper.rb#122
  def assert_enqueued_jobs(number, only: T.unsafe(nil), except: T.unsafe(nil), queue: T.unsafe(nil), &block); end

  # source://activejob//lib/active_job/test_helper.rb#406
  def assert_enqueued_with(job: T.unsafe(nil), args: T.unsafe(nil), at: T.unsafe(nil), queue: T.unsafe(nil), priority: T.unsafe(nil), &block); end

  # source://activejob//lib/active_job/test_helper.rb#186
  def assert_no_enqueued_jobs(only: T.unsafe(nil), except: T.unsafe(nil), queue: T.unsafe(nil), &block); end

  # source://activejob//lib/active_job/test_helper.rb#348
  def assert_no_performed_jobs(only: T.unsafe(nil), except: T.unsafe(nil), queue: T.unsafe(nil), &block); end

  # source://activejob//lib/active_job/test_helper.rb#278
  def assert_performed_jobs(number, only: T.unsafe(nil), except: T.unsafe(nil), queue: T.unsafe(nil), &block); end

  # source://activejob//lib/active_job/test_helper.rb#510
  def assert_performed_with(job: T.unsafe(nil), args: T.unsafe(nil), at: T.unsafe(nil), queue: T.unsafe(nil), priority: T.unsafe(nil), &block); end

  # source://activejob//lib/active_job/test_helper.rb#41
  def before_setup; end

  # source://activejob//lib/active_job/test_helper.rb#9
  def enqueued_jobs(*_arg0, **_arg1, &_arg2); end

  # source://activejob//lib/active_job/test_helper.rb#9
  def enqueued_jobs=(arg); end

  # source://activejob//lib/active_job/test_helper.rb#620
  def perform_enqueued_jobs(only: T.unsafe(nil), except: T.unsafe(nil), queue: T.unsafe(nil), at: T.unsafe(nil), &block); end

  # source://activejob//lib/active_job/test_helper.rb#9
  def performed_jobs(*_arg0, **_arg1, &_arg2); end

  # source://activejob//lib/active_job/test_helper.rb#9
  def performed_jobs=(arg); end

  # source://activejob//lib/active_job/test_helper.rb#661
  def queue_adapter; end

  # source://activejob//lib/active_job/test_helper.rb#66
  def queue_adapter_for_test; end

  private

  # source://activejob//lib/active_job/test_helper.rb#676
  def clear_enqueued_jobs; end

  # source://activejob//lib/active_job/test_helper.rb#680
  def clear_performed_jobs; end

  # source://activejob//lib/active_job/test_helper.rb#745
  def deserialize_args_for_assertion(job); end

  # source://activejob//lib/active_job/test_helper.rb#716
  def enqueued_jobs_with(only: T.unsafe(nil), except: T.unsafe(nil), queue: T.unsafe(nil), at: T.unsafe(nil), &block); end

  # source://activejob//lib/active_job/test_helper.rb#710
  def filter_as_proc(filter); end

  # source://activejob//lib/active_job/test_helper.rb#724
  def flush_enqueued_jobs(only: T.unsafe(nil), except: T.unsafe(nil), queue: T.unsafe(nil), at: T.unsafe(nil)); end

  # source://activejob//lib/active_job/test_helper.rb#752
  def instantiate_job(payload, skip_deserialize_arguments: T.unsafe(nil)); end

  # source://activejob//lib/active_job/test_helper.rb#684
  def jobs_with(jobs, only: T.unsafe(nil), except: T.unsafe(nil), queue: T.unsafe(nil), at: T.unsafe(nil)); end

  # source://activejob//lib/active_job/test_helper.rb#720
  def performed_jobs_with(only: T.unsafe(nil), except: T.unsafe(nil), queue: T.unsafe(nil), &block); end

  # source://activejob//lib/active_job/test_helper.rb#732
  def prepare_args_for_assertion(args); end

  # source://activejob//lib/active_job/test_helper.rb#759
  def queue_adapter_changed_jobs; end

  # source://activejob//lib/active_job/test_helper.rb#666
  def require_active_job_test_adapter!(method); end

  # source://activejob//lib/active_job/test_helper.rb#672
  def using_test_adapter?; end

  # source://activejob//lib/active_job/test_helper.rb#766
  def validate_option(only: T.unsafe(nil), except: T.unsafe(nil)); end
end

# source://activejob//lib/active_job/test_helper.rb#15
module ActiveJob::TestHelper::TestQueueAdapter
  extend ::ActiveSupport::Concern
  include GeneratedInstanceMethods

  mixes_in_class_methods GeneratedClassMethods
  mixes_in_class_methods ::ActiveJob::TestHelper::TestQueueAdapter::ClassMethods

  module GeneratedClassMethods
    def _test_adapter; end
    def _test_adapter=(value); end
  end

  module GeneratedInstanceMethods; end
end

# source://activejob//lib/active_job/test_helper.rb#22
module ActiveJob::TestHelper::TestQueueAdapter::ClassMethods
  # source://activejob//lib/active_job/test_helper.rb#27
  def disable_test_adapter; end

  # source://activejob//lib/active_job/test_helper.rb#31
  def enable_test_adapter(test_adapter); end

  # source://activejob//lib/active_job/test_helper.rb#23
  def queue_adapter; end
end

# source://activejob//lib/active_job/core.rb#5
class ActiveJob::UnknownJobClassError < ::NameError
  # source://activejob//lib/active_job/core.rb#6
  def initialize(job_class_name); end
end

# source://activejob//lib/active_job/gem_version.rb#9
module ActiveJob::VERSION; end

# source://activejob//lib/active_job/gem_version.rb#10
ActiveJob::VERSION::MAJOR = T.let(T.unsafe(nil), Integer)

# source://activejob//lib/active_job/gem_version.rb#11
ActiveJob::VERSION::MINOR = T.let(T.unsafe(nil), Integer)

# source://activejob//lib/active_job/gem_version.rb#13
ActiveJob::VERSION::PRE = T.let(T.unsafe(nil), T.untyped)

# source://activejob//lib/active_job/gem_version.rb#15
ActiveJob::VERSION::STRING = T.let(T.unsafe(nil), String)

# source://activejob//lib/active_job/gem_version.rb#12
ActiveJob::VERSION::TINY = T.let(T.unsafe(nil), Integer)
