# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `brakeman` gem.
# Please instead update this file by running `bin/tapioca gem brakeman`.


# source://brakeman//lib/brakeman/version.rb#1
module Brakeman
  class << self
    # source://brakeman//lib/brakeman.rb#594
    def add_external_checks(options); end

    # source://brakeman//lib/brakeman.rb#600
    def check_for_missing_checks(included_checks, excluded_checks, enabled_checks); end

    # source://brakeman//lib/brakeman.rb#505
    def compare(options); end

    # source://brakeman//lib/brakeman.rb#193
    def config_file(custom_location, app_path); end

    # source://brakeman//lib/brakeman.rb#500
    def debug(message); end

    # source://brakeman//lib/brakeman.rb#610
    def debug=(val); end

    # source://brakeman//lib/brakeman.rb#200
    def default_options; end

    # source://brakeman//lib/brakeman.rb#360
    def dump_config(options); end

    # source://brakeman//lib/brakeman.rb#386
    def ensure_latest; end

    # source://brakeman//lib/brakeman.rb#566
    def filter_warnings(tracker, options); end

    # source://brakeman//lib/brakeman.rb#232
    def get_output_formats(options); end

    # source://brakeman//lib/brakeman.rb#556
    def ignore_file_entries_with_empty_notes(file); end

    # source://brakeman//lib/brakeman.rb#338
    def list_checks(options); end

    # source://brakeman//lib/brakeman.rb#528
    def load_brakeman_dependency(name, allow_fail = T.unsafe(nil)); end

    # source://brakeman//lib/brakeman.rb#145
    def load_options(line_options); end

    # source://brakeman//lib/brakeman.rb#496
    def notify(message); end

    # source://brakeman//lib/brakeman.rb#614
    def quiet=(val); end

    # source://brakeman//lib/brakeman.rb#485
    def rescan(tracker, files, options = T.unsafe(nil)); end

    # source://brakeman//lib/brakeman.rb#81
    def run(options); end

    # source://brakeman//lib/brakeman.rb#395
    def scan(options); end

    # source://brakeman//lib/brakeman.rb#104
    def set_options(options); end

    private

    # source://brakeman//lib/brakeman.rb#285
    def get_formats_from_output_files(output_files); end

    # source://brakeman//lib/brakeman.rb#251
    def get_formats_from_output_format(output_format); end

    # source://brakeman//lib/brakeman.rb#321
    def get_github_url(options); end

    # source://brakeman//lib/brakeman.rb#439
    def write_report_to_files(tracker, output_files); end

    # source://brakeman//lib/brakeman.rb#457
    def write_report_to_formats(tracker, output_formats); end
  end
end

# source://brakeman//lib/brakeman.rb#181
Brakeman::CONFIG_FILES = T.let(T.unsafe(nil), Array)

# source://brakeman//lib/brakeman.rb#618
class Brakeman::DependencyError < ::RuntimeError; end

# source://brakeman//lib/brakeman.rb#25
Brakeman::Empty_Ignore_Note_Exit_Code = T.let(T.unsafe(nil), Integer)

# source://brakeman//lib/brakeman.rb#21
Brakeman::Errors_Found_Exit_Code = T.let(T.unsafe(nil), Integer)

# source://brakeman//lib/brakeman.rb#621
class Brakeman::MissingChecksError < ::RuntimeError; end

# source://brakeman//lib/brakeman.rb#17
Brakeman::Missing_Checks_Exit_Code = T.let(T.unsafe(nil), Integer)

# source://brakeman//lib/brakeman.rb#620
class Brakeman::NoApplication < ::RuntimeError; end

# source://brakeman//lib/brakeman.rb#619
class Brakeman::NoBrakemanError < ::RuntimeError; end

# source://brakeman//lib/brakeman.rb#11
Brakeman::No_App_Found_Exit_Code = T.let(T.unsafe(nil), Integer)

# source://brakeman//lib/brakeman.rb#14
Brakeman::Not_Latest_Version_Exit_Code = T.let(T.unsafe(nil), Integer)

# source://brakeman//lib/brakeman.rb#29
Brakeman::Obsolete_Ignore_Entries_Exit_Code = T.let(T.unsafe(nil), Integer)

# source://brakeman//lib/brakeman/version.rb#2
Brakeman::Version = T.let(T.unsafe(nil), String)

# source://brakeman//lib/brakeman.rb#8
Brakeman::Warnings_Found_Exit_Code = T.let(T.unsafe(nil), Integer)
