# typed: false

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `drb` gem.
# Please instead update this file by running `bin/tapioca gem drb`.


# source://drb//lib/drb/eq.rb#2
module DRb
  private

  # source://drb//lib/drb/drb.rb#1882
  def config; end

  # source://drb//lib/drb/drb.rb#1839
  def current_server; end

  # source://drb//lib/drb/drb.rb#1984
  def fetch_server(uri); end

  # source://drb//lib/drb/drb.rb#1893
  def front; end

  # source://drb//lib/drb/drb.rb#1872
  def here?(uri); end

  # source://drb//lib/drb/drb.rb#1938
  def install_acl(acl); end

  # source://drb//lib/drb/drb.rb#1930
  def install_id_conv(idconv); end

  # source://drb//lib/drb/drb.rb#1944
  def mutex; end

  # source://drb//lib/drb/drb.rb#1826
  def primary_server; end

  # source://drb//lib/drb/drb.rb#1826
  def primary_server=(_arg0); end

  # source://drb//lib/drb/drb.rb#1962
  def regist_server(server); end

  # source://drb//lib/drb/drb.rb#1971
  def remove_server(server); end

  # source://drb//lib/drb/drb.rb#1818
  def start_service(uri = T.unsafe(nil), front = T.unsafe(nil), config = T.unsafe(nil)); end

  # source://drb//lib/drb/drb.rb#1851
  def stop_service; end

  # source://drb//lib/drb/drb.rb#1919
  def thread; end

  # source://drb//lib/drb/drb.rb#1910
  def to_id(obj); end

  # source://drb//lib/drb/drb.rb#1902
  def to_obj(ref); end

  # source://drb//lib/drb/drb.rb#1860
  def uri; end

  class << self
    # source://drb//lib/drb/drb.rb#1887
    def config; end

    # source://drb//lib/drb/drb.rb#1845
    def current_server; end

    # source://drb//lib/drb/drb.rb#1987
    def fetch_server(uri); end

    # source://drb//lib/drb/drb.rb#1896
    def front; end

    # source://drb//lib/drb/drb.rb#1876
    def here?(uri); end

    # source://drb//lib/drb/drb.rb#1941
    def install_acl(acl); end

    # source://drb//lib/drb/drb.rb#1933
    def install_id_conv(idconv); end

    # source://drb//lib/drb/drb.rb#1947
    def mutex; end

    # source://drb//lib/drb/drb.rb#1827
    def primary_server; end

    # source://drb//lib/drb/drb.rb#1827
    def primary_server=(_arg0); end

    # source://drb//lib/drb/drb.rb#1968
    def regist_server(server); end

    # source://drb//lib/drb/drb.rb#1979
    def remove_server(server); end

    # source://drb//lib/drb/drb.rb#1821
    def start_service(uri = T.unsafe(nil), front = T.unsafe(nil), config = T.unsafe(nil)); end

    # source://drb//lib/drb/drb.rb#1855
    def stop_service; end

    # source://drb//lib/drb/drb.rb#1922
    def thread; end

    # source://drb//lib/drb/drb.rb#1913
    def to_id(obj); end

    # source://drb//lib/drb/drb.rb#1914
    def to_obj(ref); end

    # source://drb//lib/drb/drb.rb#1869
    def uri; end
  end
end

# source://drb//lib/drb/drb.rb#382
DRb::DRB_OBJECT_SPACE = T.let(T.unsafe(nil), DRb::DRbObjectSpace)

# source://drb//lib/drb/drb.rb#546
class DRb::DRbArray
  # source://drb//lib/drb/drb.rb#551
  def initialize(ary); end

  # source://drb//lib/drb/drb.rb#570
  def _dump(lv); end

  class << self
    # source://drb//lib/drb/drb.rb#566
    def _load(s); end
  end
end

# source://drb//lib/drb/drb.rb#1284
class DRb::DRbConn
  # source://drb//lib/drb/drb.rb#1345
  def initialize(remote_uri); end

  # source://drb//lib/drb/drb.rb#1361
  def alive?; end

  # source://drb//lib/drb/drb.rb#1356
  def close; end

  # source://drb//lib/drb/drb.rb#1351
  def send_message(ref, msg_id, arg, block); end

  # source://drb//lib/drb/drb.rb#1349
  def uri; end

  class << self
    # source://drb//lib/drb/drb.rb#1287
    def make_pool; end

    # source://drb//lib/drb/drb.rb#1325
    def open(remote_uri); end

    # source://drb//lib/drb/drb.rb#1320
    def stop_pool; end
  end
end

# source://drb//lib/drb/drb.rb#393
class DRb::DRbIdConv
  # source://drb//lib/drb/drb.rb#407
  def to_id(obj); end

  # source://drb//lib/drb/drb.rb#399
  def to_obj(ref); end
end

# source://drb//lib/drb/drb.rb#584
class DRb::DRbMessage
  # source://drb//lib/drb/drb.rb#585
  def initialize(config); end

  # source://drb//lib/drb/drb.rb#590
  def dump(obj, error = T.unsafe(nil)); end

  # source://drb//lib/drb/drb.rb#607
  def load(soc); end

  # source://drb//lib/drb/drb.rb#667
  def recv_reply(stream); end

  # source://drb//lib/drb/drb.rb#647
  def recv_request(stream); end

  # source://drb//lib/drb/drb.rb#661
  def send_reply(stream, succ, result); end

  # source://drb//lib/drb/drb.rb#633
  def send_request(stream, ref, msg_id, arg, b); end

  private

  # source://drb//lib/drb/drb.rb#674
  def make_proxy(obj, error = T.unsafe(nil)); end
end

# source://drb//lib/drb/eq.rb#3
class DRb::DRbObject
  # source://drb//lib/drb/drb.rb#1117
  def initialize(obj, uri = T.unsafe(nil)); end

  # source://drb//lib/drb/eq.rb#4
  def ==(other); end

  # source://drb//lib/drb/drb.rb#1143
  def __drbref; end

  # source://drb//lib/drb/drb.rb#1138
  def __drburi; end

  # source://drb//lib/drb/drb.rb#1108
  def _dump(lv); end

  # source://drb//lib/drb/eq.rb#13
  def eql?(other); end

  # source://drb//lib/drb/eq.rb#9
  def hash; end

  # source://drb//lib/drb/drb.rb#1163
  def method_missing(msg_id, *a, **_arg2, &b); end

  # source://drb//lib/drb/drb.rb#1215
  def pretty_print(q); end

  # source://drb//lib/drb/drb.rb#1219
  def pretty_print_cycle(q); end

  # source://drb//lib/drb/drb.rb#1151
  def respond_to?(msg_id, priv = T.unsafe(nil)); end

  class << self
    # source://drb//lib/drb/drb.rb#1079
    def _load(s); end

    # source://drb//lib/drb/drb.rb#1093
    def new_with(uri, ref); end

    # source://drb//lib/drb/drb.rb#1101
    def new_with_uri(uri); end

    # source://drb//lib/drb/drb.rb#1201
    def prepare_backtrace(uri, result); end

    # source://drb//lib/drb/drb.rb#1188
    def with_friend(uri); end
  end
end

# source://drb//lib/drb/drb.rb#351
class DRb::DRbObjectSpace
  include ::MonitorMixin

  # source://drb//lib/drb/drb.rb#357
  def initialize; end

  # source://drb//lib/drb/drb.rb#362
  def to_id(obj); end

  # source://drb//lib/drb/drb.rb#369
  def to_obj(ref); end
end

# source://drb//lib/drb/drb.rb#749
module DRb::DRbProtocol
  private

  # source://drb//lib/drb/drb.rb#752
  def add_protocol(prot); end

  # source://drb//lib/drb/drb.rb#830
  def auto_load(uri); end

  # source://drb//lib/drb/drb.rb#764
  def open(uri, config, first = T.unsafe(nil)); end

  # source://drb//lib/drb/drb.rb#792
  def open_server(uri, config, first = T.unsafe(nil)); end

  # source://drb//lib/drb/drb.rb#813
  def uri_option(uri, config, first = T.unsafe(nil)); end

  class << self
    # source://drb//lib/drb/drb.rb#755
    def add_protocol(prot); end

    # source://drb//lib/drb/drb.rb#835
    def auto_load(uri); end

    # source://drb//lib/drb/drb.rb#781
    def open(uri, config, first = T.unsafe(nil)); end

    # source://drb//lib/drb/drb.rb#805
    def open_server(uri, config, first = T.unsafe(nil)); end

    # source://drb//lib/drb/drb.rb#828
    def uri_option(uri, config, first = T.unsafe(nil)); end
  end
end

# source://drb//lib/drb/drb.rb#459
class DRb::DRbRemoteError < ::DRb::DRbError
  # source://drb//lib/drb/drb.rb#462
  def initialize(error); end

  # source://drb//lib/drb/drb.rb#469
  def reason; end
end

# source://drb//lib/drb/drb.rb#1378
class DRb::DRbServer
  # source://drb//lib/drb/drb.rb#1479
  def initialize(uri = T.unsafe(nil), front = T.unsafe(nil), config_or_acl = T.unsafe(nil)); end

  # source://drb//lib/drb/drb.rb#1534
  def alive?; end

  # source://drb//lib/drb/drb.rb#1622
  def check_insecure_method(obj, msg_id); end

  # source://drb//lib/drb/drb.rb#1521
  def config; end

  # source://drb//lib/drb/drb.rb#1518
  def front; end

  # source://drb//lib/drb/drb.rb#1539
  def here?(uri); end

  # source://drb//lib/drb/drb.rb#1544
  def stop_service; end

  # source://drb//lib/drb/drb.rb#1512
  def thread; end

  # source://drb//lib/drb/drb.rb#1561
  def to_id(obj); end

  # source://drb//lib/drb/drb.rb#1554
  def to_obj(ref); end

  # source://drb//lib/drb/drb.rb#1505
  def uri; end

  # source://drb//lib/drb/drb.rb#1531
  def verbose; end

  # source://drb//lib/drb/drb.rb#1526
  def verbose=(v); end

  private

  # source://drb//lib/drb/drb.rb#1608
  def any_to_s(obj); end

  # source://drb//lib/drb/drb.rb#1746
  def error_print(exception); end

  # source://drb//lib/drb/drb.rb#1602
  def insecure_method?(msg_id); end

  # source://drb//lib/drb/drb.rb#1764
  def main_loop; end

  # source://drb//lib/drb/drb.rb#1583
  def run; end

  # source://drb//lib/drb/drb.rb#1568
  def shutdown; end

  class << self
    # source://drb//lib/drb/drb.rb#1403
    def default_acl(acl); end

    # source://drb//lib/drb/drb.rb#1389
    def default_argc_limit(argc); end

    # source://drb//lib/drb/drb.rb#1410
    def default_id_conv(idconv); end

    # source://drb//lib/drb/drb.rb#1396
    def default_load_limit(sz); end

    # source://drb//lib/drb/drb.rb#1426
    def make_config(hash = T.unsafe(nil)); end

    # source://drb//lib/drb/drb.rb#1422
    def verbose; end

    # source://drb//lib/drb/drb.rb#1417
    def verbose=(on); end
  end
end

# source://drb//lib/drb/drb.rb#1652
class DRb::DRbServer::InvokeMethod
  # source://drb//lib/drb/drb.rb#1653
  def initialize(drb_server, client); end

  # source://drb//lib/drb/drb.rb#1658
  def perform; end

  private

  # source://drb//lib/drb/drb.rb#1704
  def block_yield(x); end

  # source://drb//lib/drb/drb.rb#1695
  def check_insecure_method; end

  # source://drb//lib/drb/drb.rb#1687
  def init_with_client; end

  # source://drb//lib/drb/drb.rb#1711
  def perform_with_block; end

  # source://drb//lib/drb/drb.rb#1731
  def perform_without_block; end

  # source://drb//lib/drb/drb.rb#1699
  def setup_message; end
end

# source://drb//lib/drb/drb.rb#843
class DRb::DRbTCPSocket
  # source://drb//lib/drb/drb.rb#931
  def initialize(uri, soc, config = T.unsafe(nil)); end

  # source://drb//lib/drb/drb.rb#999
  def accept; end

  # source://drb//lib/drb/drb.rb#1029
  def alive?; end

  # source://drb//lib/drb/drb.rb#981
  def close; end

  # source://drb//lib/drb/drb.rb#946
  def peeraddr; end

  # source://drb//lib/drb/drb.rb#969
  def recv_reply; end

  # source://drb//lib/drb/drb.rb#959
  def recv_request; end

  # source://drb//lib/drb/drb.rb#964
  def send_reply(succ, result); end

  # source://drb//lib/drb/drb.rb#954
  def send_request(ref, msg_id, arg, b); end

  # source://drb//lib/drb/drb.rb#1038
  def set_sockopt(soc); end

  # source://drb//lib/drb/drb.rb#1024
  def shutdown; end

  # source://drb//lib/drb/drb.rb#951
  def stream; end

  # source://drb//lib/drb/drb.rb#942
  def uri; end

  private

  # source://drb//lib/drb/drb.rb#1014
  def accept_or_shutdown; end

  # source://drb//lib/drb/drb.rb#990
  def close_shutdown_pipe; end

  class << self
    # source://drb//lib/drb/drb.rb#873
    def getservername; end

    # source://drb//lib/drb/drb.rb#866
    def open(uri, config); end

    # source://drb//lib/drb/drb.rb#904
    def open_server(uri, config); end

    # source://drb//lib/drb/drb.rb#889
    def open_server_inaddr_any(host, port); end

    # source://drb//lib/drb/drb.rb#846
    def parse_uri(uri); end

    # source://drb//lib/drb/drb.rb#921
    def uri_option(uri, config); end
  end
end

# source://drb//lib/drb/unix.rb#15
class DRb::DRbUNIXSocket < ::DRb::DRbTCPSocket
  # source://drb//lib/drb/unix.rb#62
  def initialize(uri, soc, config = T.unsafe(nil), server_mode = T.unsafe(nil)); end

  # source://drb//lib/drb/unix.rb#105
  def accept; end

  # source://drb//lib/drb/unix.rb#95
  def close; end

  # source://drb//lib/drb/unix.rb#111
  def set_sockopt(soc); end

  class << self
    # source://drb//lib/drb/unix.rb#28
    def open(uri, config); end

    # source://drb//lib/drb/unix.rb#34
    def open_server(uri, config); end

    # source://drb//lib/drb/unix.rb#17
    def parse_uri(uri); end

    # source://drb//lib/drb/unix.rb#72
    def temp_server; end

    # source://drb//lib/drb/unix.rb#57
    def uri_option(uri, config); end
  end
end

# source://drb//lib/drb/unix.rb#70
DRb::DRbUNIXSocket::Max_try = T.let(T.unsafe(nil), Integer)

# source://drb//lib/drb/drb.rb#1049
class DRb::DRbURIOption
  # source://drb//lib/drb/drb.rb#1050
  def initialize(option); end

  # source://drb//lib/drb/drb.rb#1056
  def ==(other); end

  # source://drb//lib/drb/drb.rb#1065
  def eql?(other); end

  # source://drb//lib/drb/drb.rb#1061
  def hash; end

  # source://drb//lib/drb/drb.rb#1053
  def option; end

  # source://drb//lib/drb/drb.rb#1054
  def to_s; end
end

# source://drb//lib/drb/drb.rb#418
module DRb::DRbUndumped
  # source://drb//lib/drb/drb.rb#419
  def _dump(dummy); end
end

# source://drb//lib/drb/drb.rb#485
class DRb::DRbUnknown
  # source://drb//lib/drb/drb.rb#493
  def initialize(err, buf); end

  # source://drb//lib/drb/drb.rb#522
  def _dump(lv); end

  # source://drb//lib/drb/drb.rb#512
  def buf; end

  # source://drb//lib/drb/drb.rb#536
  def exception; end

  # source://drb//lib/drb/drb.rb#509
  def name; end

  # source://drb//lib/drb/drb.rb#531
  def reload; end

  class << self
    # source://drb//lib/drb/drb.rb#514
    def _load(s); end
  end
end

# source://drb//lib/drb/drb.rb#438
class DRb::DRbUnknownError < ::DRb::DRbError
  # source://drb//lib/drb/drb.rb#441
  def initialize(unknown); end

  # source://drb//lib/drb/drb.rb#453
  def _dump(lv); end

  # source://drb//lib/drb/drb.rb#447
  def unknown; end

  class << self
    # source://drb//lib/drb/drb.rb#449
    def _load(s); end
  end
end

# source://drb//lib/drb/drb.rb#1227
class DRb::ThreadObject
  include ::MonitorMixin

  # source://drb//lib/drb/drb.rb#1230
  def initialize(&blk); end

  # source://drb//lib/drb/drb.rb#1265
  def _execute; end

  # source://drb//lib/drb/drb.rb#1241
  def alive?; end

  # source://drb//lib/drb/drb.rb#1245
  def kill; end

  # source://drb//lib/drb/drb.rb#1250
  def method_missing(msg, *arg, &blk); end
end

# source://drb//lib/drb/version.rb#2
DRb::VERSION = T.let(T.unsafe(nil), String)

# source://drb//lib/drb/drb.rb#1993
DRbIdConv = DRb::DRbIdConv

# source://drb//lib/drb/drb.rb#1991
DRbObject = DRb::DRbObject

# source://drb//lib/drb/drb.rb#1992
DRbUndumped = DRb::DRbUndumped
