# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `image_processing` gem.
# Please instead update this file by running `bin/tapioca gem image_processing`.


# source://image_processing//lib/image_processing/chainable.rb#1
module ImageProcessing; end

# source://image_processing//lib/image_processing/builder.rb#2
class ImageProcessing::Builder
  include ::ImageProcessing::Chainable

  # source://image_processing//lib/image_processing/builder.rb#7
  def initialize(options); end

  # source://image_processing//lib/image_processing/builder.rb#12
  def call!(**call_options); end

  # source://image_processing//lib/image_processing/builder.rb#5
  def options; end

  private

  # source://image_processing//lib/image_processing/builder.rb#20
  def instrument; end

  # source://image_processing//lib/image_processing/builder.rb#28
  def pipeline_options; end
end

# source://image_processing//lib/image_processing/chainable.rb#3
module ImageProcessing::Chainable
  # source://image_processing//lib/image_processing/chainable.rb#34
  def apply(operations); end

  # source://image_processing//lib/image_processing/chainable.rb#64
  def branch(**new_options); end

  # source://image_processing//lib/image_processing/chainable.rb#55
  def call(file = T.unsafe(nil), destination: T.unsafe(nil), **call_options); end

  # source://image_processing//lib/image_processing/chainable.rb#10
  def convert(format); end

  # source://image_processing//lib/image_processing/chainable.rb#25
  def instrumenter(&block); end

  # source://image_processing//lib/image_processing/chainable.rb#15
  def loader(**options); end

  # source://image_processing//lib/image_processing/chainable.rb#49
  def operation(name, *args, &block); end

  # source://image_processing//lib/image_processing/chainable.rb#20
  def saver(**options); end

  # source://image_processing//lib/image_processing/chainable.rb#5
  def source(file); end

  private

  # source://image_processing//lib/image_processing/chainable.rb#86
  def method_missing(name, *args, **_arg2, &block); end
end

# source://image_processing//lib/image_processing/chainable.rb#95
ImageProcessing::Chainable::DEFAULT_OPTIONS = T.let(T.unsafe(nil), Hash)

# source://image_processing//lib/image_processing.rb#8
class ImageProcessing::Error < ::StandardError; end

# source://image_processing//lib/image_processing/mini_magick.rb#5
module ImageProcessing::MiniMagick
  extend ::ImageProcessing::Chainable

  class << self
    # source://image_processing//lib/image_processing/mini_magick.rb#8
    def convert_shim(&block); end

    # source://image_processing//lib/image_processing/mini_magick.rb#17
    def valid_image?(file); end
  end
end

# source://image_processing//lib/image_processing/mini_magick.rb#27
class ImageProcessing::MiniMagick::Processor < ::ImageProcessing::Processor
  # source://image_processing//lib/image_processing/mini_magick.rb#167
  def append(*args); end

  # source://image_processing//lib/image_processing/mini_magick.rb#123
  def composite(overlay = T.unsafe(nil), mask: T.unsafe(nil), mode: T.unsafe(nil), gravity: T.unsafe(nil), offset: T.unsafe(nil), args: T.unsafe(nil), **options, &block); end

  # source://image_processing//lib/image_processing/mini_magick.rb#104
  def crop(*args); end

  # source://image_processing//lib/image_processing/mini_magick.rb#155
  def define(options); end

  # source://image_processing//lib/image_processing/mini_magick.rb#161
  def limits(options); end

  # source://image_processing//lib/image_processing/mini_magick.rb#90
  def resize_and_pad(width, height, background: T.unsafe(nil), gravity: T.unsafe(nil), **options); end

  # source://image_processing//lib/image_processing/mini_magick.rb#99
  def resize_to_cover(width, height, **options); end

  # source://image_processing//lib/image_processing/mini_magick.rb#81
  def resize_to_fill(width, height, gravity: T.unsafe(nil), **options); end

  # source://image_processing//lib/image_processing/mini_magick.rb#75
  def resize_to_fit(width, height, **options); end

  # source://image_processing//lib/image_processing/mini_magick.rb#70
  def resize_to_limit(width, height, **options); end

  # source://image_processing//lib/image_processing/mini_magick.rb#115
  def rotate(degrees, background: T.unsafe(nil)); end

  protected

  # source://image_processing//lib/image_processing/mini_magick.rb#28
  def magick; end

  private

  # source://image_processing//lib/image_processing/mini_magick.rb#180
  def color(value); end

  # source://image_processing//lib/image_processing/mini_magick.rb#203
  def convert_to_path(file, name); end

  # source://image_processing//lib/image_processing/mini_magick.rb#191
  def thumbnail(geometry, sharpen: T.unsafe(nil)); end

  class << self
    # source://image_processing//lib/image_processing/mini_magick.rb#36
    def load_image(path_or_magick, loader: T.unsafe(nil), page: T.unsafe(nil), geometry: T.unsafe(nil), auto_orient: T.unsafe(nil), **options); end

    # source://image_processing//lib/image_processing/mini_magick.rb#60
    def save_image(magick, destination_path, allow_splitting: T.unsafe(nil), **options); end
  end
end

# source://image_processing//lib/image_processing/processor.rb#34
ImageProcessing::MiniMagick::Processor::ACCUMULATOR_CLASS = MiniMagick::Tool

# source://image_processing//lib/image_processing/mini_magick.rb#31
ImageProcessing::MiniMagick::Processor::SHARPEN_PARAMETERS = T.let(T.unsafe(nil), Hash)

# source://image_processing//lib/image_processing/mini_magick.rb#215
module ImageProcessing::MiniMagick::Processor::Utils
  private

  # source://image_processing//lib/image_processing/mini_magick.rb#244
  def apply_define(magick, options); end

  # source://image_processing//lib/image_processing/mini_magick.rb#231
  def apply_options(magick, define: T.unsafe(nil), **options); end

  # source://image_processing//lib/image_processing/mini_magick.rb#221
  def disallow_split_layers!(destination_path); end

  class << self
    # source://image_processing//lib/image_processing/mini_magick.rb#244
    def apply_define(magick, options); end

    # source://image_processing//lib/image_processing/mini_magick.rb#231
    def apply_options(magick, define: T.unsafe(nil), **options); end

    # source://image_processing//lib/image_processing/mini_magick.rb#221
    def disallow_split_layers!(destination_path); end
  end
end

# source://image_processing//lib/image_processing/pipeline.rb#4
class ImageProcessing::Pipeline
  # source://image_processing//lib/image_processing/pipeline.rb#10
  def initialize(options); end

  # source://image_processing//lib/image_processing/pipeline.rb#19
  def call(save: T.unsafe(nil)); end

  # source://image_processing//lib/image_processing/pipeline.rb#7
  def destination; end

  # source://image_processing//lib/image_processing/pipeline.rb#39
  def destination_format; end

  # source://image_processing//lib/image_processing/pipeline.rb#7
  def format; end

  # source://image_processing//lib/image_processing/pipeline.rb#7
  def loader; end

  # source://image_processing//lib/image_processing/pipeline.rb#7
  def operations; end

  # source://image_processing//lib/image_processing/pipeline.rb#7
  def processor; end

  # source://image_processing//lib/image_processing/pipeline.rb#7
  def saver; end

  # source://image_processing//lib/image_processing/pipeline.rb#34
  def source_path; end

  private

  # source://image_processing//lib/image_processing/pipeline.rb#49
  def call_processor(**options); end

  # source://image_processing//lib/image_processing/pipeline.rb#61
  def create_tempfile; end

  # source://image_processing//lib/image_processing/pipeline.rb#97
  def determine_format(file_path); end

  # source://image_processing//lib/image_processing/pipeline.rb#76
  def handle_destination; end

  # source://image_processing//lib/image_processing/pipeline.rb#85
  def source; end
end

# source://image_processing//lib/image_processing/pipeline.rb#5
ImageProcessing::Pipeline::DEFAULT_FORMAT = T.let(T.unsafe(nil), String)

# source://image_processing//lib/image_processing/processor.rb#3
class ImageProcessing::Processor
  # source://image_processing//lib/image_processing/processor.rb#47
  def initialize(accumulator = T.unsafe(nil)); end

  # source://image_processing//lib/image_processing/processor.rb#55
  def apply_operation(name, *args, &block); end

  # source://image_processing//lib/image_processing/processor.rb#68
  def custom(&block); end

  class << self
    # source://image_processing//lib/image_processing/processor.rb#31
    def accumulator(name, klass); end

    # source://image_processing//lib/image_processing/processor.rb#38
    def apply_operation(accumulator, _arg1); end

    # source://image_processing//lib/image_processing/processor.rb#4
    def call(source:, loader:, operations:, saver:, destination: T.unsafe(nil)); end

    # source://image_processing//lib/image_processing/processor.rb#43
    def supports_resize_on_load?; end
  end
end

# source://image_processing//lib/image_processing/version.rb#2
ImageProcessing::VERSION = T.let(T.unsafe(nil), String)

# source://image_processing//lib/image_processing/vips.rb#7
module ImageProcessing::Vips
  extend ::ImageProcessing::Chainable

  class << self
    # source://image_processing//lib/image_processing/vips.rb#11
    def valid_image?(file); end
  end
end

# source://image_processing//lib/image_processing/vips.rb#18
class ImageProcessing::Vips::Processor < ::ImageProcessing::Processor
  # source://image_processing//lib/image_processing/vips.rb#122
  def composite(overlay, _mode = T.unsafe(nil), mode: T.unsafe(nil), gravity: T.unsafe(nil), offset: T.unsafe(nil), **options); end

  # source://image_processing//lib/image_processing/vips.rb#152
  def remove(*args); end

  # source://image_processing//lib/image_processing/vips.rb#87
  def resize_and_pad(width, height, gravity: T.unsafe(nil), extend: T.unsafe(nil), background: T.unsafe(nil), alpha: T.unsafe(nil), **options); end

  # source://image_processing//lib/image_processing/vips.rb#95
  def resize_to_cover(width, height, **options); end

  # source://image_processing//lib/image_processing/vips.rb#81
  def resize_to_fill(width, height, **options); end

  # source://image_processing//lib/image_processing/vips.rb#74
  def resize_to_fit(width, height, **options); end

  # source://image_processing//lib/image_processing/vips.rb#68
  def resize_to_limit(width, height, **options); end

  # source://image_processing//lib/image_processing/vips.rb#111
  def rotate(degrees, **options); end

  # source://image_processing//lib/image_processing/vips.rb#149
  def set(*args); end

  # source://image_processing//lib/image_processing/vips.rb#150
  def set_type(*args); end

  # source://image_processing//lib/image_processing/vips.rb#151
  def set_value(*args); end

  protected

  # source://image_processing//lib/image_processing/vips.rb#19
  def image; end

  private

  # source://image_processing//lib/image_processing/vips.rb#182
  def convert_to_image(object, name); end

  # source://image_processing//lib/image_processing/vips.rb#175
  def default_dimensions(width, height); end

  # source://image_processing//lib/image_processing/vips.rb#158
  def thumbnail(width, height, sharpen: T.unsafe(nil), **options); end

  class << self
    # source://image_processing//lib/image_processing/vips.rb#30
    def load_image(path_or_image, loader: T.unsafe(nil), autorot: T.unsafe(nil), **options); end

    # source://image_processing//lib/image_processing/vips.rb#56
    def save_image(image, path, saver: T.unsafe(nil), quality: T.unsafe(nil), **options); end

    # source://image_processing//lib/image_processing/vips.rb#49
    def supports_resize_on_load?; end
  end
end

# source://image_processing//lib/image_processing/processor.rb#34
ImageProcessing::Vips::Processor::ACCUMULATOR_CLASS = Vips::Image

# source://image_processing//lib/image_processing/vips.rb#22
ImageProcessing::Vips::Processor::SHARPEN_MASK = T.let(T.unsafe(nil), Vips::Image)

# source://image_processing//lib/image_processing/vips.rb#198
module ImageProcessing::Vips::Processor::Utils
  private

  # source://image_processing//lib/image_processing/vips.rb#202
  def select_valid_loader_options(source_path, options); end

  # source://image_processing//lib/image_processing/vips.rb#219
  def select_valid_options(operation_name, options); end

  # source://image_processing//lib/image_processing/vips.rb#208
  def select_valid_saver_options(destination_path, options); end

  class << self
    # source://image_processing//lib/image_processing/vips.rb#202
    def select_valid_loader_options(source_path, options); end

    # source://image_processing//lib/image_processing/vips.rb#219
    def select_valid_options(operation_name, options); end

    # source://image_processing//lib/image_processing/vips.rb#208
    def select_valid_saver_options(destination_path, options); end
  end
end
