# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `importmap-rails` gem.
# Please instead update this file by running `bin/tapioca gem importmap-rails`.


# source://importmap-rails//lib/importmap-rails.rb#1
module Importmap; end

# source://importmap-rails//lib/importmap/engine.rb#7
class Importmap::Engine < ::Rails::Engine; end

module Importmap::Freshness
  def stale_when_importmap_changes; end
end

module Importmap::ImportmapTagsHelper
  def javascript_import_module_tag(*module_names); end
  def javascript_importmap_module_preload_tags(importmap = T.unsafe(nil), entry_point: T.unsafe(nil)); end
  def javascript_importmap_tags(entry_point = T.unsafe(nil), importmap: T.unsafe(nil)); end
  def javascript_inline_importmap_tag(importmap_json = T.unsafe(nil)); end
  def javascript_module_preload_tag(*paths); end

  private

  def _generate_preload_tags(items); end
end

# source://importmap-rails//lib/importmap/map.rb#3
class Importmap::Map
  # source://importmap-rails//lib/importmap/map.rb#14
  def initialize; end

  # source://importmap-rails//lib/importmap/map.rb#185
  def cache_sweeper(watches: T.unsafe(nil)); end

  # source://importmap-rails//lib/importmap/map.rb#178
  def digest(resolver:); end

  # source://importmap-rails//lib/importmap/map.rb#4
  def directories; end

  # source://importmap-rails//lib/importmap/map.rb#20
  def draw(path = T.unsafe(nil), &block); end

  # source://importmap-rails//lib/importmap/map.rb#67
  def enable_integrity!; end

  # source://importmap-rails//lib/importmap/map.rb#4
  def packages; end

  # source://importmap-rails//lib/importmap/map.rb#72
  def pin(name, to: T.unsafe(nil), preload: T.unsafe(nil), integrity: T.unsafe(nil)); end

  # source://importmap-rails//lib/importmap/map.rb#77
  def pin_all_from(dir, under: T.unsafe(nil), to: T.unsafe(nil), preload: T.unsafe(nil), integrity: T.unsafe(nil)); end

  # source://importmap-rails//lib/importmap/map.rb#137
  def preloaded_module_packages(resolver:, entry_point: T.unsafe(nil), cache_key: T.unsafe(nil)); end

  # source://importmap-rails//lib/importmap/map.rb#87
  def preloaded_module_paths(resolver:, entry_point: T.unsafe(nil), cache_key: T.unsafe(nil)); end

  # source://importmap-rails//lib/importmap/map.rb#162
  def to_json(resolver:, cache_key: T.unsafe(nil)); end

  private

  # source://importmap-rails//lib/importmap/map.rb#316
  def absolute_root_of(path); end

  # source://importmap-rails//lib/importmap/map.rb#235
  def build_import_map(packages, resolver:); end

  # source://importmap-rails//lib/importmap/map.rb#242
  def build_integrity_hash(packages, resolver:); end

  # source://importmap-rails//lib/importmap/map.rb#200
  def cache_as(name); end

  # source://importmap-rails//lib/importmap/map.rb#208
  def clear_cache; end

  # source://importmap-rails//lib/importmap/map.rb#275
  def expand_directories_into(paths); end

  # source://importmap-rails//lib/importmap/map.rb#271
  def expanded_packages_and_directories; end

  # source://importmap-rails//lib/importmap/map.rb#267
  def expanded_preloading_packages_and_directories(entry_point:); end

  # source://importmap-rails//lib/importmap/map.rb#312
  def find_javascript_files_in_tree(path); end

  # source://importmap-rails//lib/importmap/map.rb#294
  def module_name_from(filename, mapping); end

  # source://importmap-rails//lib/importmap/map.rb#308
  def module_path_from(filename, mapping); end

  # source://importmap-rails//lib/importmap/map.rb#212
  def rescuable_asset_error?(error); end

  # source://importmap-rails//lib/importmap/map.rb#222
  def resolve_asset_path(path, resolver:); end

  # source://importmap-rails//lib/importmap/map.rb#216
  def resolve_asset_paths(paths, resolver:); end

  # source://importmap-rails//lib/importmap/map.rb#256
  def resolve_integrity_value(integrity, path, resolver:); end

  class << self
    # source://importmap-rails//lib/importmap/map.rb#8
    def pin_line_regexp_for(package); end
  end
end

# source://importmap-rails//lib/importmap/map.rb#12
class Importmap::Map::InvalidFile < ::StandardError; end

# source://importmap-rails//lib/importmap/map.rb#197
class Importmap::Map::MappedDir < ::Struct
  # source://importmap-rails//lib/importmap/map.rb#197
  def dir; end

  # source://importmap-rails//lib/importmap/map.rb#197
  def dir=(_); end

  # source://importmap-rails//lib/importmap/map.rb#197
  def integrity; end

  # source://importmap-rails//lib/importmap/map.rb#197
  def integrity=(_); end

  # source://importmap-rails//lib/importmap/map.rb#197
  def path; end

  # source://importmap-rails//lib/importmap/map.rb#197
  def path=(_); end

  # source://importmap-rails//lib/importmap/map.rb#197
  def preload; end

  # source://importmap-rails//lib/importmap/map.rb#197
  def preload=(_); end

  # source://importmap-rails//lib/importmap/map.rb#197
  def under; end

  # source://importmap-rails//lib/importmap/map.rb#197
  def under=(_); end

  class << self
    # source://importmap-rails//lib/importmap/map.rb#197
    def [](*_arg0); end

    # source://importmap-rails//lib/importmap/map.rb#197
    def inspect; end

    # source://importmap-rails//lib/importmap/map.rb#197
    def keyword_init?; end

    # source://importmap-rails//lib/importmap/map.rb#197
    def members; end

    # source://importmap-rails//lib/importmap/map.rb#197
    def new(*_arg0); end
  end
end

# source://importmap-rails//lib/importmap/map.rb#198
class Importmap::Map::MappedFile < ::Struct
  # source://importmap-rails//lib/importmap/map.rb#198
  def integrity; end

  # source://importmap-rails//lib/importmap/map.rb#198
  def integrity=(_); end

  # source://importmap-rails//lib/importmap/map.rb#198
  def name; end

  # source://importmap-rails//lib/importmap/map.rb#198
  def name=(_); end

  # source://importmap-rails//lib/importmap/map.rb#198
  def path; end

  # source://importmap-rails//lib/importmap/map.rb#198
  def path=(_); end

  # source://importmap-rails//lib/importmap/map.rb#198
  def preload; end

  # source://importmap-rails//lib/importmap/map.rb#198
  def preload=(_); end

  class << self
    # source://importmap-rails//lib/importmap/map.rb#198
    def [](*_arg0); end

    # source://importmap-rails//lib/importmap/map.rb#198
    def inspect; end

    # source://importmap-rails//lib/importmap/map.rb#198
    def keyword_init?; end

    # source://importmap-rails//lib/importmap/map.rb#198
    def members; end

    # source://importmap-rails//lib/importmap/map.rb#198
    def new(*_arg0); end
  end
end

# source://importmap-rails//lib/importmap/map.rb#6
Importmap::Map::PIN_REGEX = T.let(T.unsafe(nil), Regexp)

# source://importmap-rails//lib/importmap/reloader.rb#4
class Importmap::Reloader
  # source://importmap-rails//lib/importmap/reloader.rb#5
  def execute(*_arg0, **_arg1, &_arg2); end

  # source://importmap-rails//lib/importmap/reloader.rb#5
  def execute_if_updated(*_arg0, **_arg1, &_arg2); end

  # source://importmap-rails//lib/importmap/reloader.rb#7
  def reload!; end

  # source://importmap-rails//lib/importmap/reloader.rb#5
  def updated?(*_arg0, **_arg1, &_arg2); end

  private

  # source://importmap-rails//lib/importmap/reloader.rb#20
  def config; end

  # source://importmap-rails//lib/importmap/reloader.rb#16
  def import_map_paths; end

  # source://importmap-rails//lib/importmap/reloader.rb#12
  def updater; end
end

# source://importmap-rails//lib/importmap/version.rb#2
Importmap::VERSION = T.let(T.unsafe(nil), String)
