# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `propshaft` gem.
# Please instead update this file by running `bin/tapioca gem propshaft`.


# source://propshaft//lib/propshaft.rb#6
module Propshaft
  # source://propshaft//lib/propshaft.rb#7
  def logger; end

  # source://propshaft//lib/propshaft.rb#7
  def logger=(val); end

  class << self
    # source://propshaft//lib/propshaft.rb#7
    def logger; end

    # source://propshaft//lib/propshaft.rb#7
    def logger=(val); end
  end
end

# source://propshaft//lib/propshaft/assembly.rb#12
class Propshaft::Assembly
  # source://propshaft//lib/propshaft/assembly.rb#15
  def initialize(config); end

  # source://propshaft//lib/propshaft/assembly.rb#49
  def compilers; end

  # source://propshaft//lib/propshaft/assembly.rb#13
  def config; end

  # source://propshaft//lib/propshaft/assembly.rb#19
  def load_path; end

  # source://propshaft//lib/propshaft/assembly.rb#37
  def prefix; end

  # source://propshaft//lib/propshaft/assembly.rb#44
  def processor; end

  # source://propshaft//lib/propshaft/assembly.rb#29
  def resolver; end

  # source://propshaft//lib/propshaft/assembly.rb#58
  def reveal(path_type = T.unsafe(nil)); end
end

# source://propshaft//lib/propshaft/asset.rb#5
class Propshaft::Asset
  # source://propshaft//lib/propshaft/asset.rb#17
  def initialize(path, logical_path:, load_path:); end

  # source://propshaft//lib/propshaft/asset.rb#71
  def ==(other_asset); end

  # source://propshaft//lib/propshaft/asset.rb#21
  def compiled_content; end

  # source://propshaft//lib/propshaft/asset.rb#25
  def content(encoding: T.unsafe(nil)); end

  # source://propshaft//lib/propshaft/asset.rb#29
  def content_type; end

  # source://propshaft//lib/propshaft/asset.rb#37
  def digest; end

  # source://propshaft//lib/propshaft/asset.rb#59
  def digested_path; end

  # source://propshaft//lib/propshaft/asset.rb#67
  def fresh?(digest); end

  # source://propshaft//lib/propshaft/asset.rb#41
  def integrity(hash_algorithm:); end

  # source://propshaft//lib/propshaft/asset.rb#33
  def length; end

  # source://propshaft//lib/propshaft/asset.rb#6
  def load_path; end

  # source://propshaft//lib/propshaft/asset.rb#6
  def logical_path; end

  # source://propshaft//lib/propshaft/asset.rb#6
  def path; end

  private

  # source://propshaft//lib/propshaft/asset.rb#80
  def already_digested?; end

  # source://propshaft//lib/propshaft/asset.rb#76
  def content_with_compile_references; end

  class << self
    # source://propshaft//lib/propshaft/asset.rb#9
    def extract_path_and_digest(digested_path); end
  end
end

# source://propshaft//lib/propshaft/compiler.rb#4
class Propshaft::Compiler
  # source://propshaft//lib/propshaft/compiler.rb#8
  def initialize(assembly); end

  # source://propshaft//lib/propshaft/compiler.rb#5
  def assembly; end

  # source://propshaft//lib/propshaft/compiler.rb#13
  def compile(asset, input); end

  # source://propshaft//lib/propshaft/compiler.rb#6
  def config(*_arg0, **_arg1, &_arg2); end

  # source://propshaft//lib/propshaft/compiler.rb#6
  def load_path(*_arg0, **_arg1, &_arg2); end

  # source://propshaft//lib/propshaft/compiler.rb#17
  def referenced_by(asset); end

  private

  # source://propshaft//lib/propshaft/compiler.rb#22
  def url_prefix; end
end

# source://propshaft//lib/propshaft/compiler/css_asset_urls.rb#5
class Propshaft::Compiler::CssAssetUrls < ::Propshaft::Compiler
  # source://propshaft//lib/propshaft/compiler/css_asset_urls.rb#8
  def compile(asset, input); end

  # source://propshaft//lib/propshaft/compiler/css_asset_urls.rb#12
  def referenced_by(asset, references: T.unsafe(nil)); end

  private

  # source://propshaft//lib/propshaft/compiler/css_asset_urls.rb#36
  def asset_url(resolved_path, logical_path, fingerprint, pattern); end

  # source://propshaft//lib/propshaft/compiler/css_asset_urls.rb#26
  def resolve_path(directory, filename); end
end

# source://propshaft//lib/propshaft/compiler/css_asset_urls.rb#6
Propshaft::Compiler::CssAssetUrls::ASSET_URL_PATTERN = T.let(T.unsafe(nil), Regexp)

# source://propshaft//lib/propshaft/compiler/js_asset_urls.rb#5
class Propshaft::Compiler::JsAssetUrls < ::Propshaft::Compiler
  # source://propshaft//lib/propshaft/compiler/js_asset_urls.rb#8
  def compile(asset, input); end

  # source://propshaft//lib/propshaft/compiler/js_asset_urls.rb#12
  def referenced_by(asset, references: T.unsafe(nil)); end

  private

  # source://propshaft//lib/propshaft/compiler/js_asset_urls.rb#36
  def asset_url(resolved_path, logical_path, fingerprint, pattern); end

  # source://propshaft//lib/propshaft/compiler/js_asset_urls.rb#26
  def resolve_path(directory, filename); end
end

# source://propshaft//lib/propshaft/compiler/js_asset_urls.rb#6
Propshaft::Compiler::JsAssetUrls::ASSET_URL_PATTERN = T.let(T.unsafe(nil), Regexp)

# source://propshaft//lib/propshaft/compiler/source_mapping_urls.rb#5
class Propshaft::Compiler::SourceMappingUrls < ::Propshaft::Compiler
  # source://propshaft//lib/propshaft/compiler/source_mapping_urls.rb#8
  def compile(asset, input); end

  private

  # source://propshaft//lib/propshaft/compiler/source_mapping_urls.rb#13
  def asset_path(source_mapping_url, logical_path); end

  # source://propshaft//lib/propshaft/compiler/source_mapping_urls.rb#23
  def source_mapping_url(logical_path, resolved_path, comment_start, comment_end); end
end

# source://propshaft//lib/propshaft/compiler/source_mapping_urls.rb#6
Propshaft::Compiler::SourceMappingUrls::SOURCE_MAPPING_PATTERN = T.let(T.unsafe(nil), Regexp)

# source://propshaft//lib/propshaft/compilers.rb#1
class Propshaft::Compilers
  # source://propshaft//lib/propshaft/compilers.rb#4
  def initialize(assembly); end

  # source://propshaft//lib/propshaft/compilers.rb#14
  def any?; end

  # source://propshaft//lib/propshaft/compilers.rb#2
  def assembly; end

  # source://propshaft//lib/propshaft/compilers.rb#18
  def compilable?(asset); end

  # source://propshaft//lib/propshaft/compilers.rb#22
  def compile(asset); end

  # source://propshaft//lib/propshaft/compilers.rb#34
  def referenced_by(asset); end

  # source://propshaft//lib/propshaft/compilers.rb#9
  def register(mime_type, klass); end

  # source://propshaft//lib/propshaft/compilers.rb#2
  def registrations; end
end

# source://propshaft//lib/propshaft/errors.rb#5
class Propshaft::Error < ::StandardError; end

# source://propshaft//lib/propshaft/helper.rb#35
module Propshaft::Helper
  # source://propshaft//lib/propshaft/helper.rb#107
  def all_stylesheets_paths; end

  # source://propshaft//lib/propshaft/helper.rb#112
  def app_stylesheets_paths; end

  # source://propshaft//lib/propshaft/helper.rb#43
  def asset_integrity(path, options = T.unsafe(nil)); end

  # source://propshaft//lib/propshaft/helper.rb#49
  def compute_asset_path(path, options = T.unsafe(nil)); end

  # source://propshaft//lib/propshaft/helper.rb#100
  def javascript_include_tag(*sources); end

  # source://propshaft//lib/propshaft/helper.rb#73
  def stylesheet_link_tag(*sources); end

  private

  # source://propshaft//lib/propshaft/helper.rb#121
  def _build_asset_tags(sources, options, asset_type); end

  # source://propshaft//lib/propshaft/helper.rb#135
  def _compute_integrity?(options); end

  # source://propshaft//lib/propshaft/helper.rb#157
  def _path_with_extname(path, options); end

  # source://propshaft//lib/propshaft/helper.rb#152
  def _secure_subresource_integrity_context?; end
end

# source://propshaft//lib/propshaft/load_path.rb#4
class Propshaft::LoadPath
  # source://propshaft//lib/propshaft/load_path.rb#17
  def initialize(paths = T.unsafe(nil), compilers:, version: T.unsafe(nil), file_watcher: T.unsafe(nil), integrity_hash_algorithm: T.unsafe(nil)); end

  # source://propshaft//lib/propshaft/load_path.rb#39
  def asset_paths_by_glob(glob); end

  # source://propshaft//lib/propshaft/load_path.rb#34
  def asset_paths_by_type(content_type); end

  # source://propshaft//lib/propshaft/load_path.rb#30
  def assets; end

  # source://propshaft//lib/propshaft/load_path.rb#53
  def cache_sweeper; end

  # source://propshaft//lib/propshaft/load_path.rb#15
  def compilers; end

  # source://propshaft//lib/propshaft/load_path.rb#22
  def find(asset_name); end

  # source://propshaft//lib/propshaft/load_path.rb#26
  def find_referenced_by(asset); end

  # source://propshaft//lib/propshaft/load_path.rb#15
  def integrity_hash_algorithm; end

  # source://propshaft//lib/propshaft/load_path.rb#44
  def manifest; end

  # source://propshaft//lib/propshaft/load_path.rb#15
  def paths; end

  # source://propshaft//lib/propshaft/load_path.rb#15
  def version; end

  private

  # source://propshaft//lib/propshaft/load_path.rb#80
  def all_files_from_tree(path); end

  # source://propshaft//lib/propshaft/load_path.rb#69
  def assets_by_path; end

  # source://propshaft//lib/propshaft/load_path.rb#92
  def clear_cache; end

  # source://propshaft//lib/propshaft/load_path.rb#102
  def dedup(paths); end

  # source://propshaft//lib/propshaft/load_path.rb#84
  def extract_logical_paths_from(assets); end

  # source://propshaft//lib/propshaft/load_path.rb#98
  def seed_cache; end

  # source://propshaft//lib/propshaft/load_path.rb#88
  def without_dotfiles(files); end
end

# source://propshaft//lib/propshaft/load_path.rb#5
class Propshaft::LoadPath::NullFileWatcher
  # source://propshaft//lib/propshaft/load_path.rb#6
  def initialize(paths, files_to_watch, &block); end

  # source://propshaft//lib/propshaft/load_path.rb#10
  def execute_if_updated; end
end

# source://propshaft//lib/propshaft/manifest.rb#6
class Propshaft::Manifest
  # source://propshaft//lib/propshaft/manifest.rb#82
  def initialize(integrity_hash_algorithm: T.unsafe(nil)); end

  # source://propshaft//lib/propshaft/manifest.rb#122
  def <<(entry); end

  # source://propshaft//lib/propshaft/manifest.rb#133
  def [](logical_path); end

  # source://propshaft//lib/propshaft/manifest.rb#146
  def delete(logical_path); end

  # source://propshaft//lib/propshaft/manifest.rb#119
  def push(entry); end

  # source://propshaft//lib/propshaft/manifest.rb#100
  def push_asset(asset); end

  # source://propshaft//lib/propshaft/manifest.rb#158
  def to_json; end

  # source://propshaft//lib/propshaft/manifest.rb#176
  def transform_values(&block); end

  private

  # source://propshaft//lib/propshaft/manifest.rb#181
  def integrity_hash_algorithm; end

  class << self
    # source://propshaft//lib/propshaft/manifest.rb#50
    def from_path(manifest_path); end
  end
end

# source://propshaft//lib/propshaft/manifest.rb#12
class Propshaft::Manifest::ManifestEntry
  # source://propshaft//lib/propshaft/manifest.rb#22
  def initialize(logical_path:, digested_path:, integrity:); end

  # source://propshaft//lib/propshaft/manifest.rb#13
  def digested_path; end

  # source://propshaft//lib/propshaft/manifest.rb#13
  def integrity; end

  # source://propshaft//lib/propshaft/manifest.rb#13
  def logical_path; end

  # source://propshaft//lib/propshaft/manifest.rb#31
  def to_h; end
end

# source://propshaft//lib/propshaft/errors.rb#8
class Propshaft::MissingAssetError < ::Propshaft::Error
  # source://propshaft//lib/propshaft/errors.rb#9
  def initialize(path); end

  # source://propshaft//lib/propshaft/errors.rb#14
  def message; end
end

# source://propshaft//lib/propshaft/output_path.rb#3
class Propshaft::OutputPath
  # source://propshaft//lib/propshaft/output_path.rb#6
  def initialize(path, manifest); end

  # source://propshaft//lib/propshaft/output_path.rb#10
  def clean(count, age); end

  # source://propshaft//lib/propshaft/output_path.rb#25
  def files; end

  # source://propshaft//lib/propshaft/output_path.rb#4
  def manifest; end

  # source://propshaft//lib/propshaft/output_path.rb#4
  def path; end

  private

  # source://propshaft//lib/propshaft/output_path.rb#51
  def all_files_from_tree(path); end

  # source://propshaft//lib/propshaft/output_path.rb#41
  def fresh_version_within_limit(mtime, count, expires_at:, limit:); end

  # source://propshaft//lib/propshaft/output_path.rb#46
  def remove(path); end
end

# source://propshaft//lib/propshaft/processor.rb#3
class Propshaft::Processor
  # source://propshaft//lib/propshaft/processor.rb#6
  def initialize(load_path:, output_path:, compilers:, manifest_path:); end

  # source://propshaft//lib/propshaft/processor.rb#22
  def clean(count); end

  # source://propshaft//lib/propshaft/processor.rb#18
  def clobber; end

  # source://propshaft//lib/propshaft/processor.rb#4
  def compilers; end

  # source://propshaft//lib/propshaft/processor.rb#4
  def load_path; end

  # source://propshaft//lib/propshaft/processor.rb#4
  def manifest_path; end

  # source://propshaft//lib/propshaft/processor.rb#4
  def output_path; end

  # source://propshaft//lib/propshaft/processor.rb#12
  def process; end

  private

  # source://propshaft//lib/propshaft/processor.rb#54
  def compile_asset(asset); end

  # source://propshaft//lib/propshaft/processor.rb#65
  def copy_asset(asset); end

  # source://propshaft//lib/propshaft/processor.rb#27
  def ensure_output_path_exists; end

  # source://propshaft//lib/propshaft/processor.rb#50
  def output_asset(asset); end

  # source://propshaft//lib/propshaft/processor.rb#40
  def output_assets; end

  # source://propshaft//lib/propshaft/processor.rb#32
  def write_manifest; end
end

# source://propshaft//lib/propshaft/quiet_assets.rb#1
class Propshaft::QuietAssets
  # source://propshaft//lib/propshaft/quiet_assets.rb#2
  def initialize(app); end

  # source://propshaft//lib/propshaft/quiet_assets.rb#7
  def call(env); end
end

# source://propshaft//lib/propshaft/railtie.rb#6
class Propshaft::Railtie < ::Rails::Railtie; end

# source://propshaft//lib/propshaft/resolver/dynamic.rb#1
module Propshaft::Resolver; end

# source://propshaft//lib/propshaft/resolver/dynamic.rb#2
class Propshaft::Resolver::Dynamic
  # source://propshaft//lib/propshaft/resolver/dynamic.rb#5
  def initialize(load_path:, prefix:); end

  # source://propshaft//lib/propshaft/resolver/dynamic.rb#15
  def integrity(logical_path); end

  # source://propshaft//lib/propshaft/resolver/dynamic.rb#3
  def load_path; end

  # source://propshaft//lib/propshaft/resolver/dynamic.rb#3
  def prefix; end

  # source://propshaft//lib/propshaft/resolver/dynamic.rb#23
  def read(logical_path, options = T.unsafe(nil)); end

  # source://propshaft//lib/propshaft/resolver/dynamic.rb#9
  def resolve(logical_path); end

  private

  # source://propshaft//lib/propshaft/resolver/dynamic.rb#30
  def find_asset(logical_path); end
end

# source://propshaft//lib/propshaft/resolver/static.rb#2
class Propshaft::Resolver::Static
  # source://propshaft//lib/propshaft/resolver/static.rb#5
  def initialize(manifest_path:, prefix:); end

  # source://propshaft//lib/propshaft/resolver/static.rb#15
  def integrity(logical_path); end

  # source://propshaft//lib/propshaft/resolver/static.rb#3
  def manifest_path; end

  # source://propshaft//lib/propshaft/resolver/static.rb#3
  def prefix; end

  # source://propshaft//lib/propshaft/resolver/static.rb#21
  def read(logical_path, encoding: T.unsafe(nil)); end

  # source://propshaft//lib/propshaft/resolver/static.rb#9
  def resolve(logical_path); end

  private

  # source://propshaft//lib/propshaft/resolver/static.rb#32
  def digested_path(logical_path); end

  # source://propshaft//lib/propshaft/resolver/static.rb#28
  def manifest; end
end

# source://propshaft//lib/propshaft/server.rb#4
class Propshaft::Server
  # source://propshaft//lib/propshaft/server.rb#5
  def initialize(app, assembly); end

  # source://propshaft//lib/propshaft/server.rb#10
  def call(env); end

  # source://propshaft//lib/propshaft/server.rb#41
  def inspect; end

  private

  # source://propshaft//lib/propshaft/server.rb#59
  def execute_cache_sweeper_if_updated; end

  # source://propshaft//lib/propshaft/server.rb#46
  def extract_path_and_digest(path); end
end

# source://propshaft//lib/propshaft/server.rb#56
Propshaft::Server::VARY = T.let(T.unsafe(nil), String)
