# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `raabro` gem.
# Please instead update this file by running `bin/tapioca gem raabro`.


# source://raabro//lib/raabro.rb#3
module Raabro
  extend ::Raabro::ModuleMethods

  class << self
    # source://raabro//lib/raabro.rb#596
    def included(target); end

    # source://raabro//lib/raabro.rb#618
    def pp(tree, depth = T.unsafe(nil), opts = T.unsafe(nil)); end
  end
end

# source://raabro//lib/raabro.rb#7
class Raabro::Input
  # source://raabro//lib/raabro.rb#12
  def initialize(string, offset = T.unsafe(nil), options = T.unsafe(nil)); end

  # source://raabro//lib/raabro.rb#36
  def at(i); end

  # source://raabro//lib/raabro.rb#19
  def match(str_or_regex); end

  # source://raabro//lib/raabro.rb#9
  def offset; end

  # source://raabro//lib/raabro.rb#9
  def offset=(_arg0); end

  # source://raabro//lib/raabro.rb#10
  def options; end

  # source://raabro//lib/raabro.rb#9
  def string; end

  # source://raabro//lib/raabro.rb#9
  def string=(_arg0); end

  # source://raabro//lib/raabro.rb#31
  def tring(l = T.unsafe(nil)); end
end

# source://raabro//lib/raabro.rb#240
module Raabro::ModuleMethods
  # source://raabro//lib/raabro.rb#242
  def _match(name, input, parter, regex_or_string); end

  # source://raabro//lib/raabro.rb#279
  def _narrow(parser); end

  # source://raabro//lib/raabro.rb#286
  def _parse(parser, input); end

  # source://raabro//lib/raabro.rb#265
  def _quantify(parser); end

  # source://raabro//lib/raabro.rb#438
  def all(name, input, parser); end

  # source://raabro//lib/raabro.rb#333
  def alt(name, input, *parsers); end

  # source://raabro//lib/raabro.rb#378
  def altg(name, input, *parsers); end

  # source://raabro//lib/raabro.rb#457
  def eseq(name, input, startpa, eltpa, seppa = T.unsafe(nil), endpa = T.unsafe(nil)); end

  # source://raabro//lib/raabro.rb#527
  def jseq(name, input, startpa, eltpa, seppa = T.unsafe(nil), endpa = T.unsafe(nil)); end

  # source://raabro//lib/raabro.rb#529
  def last; end

  # source://raabro//lib/raabro.rb#529
  def last=(_arg0); end

  # source://raabro//lib/raabro.rb#594
  def make_includable; end

  # source://raabro//lib/raabro.rb#531
  def method_added(name); end

  # source://raabro//lib/raabro.rb#422
  def nott(name, input, parser); end

  # source://raabro//lib/raabro.rb#540
  def parse(input, opts = T.unsafe(nil)); end

  # source://raabro//lib/raabro.rb#413
  def ren(name, input, parser); end

  # source://raabro//lib/raabro.rb#420
  def rename(name, input, parser); end

  # source://raabro//lib/raabro.rb#383
  def rep(name, input, parser, min, max = T.unsafe(nil)); end

  # source://raabro//lib/raabro.rb#568
  def reparse_for_error(input, opts, t); end

  # source://raabro//lib/raabro.rb#586
  def rewrite(tree); end

  # source://raabro//lib/raabro.rb#579
  def rewrite_(tree); end

  # source://raabro//lib/raabro.rb#260
  def rex(name, input, regex_or_string); end

  # source://raabro//lib/raabro.rb#295
  def seq(name, input, *parsers); end

  # source://raabro//lib/raabro.rb#255
  def str(name, input, string); end
end

# source://raabro//lib/raabro.rb#42
class Raabro::Tree
  # source://raabro//lib/raabro.rb#49
  def initialize(name, parter, input); end

  # source://raabro//lib/raabro.rb#60
  def c0; end

  # source://raabro//lib/raabro.rb#61
  def c1; end

  # source://raabro//lib/raabro.rb#62
  def c2; end

  # source://raabro//lib/raabro.rb#63
  def c3; end

  # source://raabro//lib/raabro.rb#64
  def c4; end

  # source://raabro//lib/raabro.rb#47
  def children; end

  # source://raabro//lib/raabro.rb#47
  def children=(_arg0); end

  # source://raabro//lib/raabro.rb#65
  def clast; end

  # source://raabro//lib/raabro.rb#67
  def empty?; end

  # source://raabro//lib/raabro.rb#166
  def even_children; end

  # source://raabro//lib/raabro.rb#171
  def extract_error; end

  # source://raabro//lib/raabro.rb#112
  def gather(name = T.unsafe(nil), acc = T.unsafe(nil)); end

  # source://raabro//lib/raabro.rb#44
  def input; end

  # source://raabro//lib/raabro.rb#44
  def input=(_arg0); end

  # source://raabro//lib/raabro.rb#46
  def length; end

  # source://raabro//lib/raabro.rb#46
  def length=(_arg0); end

  # source://raabro//lib/raabro.rb#216
  def line_and_column(offset); end

  # source://raabro//lib/raabro.rb#96
  def lookup(name = T.unsafe(nil)); end

  # source://raabro//lib/raabro.rb#208
  def lookup_all_error; end

  # source://raabro//lib/raabro.rb#193
  def lookup_error(stack = T.unsafe(nil)); end

  # source://raabro//lib/raabro.rb#44
  def name; end

  # source://raabro//lib/raabro.rb#44
  def name=(_arg0); end

  # source://raabro//lib/raabro.rb#85
  def nonstring(l = T.unsafe(nil)); end

  # source://raabro//lib/raabro.rb#161
  def odd_children; end

  # source://raabro//lib/raabro.rb#46
  def offset; end

  # source://raabro//lib/raabro.rb#46
  def offset=(_arg0); end

  # source://raabro//lib/raabro.rb#47
  def parter; end

  # source://raabro//lib/raabro.rb#47
  def parter=(_arg0); end

  # source://raabro//lib/raabro.rb#77
  def prune!; end

  # source://raabro//lib/raabro.rb#45
  def result; end

  # source://raabro//lib/raabro.rb#45
  def result=(_arg0); end

  # source://raabro//lib/raabro.rb#84
  def strim; end

  # source://raabro//lib/raabro.rb#88
  def strind; end

  # source://raabro//lib/raabro.rb#82
  def string; end

  # source://raabro//lib/raabro.rb#87
  def stringd; end

  # source://raabro//lib/raabro.rb#89
  def stringpd; end

  # source://raabro//lib/raabro.rb#83
  def strinp; end

  # source://raabro//lib/raabro.rb#90
  def strinpd; end

  # source://raabro//lib/raabro.rb#125
  def subgather(name = T.unsafe(nil), acc = T.unsafe(nil)); end

  # source://raabro//lib/raabro.rb#105
  def sublookup(name = T.unsafe(nil)); end

  # source://raabro//lib/raabro.rb#72
  def successful_children; end

  # source://raabro//lib/raabro.rb#94
  def symbod; end

  # source://raabro//lib/raabro.rb#92
  def symbol; end

  # source://raabro//lib/raabro.rb#93
  def symbold; end

  # source://raabro//lib/raabro.rb#132
  def to_a(opts = T.unsafe(nil)); end

  # source://raabro//lib/raabro.rb#149
  def to_s(depth = T.unsafe(nil), io = T.unsafe(nil)); end

  # source://raabro//lib/raabro.rb#233
  def visual(line, column); end
end

# source://raabro//lib/raabro.rb#5
Raabro::VERSION = T.let(T.unsafe(nil), String)
