# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `require-hooks` gem.
# Please instead update this file by running `bin/tapioca gem require-hooks`.


# source://require-hooks//lib/require-hooks/api.rb#3
module RequireHooks
  class << self
    # source://require-hooks//lib/require-hooks/api.rb#71
    def around_load(patterns: T.unsafe(nil), exclude_patterns: T.unsafe(nil), &block); end

    # source://require-hooks//lib/require-hooks/api.rb#107
    def context_for(path); end

    # source://require-hooks//lib/require-hooks/api.rb#103
    def hijack_load(patterns: T.unsafe(nil), exclude_patterns: T.unsafe(nil), &block); end

    # source://require-hooks//lib/require-hooks/api.rb#61
    def print_warnings; end

    # source://require-hooks//lib/require-hooks/api.rb#61
    def print_warnings=(_arg0); end

    # source://require-hooks//lib/require-hooks/api.rb#85
    def source_transform(patterns: T.unsafe(nil), exclude_patterns: T.unsafe(nil), &block); end
  end
end

# source://require-hooks//lib/require-hooks/api.rb#8
class RequireHooks::Context
  # source://require-hooks//lib/require-hooks/api.rb#9
  def initialize(around_load, source_transform, hijack_load); end

  # source://require-hooks//lib/require-hooks/api.rb#15
  def empty?; end

  # source://require-hooks//lib/require-hooks/api.rb#23
  def hijack?; end

  # source://require-hooks//lib/require-hooks/api.rb#37
  def perform_source_transform(path); end

  # source://require-hooks//lib/require-hooks/api.rb#27
  def run_around_load_callbacks(path); end

  # source://require-hooks//lib/require-hooks/api.rb#19
  def source_transform?; end

  # source://require-hooks//lib/require-hooks/api.rb#49
  def try_hijack_load(path, source); end
end

# source://require-hooks//lib/require-hooks/mode/load_iseq.rb#4
module RequireHooks::LoadIseq
  # source://require-hooks//lib/require-hooks/mode/load_iseq.rb#5
  def load_iseq(path); end
end

# source://require-hooks//lib/require-hooks/version.rb#4
RequireHooks::VERSION = T.let(T.unsafe(nil), String)

class RubyVM::InstructionSequence
  extend ::RequireHooks::LoadIseq
  extend ::Bootsnap::CompileCache::ISeq::InstructionSequenceMixin
end
