# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `ruby-vips` gem.
# Please instead update this file by running `bin/tapioca gem ruby-vips`.


# source://ruby-vips//lib/vips.rb#60
module GLib
  extend ::FFI::Library

  # source://ruby-vips//lib/vips.rb#79
  def g_free(*_arg0); end

  # source://ruby-vips//lib/vips.rb#84
  def g_log_remove_handler(*_arg0); end

  # source://ruby-vips//lib/vips.rb#82
  def g_log_set_handler(*_arg0); end

  # source://ruby-vips//lib/vips.rb#75
  def g_malloc(*_arg0); end

  class << self
    # source://ruby-vips//lib/vips.rb#79
    def g_free(*_arg0); end

    # source://ruby-vips//lib/vips.rb#84
    def g_log_remove_handler(*_arg0); end

    # source://ruby-vips//lib/vips.rb#82
    def g_log_set_handler(*_arg0); end

    # source://ruby-vips//lib/vips.rb#75
    def g_malloc(*_arg0); end

    # source://ruby-vips//lib/vips.rb#62
    def logger; end

    # source://ruby-vips//lib/vips.rb#62
    def logger=(_arg0); end

    # source://ruby-vips//lib/vips.rb#118
    def remove_log_handler; end

    # source://ruby-vips//lib/vips.rb#125
    def set_log_domain(domain); end
  end
end

# source://ruby-vips//lib/vips.rb#99
GLib::GLIB_TO_SEVERITY = T.let(T.unsafe(nil), Hash)

# source://ruby-vips//lib/vips.rb#79
GLib::G_FREE = T.let(T.unsafe(nil), FFI::Function)

# source://ruby-vips//lib/vips.rb#88
GLib::LOG_FLAG_FATAL = T.let(T.unsafe(nil), Integer)

# source://ruby-vips//lib/vips.rb#87
GLib::LOG_FLAG_RECURSION = T.let(T.unsafe(nil), Integer)

# source://ruby-vips//lib/vips.rb#114
GLib::LOG_HANDLER = T.let(T.unsafe(nil), Proc)

# source://ruby-vips//lib/vips.rb#92
GLib::LOG_LEVEL_CRITICAL = T.let(T.unsafe(nil), Integer)

# source://ruby-vips//lib/vips.rb#96
GLib::LOG_LEVEL_DEBUG = T.let(T.unsafe(nil), Integer)

# source://ruby-vips//lib/vips.rb#91
GLib::LOG_LEVEL_ERROR = T.let(T.unsafe(nil), Integer)

# source://ruby-vips//lib/vips.rb#95
GLib::LOG_LEVEL_INFO = T.let(T.unsafe(nil), Integer)

# source://ruby-vips//lib/vips.rb#94
GLib::LOG_LEVEL_MESSAGE = T.let(T.unsafe(nil), Integer)

# source://ruby-vips//lib/vips.rb#93
GLib::LOG_LEVEL_WARNING = T.let(T.unsafe(nil), Integer)

# source://ruby-vips//lib/vips.rb#162
module GObject
  extend ::FFI::Library

  # source://ruby-vips//lib/vips/gvalue.rb#323
  def g_object_get_property(*_arg0); end

  # source://ruby-vips//lib/vips/gobject.rb#126
  def g_object_ref(*_arg0); end

  # source://ruby-vips//lib/vips/gvalue.rb#321
  def g_object_set_property(*_arg0); end

  # source://ruby-vips//lib/vips/gobject.rb#127
  def g_object_unref(*_arg0); end

  # source://ruby-vips//lib/vips/gobject.rb#124
  def g_param_spec_get_blurb(*_arg0); end

  # source://ruby-vips//lib/vips/gobject.rb#131
  def g_signal_connect_data(*_arg0); end

  # source://ruby-vips//lib/vips.rb#180
  def g_type_from_name(*_arg0); end

  # source://ruby-vips//lib/vips.rb#181
  def g_type_fundamental(*_arg0); end

  # source://ruby-vips//lib/vips.rb#178
  def g_type_init(*_arg0); end

  # source://ruby-vips//lib/vips.rb#179
  def g_type_name(*_arg0); end

  # source://ruby-vips//lib/vips/gvalue.rb#311
  def g_value_get_boolean(*_arg0); end

  # source://ruby-vips//lib/vips/gvalue.rb#314
  def g_value_get_double(*_arg0); end

  # source://ruby-vips//lib/vips/gvalue.rb#315
  def g_value_get_enum(*_arg0); end

  # source://ruby-vips//lib/vips/gvalue.rb#316
  def g_value_get_flags(*_arg0); end

  # source://ruby-vips//lib/vips/gvalue.rb#312
  def g_value_get_int(*_arg0); end

  # source://ruby-vips//lib/vips/gvalue.rb#318
  def g_value_get_object(*_arg0); end

  # source://ruby-vips//lib/vips/gvalue.rb#317
  def g_value_get_string(*_arg0); end

  # source://ruby-vips//lib/vips/gvalue.rb#313
  def g_value_get_uint64(*_arg0); end

  # source://ruby-vips//lib/vips/gvalue.rb#296
  def g_value_init(*_arg0); end

  # source://ruby-vips//lib/vips/gvalue.rb#302
  def g_value_set_boolean(*_arg0); end

  # source://ruby-vips//lib/vips/gvalue.rb#305
  def g_value_set_double(*_arg0); end

  # source://ruby-vips//lib/vips/gvalue.rb#306
  def g_value_set_enum(*_arg0); end

  # source://ruby-vips//lib/vips/gvalue.rb#307
  def g_value_set_flags(*_arg0); end

  # source://ruby-vips//lib/vips/gvalue.rb#303
  def g_value_set_int(*_arg0); end

  # source://ruby-vips//lib/vips/gvalue.rb#309
  def g_value_set_object(*_arg0); end

  # source://ruby-vips//lib/vips/gvalue.rb#308
  def g_value_set_string(*_arg0); end

  # source://ruby-vips//lib/vips/gvalue.rb#304
  def g_value_set_uint64(*_arg0); end

  # source://ruby-vips//lib/vips/gvalue.rb#300
  def g_value_unset(*_arg0); end

  class << self
    # source://ruby-vips//lib/vips/gvalue.rb#323
    def g_object_get_property(*_arg0); end

    # source://ruby-vips//lib/vips/gobject.rb#126
    def g_object_ref(*_arg0); end

    # source://ruby-vips//lib/vips/gvalue.rb#321
    def g_object_set_property(*_arg0); end

    # source://ruby-vips//lib/vips/gobject.rb#127
    def g_object_unref(*_arg0); end

    # source://ruby-vips//lib/vips/gobject.rb#124
    def g_param_spec_get_blurb(*_arg0); end

    # source://ruby-vips//lib/vips/gobject.rb#131
    def g_signal_connect_data(*_arg0); end

    # source://ruby-vips//lib/vips.rb#180
    def g_type_from_name(*_arg0); end

    # source://ruby-vips//lib/vips.rb#181
    def g_type_fundamental(*_arg0); end

    # source://ruby-vips//lib/vips.rb#178
    def g_type_init(*_arg0); end

    # source://ruby-vips//lib/vips.rb#179
    def g_type_name(*_arg0); end

    # source://ruby-vips//lib/vips/gvalue.rb#311
    def g_value_get_boolean(*_arg0); end

    # source://ruby-vips//lib/vips/gvalue.rb#314
    def g_value_get_double(*_arg0); end

    # source://ruby-vips//lib/vips/gvalue.rb#315
    def g_value_get_enum(*_arg0); end

    # source://ruby-vips//lib/vips/gvalue.rb#316
    def g_value_get_flags(*_arg0); end

    # source://ruby-vips//lib/vips/gvalue.rb#312
    def g_value_get_int(*_arg0); end

    # source://ruby-vips//lib/vips/gvalue.rb#318
    def g_value_get_object(*_arg0); end

    # source://ruby-vips//lib/vips/gvalue.rb#317
    def g_value_get_string(*_arg0); end

    # source://ruby-vips//lib/vips/gvalue.rb#313
    def g_value_get_uint64(*_arg0); end

    # source://ruby-vips//lib/vips/gvalue.rb#296
    def g_value_init(*_arg0); end

    # source://ruby-vips//lib/vips/gvalue.rb#302
    def g_value_set_boolean(*_arg0); end

    # source://ruby-vips//lib/vips/gvalue.rb#305
    def g_value_set_double(*_arg0); end

    # source://ruby-vips//lib/vips/gvalue.rb#306
    def g_value_set_enum(*_arg0); end

    # source://ruby-vips//lib/vips/gvalue.rb#307
    def g_value_set_flags(*_arg0); end

    # source://ruby-vips//lib/vips/gvalue.rb#303
    def g_value_set_int(*_arg0); end

    # source://ruby-vips//lib/vips/gvalue.rb#309
    def g_value_set_object(*_arg0); end

    # source://ruby-vips//lib/vips/gvalue.rb#308
    def g_value_set_string(*_arg0); end

    # source://ruby-vips//lib/vips/gvalue.rb#304
    def g_value_set_uint64(*_arg0); end

    # source://ruby-vips//lib/vips/gvalue.rb#300
    def g_value_unset(*_arg0); end
  end
end

# source://ruby-vips//lib/vips.rb#187
GObject::GBOOL_TYPE = T.let(T.unsafe(nil), Integer)

# source://ruby-vips//lib/vips.rb#190
GObject::GDOUBLE_TYPE = T.let(T.unsafe(nil), Integer)

# source://ruby-vips//lib/vips.rb#191
GObject::GENUM_TYPE = T.let(T.unsafe(nil), Integer)

# source://ruby-vips//lib/vips.rb#192
GObject::GFLAGS_TYPE = T.let(T.unsafe(nil), Integer)

# source://ruby-vips//lib/vips.rb#188
GObject::GINT_TYPE = T.let(T.unsafe(nil), Integer)

# source://ruby-vips//lib/vips.rb#194
GObject::GOBJECT_TYPE = T.let(T.unsafe(nil), Integer)

# source://ruby-vips//lib/vips/gobject.rb#33
class GObject::GObject
  extend ::Forwardable
  extend ::SingleForwardable

  # source://ruby-vips//lib/vips/gobject.rb#75
  def initialize(ptr); end

  # source://ruby-vips//lib/vips/gobject.rb#37
  def [](*args, **_arg1, &block); end

  # source://ruby-vips//lib/vips/gobject.rb#100
  def ffi_managed_struct; end

  # source://ruby-vips//lib/vips/gobject.rb#85
  def ffi_struct; end

  # source://ruby-vips//lib/vips/gobject.rb#91
  def ptr; end

  # source://ruby-vips//lib/vips/gobject.rb#40
  def references; end

  # source://ruby-vips//lib/vips/gobject.rb#37
  def to_ptr(*args, **_arg1, &block); end

  class << self
    # source://ruby-vips//lib/vips/gobject.rb#105
    def ffi_managed_struct; end

    # source://ruby-vips//lib/vips/gobject.rb#94
    def ffi_struct; end

    # source://ruby-vips//lib/vips/gobject.rb#38
    def ptr(*args, **_arg1, &block); end
  end
end

# source://ruby-vips//lib/vips/gobject.rb#43
module GObject::GObject::GObjectLayout
  class << self
    # source://ruby-vips//lib/vips/gobject.rb#44
    def included(base); end
  end
end

# source://ruby-vips//lib/vips/gobject.rb#54
class GObject::GObject::ManagedStruct < ::FFI::ManagedStruct
  include ::GObject::GObject::GObjectLayout

  class << self
    # source://ruby-vips//lib/vips/gobject.rb#57
    def release(ptr); end
  end
end

# source://ruby-vips//lib/vips/gobject.rb#66
class GObject::GObject::Struct < ::FFI::Struct
  include ::GObject::GObject::GObjectLayout
end

# source://ruby-vips//lib/vips/gobject.rb#111
class GObject::GParamSpec < ::FFI::Struct; end

# source://ruby-vips//lib/vips/gobject.rb#120
class GObject::GParamSpecPtr < ::FFI::Struct; end

# source://ruby-vips//lib/vips.rb#193
GObject::GSTR_TYPE = T.let(T.unsafe(nil), Integer)

# source://ruby-vips//lib/vips.rb#189
GObject::GUINT64_TYPE = T.let(T.unsafe(nil), Integer)

# source://ruby-vips//lib/vips/gvalue.rb#23
class GObject::GValue < ::FFI::ManagedStruct
  # source://ruby-vips//lib/vips/gvalue.rb#209
  def get; end

  # source://ruby-vips//lib/vips/gvalue.rb#116
  def init(gtype); end

  # source://ruby-vips//lib/vips/gvalue.rb#124
  def set(value); end

  # source://ruby-vips//lib/vips/gvalue.rb#291
  def unset; end

  class << self
    # source://ruby-vips//lib/vips/gvalue.rb#100
    def alloc; end

    # source://ruby-vips//lib/vips/gvalue.rb#28
    def enum_from_nick(gtype, value); end

    # source://ruby-vips//lib/vips/gvalue.rb#51
    def flags_from_nick(gtype, value); end

    # source://ruby-vips//lib/vips/gvalue.rb#45
    def from_nick(gtype, value); end

    # source://ruby-vips//lib/vips/gvalue.rb#90
    def release(ptr); end

    # source://ruby-vips//lib/vips/gvalue.rb#81
    def to_nick(gtype, enum_value); end
  end
end

class Object < ::BasicObject
  include ::Kernel
  include ::PP::ObjectMixin

  private

  # source://ruby-vips//lib/vips.rb#26
  def library_name(name, abi_number); end
end

# source://ruby-vips//lib/vips.rb#43
module Vips
  extend ::FFI::Library

  # source://ruby-vips//lib/vips.rb#49
  def g_malloc(*_arg0); end

  # source://ruby-vips//lib/vips/image.rb#62
  def nickname_find(*_arg0); end

  # source://ruby-vips//lib/vips/object.rb#161
  def type_find(*_arg0); end

  # source://ruby-vips//lib/vips.rb#814
  def version(*_arg0); end

  # source://ruby-vips//lib/vips.rb#815
  def version_string(*_arg0); end

  # source://ruby-vips//lib/vips/image.rb#50
  def vips_addalpha(*args); end

  # source://ruby-vips//lib/vips/operation.rb#29
  def vips_argument_map(*_arg0); end

  # source://ruby-vips//lib/vips/object.rb#14
  def vips_band_format_get_type(*_arg0); end

  # source://ruby-vips//lib/vips/image.rb#59
  def vips_band_format_iscomplex(*_arg0); end

  # source://ruby-vips//lib/vips/image.rb#60
  def vips_band_format_isfloat(*_arg0); end

  # source://ruby-vips//lib/vips/object.rb#33
  def vips_blend_mode_get_type(*_arg0); end

  # source://ruby-vips//lib/vips.rb#826
  def vips_block_untrusted_set(*_arg0); end

  # source://ruby-vips//lib/vips.rb#702
  def vips_cache_drop_all(*_arg0); end

  # source://ruby-vips//lib/vips.rb#695
  def vips_cache_get_max(*_arg0); end

  # source://ruby-vips//lib/vips.rb#697
  def vips_cache_get_max_files(*_arg0); end

  # source://ruby-vips//lib/vips.rb#696
  def vips_cache_get_max_mem(*_arg0); end

  # source://ruby-vips//lib/vips/operation.rb#20
  def vips_cache_operation_build(*_arg0); end

  # source://ruby-vips//lib/vips.rb#701
  def vips_cache_print(*_arg0); end

  # source://ruby-vips//lib/vips.rb#698
  def vips_cache_set_max(*_arg0); end

  # source://ruby-vips//lib/vips.rb#700
  def vips_cache_set_max_files(*_arg0); end

  # source://ruby-vips//lib/vips.rb#699
  def vips_cache_set_max_mem(*_arg0); end

  # source://ruby-vips//lib/vips/object.rb#16
  def vips_coding_get_type(*_arg0); end

  # source://ruby-vips//lib/vips.rb#673
  def vips_concurrency_get(*_arg0); end

  # source://ruby-vips//lib/vips.rb#672
  def vips_concurrency_set(*_arg0); end

  # source://ruby-vips//lib/vips/connection.rb#11
  def vips_connection_filename(*_arg0); end

  # source://ruby-vips//lib/vips/connection.rb#12
  def vips_connection_nick(*_arg0); end

  # source://ruby-vips//lib/vips/object.rb#126
  def vips_enum_from_nick(*_arg0); end

  # source://ruby-vips//lib/vips/object.rb#127
  def vips_enum_nick(*_arg0); end

  # source://ruby-vips//lib/vips.rb#628
  def vips_error_buffer(*_arg0); end

  # source://ruby-vips//lib/vips.rb#629
  def vips_error_clear(*_arg0); end

  # source://ruby-vips//lib/vips.rb#630
  def vips_error_freeze(*_arg0); end

  # source://ruby-vips//lib/vips.rb#631
  def vips_error_thaw(*_arg0); end

  # source://ruby-vips//lib/vips/image.rb#20
  def vips_filename_get_filename(*_arg0); end

  # source://ruby-vips//lib/vips/image.rb#21
  def vips_filename_get_options(*_arg0); end

  # source://ruby-vips//lib/vips/object.rb#128
  def vips_flags_from_nick(*_arg0); end

  # source://ruby-vips//lib/vips/image.rb#23
  def vips_foreign_find_load(*_arg0); end

  # source://ruby-vips//lib/vips/image.rb#25
  def vips_foreign_find_load_buffer(*_arg0); end

  # source://ruby-vips//lib/vips/image.rb#29
  def vips_foreign_find_load_source(*_arg0); end

  # source://ruby-vips//lib/vips/image.rb#24
  def vips_foreign_find_save(*_arg0); end

  # source://ruby-vips//lib/vips/image.rb#26
  def vips_foreign_find_save_buffer(*_arg0); end

  # source://ruby-vips//lib/vips/image.rb#30
  def vips_foreign_find_save_target(*_arg0); end

  # source://ruby-vips//lib/vips.rb#680
  def vips_foreign_get_suffixes(*_arg0); end

  # source://ruby-vips//lib/vips/image.rb#15
  def vips_image_copy_memory(*_arg0); end

  # source://ruby-vips//lib/vips/image.rb#37
  def vips_image_get(*_arg0); end

  # source://ruby-vips//lib/vips/image.rb#42
  def vips_image_get_bands(*_arg0); end

  # source://ruby-vips//lib/vips/image.rb#45
  def vips_image_get_fields(*_arg0); end

  # source://ruby-vips//lib/vips/image.rb#41
  def vips_image_get_height(*_arg0); end

  # source://ruby-vips//lib/vips/image.rb#36
  def vips_image_get_typeof(*_arg0); end

  # source://ruby-vips//lib/vips/image.rb#40
  def vips_image_get_width(*_arg0); end

  # source://ruby-vips//lib/vips/image.rb#46
  def vips_image_hasalpha(*_arg0); end

  # source://ruby-vips//lib/vips/image.rb#64
  def vips_image_new_from_memory(*_arg0); end

  # source://ruby-vips//lib/vips/image.rb#65
  def vips_image_new_from_memory_copy(*_arg0); end

  # source://ruby-vips//lib/vips/image.rb#12
  def vips_image_new_matrix_from_array(*_arg0); end

  # source://ruby-vips//lib/vips/image.rb#57
  def vips_image_remove(*_arg0); end

  # source://ruby-vips//lib/vips/image.rb#55
  def vips_image_set(*_arg0); end

  # source://ruby-vips//lib/vips/image.rb#18
  def vips_image_set_kill(*_arg0); end

  # source://ruby-vips//lib/vips/image.rb#17
  def vips_image_set_progress(*_arg0); end

  # source://ruby-vips//lib/vips/image.rb#33
  def vips_image_write_to_memory(*_arg0); end

  # source://ruby-vips//lib/vips.rb#660
  def vips_init(*_arg0); end

  # source://ruby-vips//lib/vips/interpolate.rb#2
  def vips_interpolate_new(*_arg0); end

  # source://ruby-vips//lib/vips/object.rb#15
  def vips_interpretation_get_type(*_arg0); end

  # source://ruby-vips//lib/vips.rb#669
  def vips_leak_set(*_arg0); end

  # source://ruby-vips//lib/vips/object.rb#332
  def vips_object_get_argument(*_arg0); end

  # source://ruby-vips//lib/vips/object.rb#346
  def vips_object_get_description(*_arg0); end

  # source://ruby-vips//lib/vips/object.rb#339
  def vips_object_print_all(*_arg0); end

  # source://ruby-vips//lib/vips/object.rb#341
  def vips_object_set_from_string(*_arg0); end

  # source://ruby-vips//lib/vips/operation.rb#22
  def vips_object_unref_outputs(*_arg0); end

  # source://ruby-vips//lib/vips.rb#827
  def vips_operation_block_set(*_arg0); end

  # source://ruby-vips//lib/vips/operation.rb#43
  def vips_operation_get_flags(*_arg0); end

  # source://ruby-vips//lib/vips/operation.rb#13
  def vips_operation_new(*_arg0); end

  # source://ruby-vips//lib/vips/region.rb#13
  def vips_region_fetch(*_arg0); end

  # source://ruby-vips//lib/vips/region.rb#15
  def vips_region_height(*_arg0); end

  # source://ruby-vips//lib/vips/region.rb#10
  def vips_region_new(*_arg0); end

  # source://ruby-vips//lib/vips/region.rb#14
  def vips_region_width(*_arg0); end

  # source://ruby-vips//lib/vips/sourcecustom.rb#11
  def vips_source_custom_new(*_arg0); end

  # source://ruby-vips//lib/vips/source.rb#11
  def vips_source_new_from_descriptor(*_arg0); end

  # source://ruby-vips//lib/vips/source.rb#12
  def vips_source_new_from_file(*_arg0); end

  # source://ruby-vips//lib/vips/source.rb#13
  def vips_source_new_from_memory(*_arg0); end

  # source://ruby-vips//lib/vips/targetcustom.rb#11
  def vips_target_custom_new(*_arg0); end

  # source://ruby-vips//lib/vips/target.rb#11
  def vips_target_new_to_descriptor(*_arg0); end

  # source://ruby-vips//lib/vips/target.rb#12
  def vips_target_new_to_file(*_arg0); end

  # source://ruby-vips//lib/vips/target.rb#13
  def vips_target_new_to_memory(*_arg0); end

  # source://ruby-vips//lib/vips.rb#693
  def vips_tracked_get_allocs(*_arg0); end

  # source://ruby-vips//lib/vips.rb#694
  def vips_tracked_get_files(*_arg0); end

  # source://ruby-vips//lib/vips.rb#691
  def vips_tracked_get_mem(*_arg0); end

  # source://ruby-vips//lib/vips.rb#692
  def vips_tracked_get_mem_highwater(*_arg0); end

  # source://ruby-vips//lib/vips/object.rb#344
  def vips_type_map(*_arg0); end

  # source://ruby-vips//lib/vips/object.rb#152
  def vips_value_get_array_double(*_arg0); end

  # source://ruby-vips//lib/vips/object.rb#156
  def vips_value_get_array_image(*_arg0); end

  # source://ruby-vips//lib/vips/object.rb#154
  def vips_value_get_array_int(*_arg0); end

  # source://ruby-vips//lib/vips/object.rb#158
  def vips_value_get_blob(*_arg0); end

  # source://ruby-vips//lib/vips/object.rb#150
  def vips_value_get_ref_string(*_arg0); end

  # source://ruby-vips//lib/vips/object.rb#132
  def vips_value_set_array_double(*_arg0); end

  # source://ruby-vips//lib/vips/object.rb#136
  def vips_value_set_array_image(*_arg0); end

  # source://ruby-vips//lib/vips/object.rb#134
  def vips_value_set_array_int(*_arg0); end

  # source://ruby-vips//lib/vips/object.rb#139
  def vips_value_set_blob(*_arg0); end

  # source://ruby-vips//lib/vips/object.rb#130
  def vips_value_set_ref_string(*_arg0); end

  # source://ruby-vips//lib/vips.rb#671
  def vips_vector_isenabled(*_arg0); end

  # source://ruby-vips//lib/vips.rb#670
  def vips_vector_set_enabled(*_arg0); end

  class << self
    # source://ruby-vips//lib/vips.rb#818
    def at_least_libvips?(x, y); end

    # source://ruby-vips//lib/vips.rb#845
    def block(operation_name, state); end

    # source://ruby-vips//lib/vips.rb#831
    def block_untrusted(state); end

    # source://ruby-vips//lib/vips.rb#767
    def cache_drop_all; end

    # source://ruby-vips//lib/vips.rb#725
    def cache_max; end

    # source://ruby-vips//lib/vips.rb#735
    def cache_max_files; end

    # source://ruby-vips//lib/vips.rb#730
    def cache_max_mem; end

    # source://ruby-vips//lib/vips.rb#762
    def cache_print; end

    # source://ruby-vips//lib/vips.rb#741
    def cache_set_max(size); end

    # source://ruby-vips//lib/vips.rb#756
    def cache_set_max_files(size); end

    # source://ruby-vips//lib/vips.rb#748
    def cache_set_max_mem(size); end

    # source://ruby-vips//lib/vips.rb#773
    def concurrency; end

    # source://ruby-vips//lib/vips.rb#778
    def concurrency_default; end

    # source://ruby-vips//lib/vips.rb#784
    def concurrency_set(n); end

    # source://ruby-vips//lib/vips.rb#49
    def g_malloc(*_arg0); end

    # source://ruby-vips//lib/vips.rb#853
    def get_suffixes; end

    # source://ruby-vips//lib/vips.rb#687
    def leak_set(leak); end

    # source://ruby-vips//lib/vips/image.rb#62
    def nickname_find(*_arg0); end

    # source://ruby-vips//lib/vips/image.rb#68
    def p2str(pointer); end

    # source://ruby-vips//lib/vips.rb#808
    def set_debug(debug); end

    # source://ruby-vips//lib/vips.rb#715
    def tracked_allocs; end

    # source://ruby-vips//lib/vips.rb#720
    def tracked_files; end

    # source://ruby-vips//lib/vips.rb#705
    def tracked_mem; end

    # source://ruby-vips//lib/vips.rb#710
    def tracked_mem_highwater; end

    # source://ruby-vips//lib/vips/object.rb#161
    def type_find(*_arg0); end

    # source://ruby-vips//lib/vips.rb#55
    def unified?; end

    # source://ruby-vips//lib/vips.rb#793
    def vector?; end

    # source://ruby-vips//lib/vips.rb#800
    def vector_set(enabled); end

    # source://ruby-vips//lib/vips.rb#814
    def version(*_arg0); end

    # source://ruby-vips//lib/vips.rb#815
    def version_string(*_arg0); end

    # source://ruby-vips//lib/vips/image.rb#50
    def vips_addalpha(*args); end

    # source://ruby-vips//lib/vips/operation.rb#29
    def vips_argument_map(*_arg0); end

    # source://ruby-vips//lib/vips/object.rb#14
    def vips_band_format_get_type(*_arg0); end

    # source://ruby-vips//lib/vips/image.rb#59
    def vips_band_format_iscomplex(*_arg0); end

    # source://ruby-vips//lib/vips/image.rb#60
    def vips_band_format_isfloat(*_arg0); end

    # source://ruby-vips//lib/vips/object.rb#33
    def vips_blend_mode_get_type(*_arg0); end

    # source://ruby-vips//lib/vips.rb#826
    def vips_block_untrusted_set(*_arg0); end

    # source://ruby-vips//lib/vips.rb#702
    def vips_cache_drop_all(*_arg0); end

    # source://ruby-vips//lib/vips.rb#695
    def vips_cache_get_max(*_arg0); end

    # source://ruby-vips//lib/vips.rb#697
    def vips_cache_get_max_files(*_arg0); end

    # source://ruby-vips//lib/vips.rb#696
    def vips_cache_get_max_mem(*_arg0); end

    # source://ruby-vips//lib/vips/operation.rb#20
    def vips_cache_operation_build(*_arg0); end

    # source://ruby-vips//lib/vips.rb#701
    def vips_cache_print(*_arg0); end

    # source://ruby-vips//lib/vips.rb#698
    def vips_cache_set_max(*_arg0); end

    # source://ruby-vips//lib/vips.rb#700
    def vips_cache_set_max_files(*_arg0); end

    # source://ruby-vips//lib/vips.rb#699
    def vips_cache_set_max_mem(*_arg0); end

    # source://ruby-vips//lib/vips/object.rb#16
    def vips_coding_get_type(*_arg0); end

    # source://ruby-vips//lib/vips.rb#673
    def vips_concurrency_get(*_arg0); end

    # source://ruby-vips//lib/vips.rb#672
    def vips_concurrency_set(*_arg0); end

    # source://ruby-vips//lib/vips/connection.rb#11
    def vips_connection_filename(*_arg0); end

    # source://ruby-vips//lib/vips/connection.rb#12
    def vips_connection_nick(*_arg0); end

    # source://ruby-vips//lib/vips/object.rb#126
    def vips_enum_from_nick(*_arg0); end

    # source://ruby-vips//lib/vips/object.rb#127
    def vips_enum_nick(*_arg0); end

    # source://ruby-vips//lib/vips.rb#628
    def vips_error_buffer(*_arg0); end

    # source://ruby-vips//lib/vips.rb#629
    def vips_error_clear(*_arg0); end

    # source://ruby-vips//lib/vips.rb#630
    def vips_error_freeze(*_arg0); end

    # source://ruby-vips//lib/vips.rb#631
    def vips_error_thaw(*_arg0); end

    # source://ruby-vips//lib/vips/image.rb#20
    def vips_filename_get_filename(*_arg0); end

    # source://ruby-vips//lib/vips/image.rb#21
    def vips_filename_get_options(*_arg0); end

    # source://ruby-vips//lib/vips/object.rb#128
    def vips_flags_from_nick(*_arg0); end

    # source://ruby-vips//lib/vips/image.rb#23
    def vips_foreign_find_load(*_arg0); end

    # source://ruby-vips//lib/vips/image.rb#25
    def vips_foreign_find_load_buffer(*_arg0); end

    # source://ruby-vips//lib/vips/image.rb#29
    def vips_foreign_find_load_source(*_arg0); end

    # source://ruby-vips//lib/vips/image.rb#24
    def vips_foreign_find_save(*_arg0); end

    # source://ruby-vips//lib/vips/image.rb#26
    def vips_foreign_find_save_buffer(*_arg0); end

    # source://ruby-vips//lib/vips/image.rb#30
    def vips_foreign_find_save_target(*_arg0); end

    # source://ruby-vips//lib/vips.rb#680
    def vips_foreign_get_suffixes(*_arg0); end

    # source://ruby-vips//lib/vips/image.rb#15
    def vips_image_copy_memory(*_arg0); end

    # source://ruby-vips//lib/vips/image.rb#37
    def vips_image_get(*_arg0); end

    # source://ruby-vips//lib/vips/image.rb#42
    def vips_image_get_bands(*_arg0); end

    # source://ruby-vips//lib/vips/image.rb#45
    def vips_image_get_fields(*_arg0); end

    # source://ruby-vips//lib/vips/image.rb#41
    def vips_image_get_height(*_arg0); end

    # source://ruby-vips//lib/vips/image.rb#36
    def vips_image_get_typeof(*_arg0); end

    # source://ruby-vips//lib/vips/image.rb#40
    def vips_image_get_width(*_arg0); end

    # source://ruby-vips//lib/vips/image.rb#46
    def vips_image_hasalpha(*_arg0); end

    # source://ruby-vips//lib/vips/image.rb#64
    def vips_image_new_from_memory(*_arg0); end

    # source://ruby-vips//lib/vips/image.rb#65
    def vips_image_new_from_memory_copy(*_arg0); end

    # source://ruby-vips//lib/vips/image.rb#12
    def vips_image_new_matrix_from_array(*_arg0); end

    # source://ruby-vips//lib/vips/image.rb#57
    def vips_image_remove(*_arg0); end

    # source://ruby-vips//lib/vips/image.rb#55
    def vips_image_set(*_arg0); end

    # source://ruby-vips//lib/vips/image.rb#18
    def vips_image_set_kill(*_arg0); end

    # source://ruby-vips//lib/vips/image.rb#17
    def vips_image_set_progress(*_arg0); end

    # source://ruby-vips//lib/vips/image.rb#33
    def vips_image_write_to_memory(*_arg0); end

    # source://ruby-vips//lib/vips.rb#660
    def vips_init(*_arg0); end

    # source://ruby-vips//lib/vips/interpolate.rb#2
    def vips_interpolate_new(*_arg0); end

    # source://ruby-vips//lib/vips/object.rb#15
    def vips_interpretation_get_type(*_arg0); end

    # source://ruby-vips//lib/vips.rb#669
    def vips_leak_set(*_arg0); end

    # source://ruby-vips//lib/vips/object.rb#332
    def vips_object_get_argument(*_arg0); end

    # source://ruby-vips//lib/vips/object.rb#346
    def vips_object_get_description(*_arg0); end

    # source://ruby-vips//lib/vips/object.rb#339
    def vips_object_print_all(*_arg0); end

    # source://ruby-vips//lib/vips/object.rb#341
    def vips_object_set_from_string(*_arg0); end

    # source://ruby-vips//lib/vips/operation.rb#22
    def vips_object_unref_outputs(*_arg0); end

    # source://ruby-vips//lib/vips.rb#827
    def vips_operation_block_set(*_arg0); end

    # source://ruby-vips//lib/vips/operation.rb#43
    def vips_operation_get_flags(*_arg0); end

    # source://ruby-vips//lib/vips/operation.rb#13
    def vips_operation_new(*_arg0); end

    # source://ruby-vips//lib/vips/region.rb#13
    def vips_region_fetch(*_arg0); end

    # source://ruby-vips//lib/vips/region.rb#15
    def vips_region_height(*_arg0); end

    # source://ruby-vips//lib/vips/region.rb#10
    def vips_region_new(*_arg0); end

    # source://ruby-vips//lib/vips/region.rb#14
    def vips_region_width(*_arg0); end

    # source://ruby-vips//lib/vips/sourcecustom.rb#11
    def vips_source_custom_new(*_arg0); end

    # source://ruby-vips//lib/vips/source.rb#11
    def vips_source_new_from_descriptor(*_arg0); end

    # source://ruby-vips//lib/vips/source.rb#12
    def vips_source_new_from_file(*_arg0); end

    # source://ruby-vips//lib/vips/source.rb#13
    def vips_source_new_from_memory(*_arg0); end

    # source://ruby-vips//lib/vips/targetcustom.rb#11
    def vips_target_custom_new(*_arg0); end

    # source://ruby-vips//lib/vips/target.rb#11
    def vips_target_new_to_descriptor(*_arg0); end

    # source://ruby-vips//lib/vips/target.rb#12
    def vips_target_new_to_file(*_arg0); end

    # source://ruby-vips//lib/vips/target.rb#13
    def vips_target_new_to_memory(*_arg0); end

    # source://ruby-vips//lib/vips.rb#693
    def vips_tracked_get_allocs(*_arg0); end

    # source://ruby-vips//lib/vips.rb#694
    def vips_tracked_get_files(*_arg0); end

    # source://ruby-vips//lib/vips.rb#691
    def vips_tracked_get_mem(*_arg0); end

    # source://ruby-vips//lib/vips.rb#692
    def vips_tracked_get_mem_highwater(*_arg0); end

    # source://ruby-vips//lib/vips/object.rb#344
    def vips_type_map(*_arg0); end

    # source://ruby-vips//lib/vips/object.rb#152
    def vips_value_get_array_double(*_arg0); end

    # source://ruby-vips//lib/vips/object.rb#156
    def vips_value_get_array_image(*_arg0); end

    # source://ruby-vips//lib/vips/object.rb#154
    def vips_value_get_array_int(*_arg0); end

    # source://ruby-vips//lib/vips/object.rb#158
    def vips_value_get_blob(*_arg0); end

    # source://ruby-vips//lib/vips/object.rb#150
    def vips_value_get_ref_string(*_arg0); end

    # source://ruby-vips//lib/vips/object.rb#132
    def vips_value_set_array_double(*_arg0); end

    # source://ruby-vips//lib/vips/object.rb#136
    def vips_value_set_array_image(*_arg0); end

    # source://ruby-vips//lib/vips/object.rb#134
    def vips_value_set_array_int(*_arg0); end

    # source://ruby-vips//lib/vips/object.rb#139
    def vips_value_set_blob(*_arg0); end

    # source://ruby-vips//lib/vips/object.rb#130
    def vips_value_set_ref_string(*_arg0); end

    # source://ruby-vips//lib/vips.rb#671
    def vips_vector_isenabled(*_arg0); end

    # source://ruby-vips//lib/vips.rb#670
    def vips_vector_set_enabled(*_arg0); end
  end
end

# source://ruby-vips//lib/vips/object.rb#295
Vips::ARGUMENT_CONSTRUCT = T.let(T.unsafe(nil), Integer)

# source://ruby-vips//lib/vips/object.rb#300
Vips::ARGUMENT_DEPRECATED = T.let(T.unsafe(nil), Integer)

# source://ruby-vips//lib/vips/object.rb#303
Vips::ARGUMENT_FLAGS = T.let(T.unsafe(nil), Hash)

# source://ruby-vips//lib/vips/object.rb#298
Vips::ARGUMENT_INPUT = T.let(T.unsafe(nil), Integer)

# source://ruby-vips//lib/vips/object.rb#301
Vips::ARGUMENT_MODIFY = T.let(T.unsafe(nil), Integer)

# source://ruby-vips//lib/vips/object.rb#299
Vips::ARGUMENT_OUTPUT = T.let(T.unsafe(nil), Integer)

# source://ruby-vips//lib/vips/object.rb#294
Vips::ARGUMENT_REQUIRED = T.let(T.unsafe(nil), Integer)

# source://ruby-vips//lib/vips/object.rb#297
Vips::ARGUMENT_SET_ALWAYS = T.let(T.unsafe(nil), Integer)

# source://ruby-vips//lib/vips/object.rb#296
Vips::ARGUMENT_SET_ONCE = T.let(T.unsafe(nil), Integer)

# source://ruby-vips//lib/vips/object.rb#23
Vips::ARRAY_DOUBLE_TYPE = T.let(T.unsafe(nil), Integer)

# source://ruby-vips//lib/vips/object.rb#24
Vips::ARRAY_IMAGE_TYPE = T.let(T.unsafe(nil), Integer)

# source://ruby-vips//lib/vips/object.rb#22
Vips::ARRAY_INT_TYPE = T.let(T.unsafe(nil), Integer)

# source://ruby-vips//lib/vips/object.rb#284
class Vips::Argument < ::FFI::Struct; end

# source://ruby-vips//lib/vips/object.rb#314
class Vips::ArgumentClass < ::Vips::Argument; end

# source://ruby-vips//lib/vips/object.rb#322
class Vips::ArgumentClassPtr < ::FFI::Struct; end

# source://ruby-vips//lib/vips/object.rb#288
class Vips::ArgumentInstance < ::Vips::Argument; end

# source://ruby-vips//lib/vips/object.rb#326
class Vips::ArgumentInstancePtr < ::FFI::Struct; end

# source://ruby-vips//lib/vips/object.rb#28
Vips::BAND_FORMAT_TYPE = T.let(T.unsafe(nil), Integer)

# source://ruby-vips//lib/vips/object.rb#34
Vips::BLEND_MODE_TYPE = T.let(T.unsafe(nil), Integer)

# source://ruby-vips//lib/vips/object.rb#26
Vips::BLOB_TYPE = T.let(T.unsafe(nil), Integer)

# source://ruby-vips//lib/vips/object.rb#30
Vips::CODING_TYPE = T.let(T.unsafe(nil), Integer)

# source://ruby-vips//lib/vips/connection.rb#16
class Vips::Connection < ::Vips::Object
  # source://ruby-vips//lib/vips/connection.rb#36
  def filename; end

  # source://ruby-vips//lib/vips/connection.rb#42
  def nick; end
end

# source://ruby-vips//lib/vips/connection.rb#18
module Vips::Connection::ConnectionLayout
  class << self
    # source://ruby-vips//lib/vips/connection.rb#19
    def included(base); end
  end
end

# source://ruby-vips//lib/vips/connection.rb#31
class Vips::Connection::ManagedStruct < ::Vips::Object::ManagedStruct
  include ::Vips::Connection::ConnectionLayout
end

# source://ruby-vips//lib/vips/connection.rb#27
class Vips::Connection::Struct < ::Vips::Object::Struct
  include ::Vips::Connection::ConnectionLayout
end

# source://ruby-vips//lib/vips.rb#676
Vips::DEFAULT_CONCURRENCY = T.let(T.unsafe(nil), Integer)

# source://ruby-vips//lib/vips.rb#634
class Vips::Error < ::RuntimeError
  # source://ruby-vips//lib/vips.rb#637
  def initialize(msg = T.unsafe(nil)); end

  # source://ruby-vips//lib/vips.rb#651
  def to_s; end
end

# source://ruby-vips//lib/vips/object.rb#21
Vips::IMAGE_TYPE = T.let(T.unsafe(nil), Integer)

# source://ruby-vips//lib/vips/object.rb#29
Vips::INTERPRETATION_TYPE = T.let(T.unsafe(nil), Integer)

# source://ruby-vips//lib/vips/image.rb#78
class Vips::Image < ::Vips::Object
  # source://ruby-vips//lib/vips/image.rb#1100
  def !; end

  # source://ruby-vips//lib/vips/image.rb#1174
  def !=(other); end

  # source://ruby-vips//lib/vips/image.rb#1044
  def %(other); end

  # source://ruby-vips//lib/vips/image.rb#1085
  def &(other); end

  # source://ruby-vips//lib/vips/image.rb#1026
  def *(other); end

  # source://ruby-vips//lib/vips/image.rb#1053
  def **(other); end

  # source://ruby-vips//lib/vips/image.rb#1008
  def +(other); end

  # source://ruby-vips//lib/vips/image.rb#1112
  def +@; end

  # source://ruby-vips//lib/vips/image.rb#1017
  def -(other); end

  # source://ruby-vips//lib/vips/image.rb#1119
  def -@; end

  # source://ruby-vips//lib/vips/image.rb#1035
  def /(other); end

  # source://ruby-vips//lib/vips/image.rb#1127
  def <(other); end

  # source://ruby-vips//lib/vips/image.rb#1061
  def <<(other); end

  # source://ruby-vips//lib/vips/image.rb#1136
  def <=(other); end

  # source://ruby-vips//lib/vips/image.rb#1161
  def ==(other); end

  # source://ruby-vips//lib/vips/image.rb#1144
  def >(other); end

  # source://ruby-vips//lib/vips/image.rb#1153
  def >=(other); end

  # source://ruby-vips//lib/vips/image.rb#1069
  def >>(other); end

  # source://ruby-vips//lib/vips/image.rb#1187
  def [](index); end

  # source://ruby-vips//lib/vips/image.rb#1093
  def ^(other); end

  # source://ruby-vips//lib/vips/image.rb#1449
  def acos; end

  # source://ruby-vips//lib/vips/image.rb#1491
  def acosh; end

  # source://ruby-vips//lib/vips/image.rb#974
  def add_alpha; end

  # source://ruby-vips//lib/vips/image.rb#1442
  def asin; end

  # source://ruby-vips//lib/vips/image.rb#1484
  def asinh; end

  # source://ruby-vips//lib/vips/image.rb#1456
  def atan; end

  # source://ruby-vips//lib/vips/image.rb#1498
  def atanh; end

  # source://ruby-vips//lib/vips/image.rb#1258
  def bandand; end

  # source://ruby-vips//lib/vips/image.rb#1272
  def bandeor; end

  # source://ruby-vips//lib/vips/image.rb#1287
  def bandjoin(other); end

  # source://ruby-vips//lib/vips/image.rb#1265
  def bandor; end

  # source://ruby-vips//lib/vips/image.rb#875
  def bands; end

  # source://ruby-vips//lib/vips/image.rb#1279
  def bandsplit; end

  # source://ruby-vips//lib/vips/image.rb#1244
  def ceil; end

  # source://ruby-vips//lib/vips/image.rb#896
  def coding; end

  # source://ruby-vips//lib/vips/image.rb#1313
  def composite(overlay, mode, **opts); end

  # source://ruby-vips//lib/vips/image.rb#1406
  def conj; end

  # source://ruby-vips//lib/vips/image.rb#990
  def copy_memory; end

  # source://ruby-vips//lib/vips/image.rb#1428
  def cos; end

  # source://ruby-vips//lib/vips/image.rb#1470
  def cosh; end

  # source://ruby-vips//lib/vips/image.rb#1414
  def cross_phase(other); end

  # source://ruby-vips//lib/vips/image.rb#1564
  def dilate(mask); end

  # source://ruby-vips//lib/vips/image.rb#1000
  def draw_point(ink, left, top, **opts); end

  # source://ruby-vips//lib/vips/image.rb#1552
  def erode(mask); end

  # source://ruby-vips//lib/vips/image.rb#1519
  def exp; end

  # source://ruby-vips//lib/vips/image.rb#1526
  def exp10; end

  # source://ruby-vips//lib/vips/image.rb#903
  def filename; end

  # source://ruby-vips//lib/vips/image.rb#1533
  def fliphor; end

  # source://ruby-vips//lib/vips/image.rb#1540
  def flipver; end

  # source://ruby-vips//lib/vips/image.rb#1237
  def floor; end

  # source://ruby-vips//lib/vips/image.rb#882
  def format; end

  # source://ruby-vips//lib/vips/image.rb#763
  def get(name); end

  # source://ruby-vips//lib/vips/image.rb#782
  def get_fields; end

  # source://ruby-vips//lib/vips/image.rb#739
  def get_typeof(name); end

  # source://ruby-vips//lib/vips/image.rb#847
  def get_value(name); end

  # source://ruby-vips//lib/vips/image.rb#964
  def has_alpha?; end

  # source://ruby-vips//lib/vips/image.rb#868
  def height; end

  # source://ruby-vips//lib/vips/image.rb#1598
  def ifthenelse(th, el, **opts); end

  # source://ruby-vips//lib/vips/image.rb#1368
  def imag; end

  # source://ruby-vips//lib/vips/image.rb#194
  def inspect; end

  # source://ruby-vips//lib/vips/image.rb#889
  def interpretation; end

  # source://ruby-vips//lib/vips/image.rb#1505
  def log; end

  # source://ruby-vips//lib/vips/image.rb#1512
  def log10; end

  # source://ruby-vips//lib/vips/image.rb#1332
  def maxpos; end

  # source://ruby-vips//lib/vips/image.rb#1354
  def median(size = T.unsafe(nil)); end

  # source://ruby-vips//lib/vips/image.rb#228
  def method_missing(name, *args, **options); end

  # source://ruby-vips//lib/vips/image.rb#1343
  def minpos; end

  # source://ruby-vips//lib/vips/image.rb#815
  def mutate; end

  # source://ruby-vips//lib/vips/image.rb#555
  def new_from_image(value); end

  # source://ruby-vips//lib/vips/image.rb#947
  def offset; end

  # source://ruby-vips//lib/vips/image.rb#79
  def parent_get_typeof(name); end

  # source://ruby-vips//lib/vips/image.rb#1381
  def polar; end

  # source://ruby-vips//lib/vips/image.rb#1361
  def real; end

  # source://ruby-vips//lib/vips/image.rb#1394
  def rect; end

  # source://ruby-vips//lib/vips/image.rb#842
  def remove(name); end

  # source://ruby-vips//lib/vips/image.rb#198
  def respond_to?(name, include_all = T.unsafe(nil)); end

  # source://ruby-vips//lib/vips/image.rb#1251
  def rint; end

  # source://ruby-vips//lib/vips/image.rb#1578
  def rot180; end

  # source://ruby-vips//lib/vips/image.rb#1585
  def rot270; end

  # source://ruby-vips//lib/vips/image.rb#1571
  def rot90; end

  # source://ruby-vips//lib/vips/image.rb#938
  def scale; end

  # source://ruby-vips//lib/vips/image.rb#1616
  def scaleimage(**opts); end

  # source://ruby-vips//lib/vips/image.rb#835
  def set(name, value); end

  # source://ruby-vips//lib/vips/image.rb#729
  def set_kill(kill); end

  # source://ruby-vips//lib/vips/image.rb#718
  def set_progress(state); end

  # source://ruby-vips//lib/vips/image.rb#824
  def set_type(gtype, name, value); end

  # source://ruby-vips//lib/vips/image.rb#854
  def set_value(name, value); end

  # source://ruby-vips//lib/vips/image.rb#1421
  def sin; end

  # source://ruby-vips//lib/vips/image.rb#1463
  def sinh; end

  # source://ruby-vips//lib/vips/image.rb#956
  def size; end

  # source://ruby-vips//lib/vips/image.rb#1435
  def tan; end

  # source://ruby-vips//lib/vips/image.rb#1477
  def tanh; end

  # source://ruby-vips//lib/vips/image.rb#1230
  def to_a; end

  # source://ruby-vips//lib/vips/image.rb#1201
  def to_enum; end

  # source://ruby-vips//lib/vips/image.rb#861
  def width; end

  # source://ruby-vips//lib/vips/image.rb#629
  def write_to_buffer(format_string, **opts); end

  # source://ruby-vips//lib/vips/image.rb#591
  def write_to_file(name, **opts); end

  # source://ruby-vips//lib/vips/image.rb#700
  def write_to_memory; end

  # source://ruby-vips//lib/vips/image.rb#686
  def write_to_target(target, format_string, **opts); end

  # source://ruby-vips//lib/vips/image.rb#910
  def xoffset; end

  # source://ruby-vips//lib/vips/image.rb#924
  def xres; end

  # source://ruby-vips//lib/vips/image.rb#917
  def yoffset; end

  # source://ruby-vips//lib/vips/image.rb#931
  def yres; end

  # source://ruby-vips//lib/vips/image.rb#1077
  def |(other); end

  # source://ruby-vips//lib/vips/image.rb#1107
  def ~; end

  private

  # source://ruby-vips//lib/vips/image.rb#156
  def call_enum(name, other, enum); end

  # source://ruby-vips//lib/vips/image.rb#209
  def respond_to_missing?(name, include_all = T.unsafe(nil)); end

  # source://ruby-vips//lib/vips/image.rb#180
  def write_gc; end

  class << self
    # source://ruby-vips//lib/vips/image.rb#116
    def complex?(format); end

    # source://ruby-vips//lib/vips/image.rb#121
    def float?(format); end

    # source://ruby-vips//lib/vips/image.rb#471
    def matrix_from_array(width, height, array); end

    # source://ruby-vips//lib/vips/image.rb#233
    def method_missing(name, *args, **options); end

    # source://ruby-vips//lib/vips/image.rb#506
    def new_from_array(array, scale = T.unsafe(nil), offset = T.unsafe(nil)); end

    # source://ruby-vips//lib/vips/image.rb#317
    def new_from_buffer(data, option_string, **opts); end

    # source://ruby-vips//lib/vips/image.rb#273
    def new_from_file(name, **opts); end

    # source://ruby-vips//lib/vips/image.rb#365
    def new_from_memory(data, width, height, bands, format); end

    # source://ruby-vips//lib/vips/image.rb#407
    def new_from_memory_copy(data, width, height, bands, format); end

    # source://ruby-vips//lib/vips/image.rb#457
    def new_from_source(source, option_string, **opts); end

    # source://ruby-vips//lib/vips/image.rb#216
    def respond_to_missing?(name, include_all = T.unsafe(nil)); end

    # source://ruby-vips//lib/vips/image.rb#129
    def run_cmplx(image, &block); end

    # source://ruby-vips//lib/vips/image.rb#112
    def smap(x, &block); end
  end
end

# source://ruby-vips//lib/vips/image.rb#106
class Vips::Image::GenericPtr < ::FFI::Struct; end

# source://ruby-vips//lib/vips/image.rb#89
module Vips::Image::ImageLayout
  class << self
    # source://ruby-vips//lib/vips/image.rb#90
    def included(base); end
  end
end

# source://ruby-vips//lib/vips/image.rb#102
class Vips::Image::ManagedStruct < ::Vips::Object::ManagedStruct
  include ::Vips::Image::ImageLayout
end

# source://ruby-vips//lib/vips/image.rb#98
class Vips::Image::Struct < ::Vips::Object::Struct
  include ::Vips::Image::ImageLayout
end

# source://ruby-vips//lib/vips/image.rb#83
Vips::Image::UNKNOWN_POINTER_SIZE = T.let(T.unsafe(nil), Integer)

# source://ruby-vips//lib/vips/object.rb#146
class Vips::IntStruct < ::FFI::Struct; end

# source://ruby-vips//lib/vips/interpolate.rb#31
class Vips::Interpolate < ::Vips::Object
  # source://ruby-vips//lib/vips/interpolate.rb#50
  def initialize(name); end
end

# source://ruby-vips//lib/vips/interpolate.rb#33
module Vips::Interpolate::InterpolateLayout
  class << self
    # source://ruby-vips//lib/vips/interpolate.rb#34
    def included(base); end
  end
end

# source://ruby-vips//lib/vips/interpolate.rb#46
class Vips::Interpolate::ManagedStruct < ::Vips::Object::ManagedStruct
  include ::Vips::Interpolate::InterpolateLayout
end

# source://ruby-vips//lib/vips/interpolate.rb#42
class Vips::Interpolate::Struct < ::Vips::Object::Struct
  include ::Vips::Interpolate::InterpolateLayout
end

# source://ruby-vips//lib/vips/operation.rb#48
class Vips::Introspect
  # source://ruby-vips//lib/vips/operation.rb#56
  def initialize(name); end

  # source://ruby-vips//lib/vips/operation.rb#140
  def add_yard_introspection(name); end

  # source://ruby-vips//lib/vips/operation.rb#49
  def args; end

  # source://ruby-vips//lib/vips/operation.rb#49
  def description; end

  # source://ruby-vips//lib/vips/operation.rb#49
  def destructive; end

  # source://ruby-vips//lib/vips/operation.rb#49
  def doc_optional_input; end

  # source://ruby-vips//lib/vips/operation.rb#49
  def doc_optional_output; end

  # source://ruby-vips//lib/vips/operation.rb#49
  def flags; end

  # source://ruby-vips//lib/vips/operation.rb#49
  def member_x; end

  # source://ruby-vips//lib/vips/operation.rb#49
  def method_args; end

  # source://ruby-vips//lib/vips/operation.rb#49
  def name; end

  # source://ruby-vips//lib/vips/operation.rb#49
  def optional_input; end

  # source://ruby-vips//lib/vips/operation.rb#49
  def optional_output; end

  # source://ruby-vips//lib/vips/operation.rb#49
  def required_input; end

  # source://ruby-vips//lib/vips/operation.rb#49
  def required_output; end

  # source://ruby-vips//lib/vips/operation.rb#49
  def vips_name; end

  class << self
    # source://ruby-vips//lib/vips/operation.rb#183
    def get(name); end

    # source://ruby-vips//lib/vips/operation.rb#187
    def get_yard(name); end
  end
end

# source://ruby-vips//lib/vips.rb#872
Vips::LIBRARY_VERSION = T.let(T.unsafe(nil), String)

# source://ruby-vips//lib/vips.rb#618
Vips::LOG_DOMAIN = T.let(T.unsafe(nil), String)

# source://ruby-vips//lib/vips/object.rb#116
Vips::MARSHAL_ALL = T.let(T.unsafe(nil), Hash)

# source://ruby-vips//lib/vips/object.rb#108
Vips::MARSHAL_FINISH = T.let(T.unsafe(nil), Proc)

# source://ruby-vips//lib/vips/object.rb#62
Vips::MARSHAL_PROGRESS = T.let(T.unsafe(nil), Proc)

# source://ruby-vips//lib/vips/object.rb#69
Vips::MARSHAL_READ = T.let(T.unsafe(nil), Proc)

# source://ruby-vips//lib/vips/object.rb#82
Vips::MARSHAL_SEEK = T.let(T.unsafe(nil), Proc)

# source://ruby-vips//lib/vips/object.rb#95
Vips::MARSHAL_WRITE = T.let(T.unsafe(nil), Proc)

# source://ruby-vips//lib/vips.rb#876
Vips::MAX_COORD = T.let(T.unsafe(nil), Integer)

# source://ruby-vips//lib/vips/mutableimage.rb#13
class Vips::MutableImage < ::Vips::Object
  # source://ruby-vips//lib/vips/mutableimage.rb#50
  def initialize(image); end

  # source://ruby-vips//lib/vips/mutableimage.rb#16
  def bands(*args, **_arg1, &block); end

  # source://ruby-vips//lib/vips/mutableimage.rb#102
  def draw_point!(ink, left, top, **opts); end

  # source://ruby-vips//lib/vips/mutableimage.rb#16
  def filename(*args, **_arg1, &block); end

  # source://ruby-vips//lib/vips/mutableimage.rb#16
  def format(*args, **_arg1, &block); end

  # source://ruby-vips//lib/vips/mutableimage.rb#16
  def get(*args, **_arg1, &block); end

  # source://ruby-vips//lib/vips/mutableimage.rb#16
  def get_fields(*args, **_arg1, &block); end

  # source://ruby-vips//lib/vips/mutableimage.rb#16
  def get_typeof(*args, **_arg1, &block); end

  # source://ruby-vips//lib/vips/mutableimage.rb#16
  def height(*args, **_arg1, &block); end

  # source://ruby-vips//lib/vips/mutableimage.rb#44
  def image; end

  # source://ruby-vips//lib/vips/mutableimage.rb#67
  def inspect; end

  # source://ruby-vips//lib/vips/mutableimage.rb#16
  def interpretation(*args, **_arg1, &block); end

  # source://ruby-vips//lib/vips/mutableimage.rb#95
  def method_missing(name, *args, **options); end

  # source://ruby-vips//lib/vips/mutableimage.rb#15
  def parent_get_typeof(name); end

  # source://ruby-vips//lib/vips/mutableimage.rb#172
  def remove!(name); end

  # source://ruby-vips//lib/vips/mutableimage.rb#71
  def respond_to?(name, include_all = T.unsafe(nil)); end

  # source://ruby-vips//lib/vips/mutableimage.rb#159
  def set!(name, value); end

  # source://ruby-vips//lib/vips/mutableimage.rb#122
  def set_type!(gtype, name, value); end

  # source://ruby-vips//lib/vips/mutableimage.rb#16
  def size(*args, **_arg1, &block); end

  # source://ruby-vips//lib/vips/mutableimage.rb#16
  def width(*args, **_arg1, &block); end

  # source://ruby-vips//lib/vips/mutableimage.rb#16
  def xoffset(*args, **_arg1, &block); end

  # source://ruby-vips//lib/vips/mutableimage.rb#16
  def xres(*args, **_arg1, &block); end

  # source://ruby-vips//lib/vips/mutableimage.rb#16
  def yoffset(*args, **_arg1, &block); end

  # source://ruby-vips//lib/vips/mutableimage.rb#16
  def yres(*args, **_arg1, &block); end

  private

  # source://ruby-vips//lib/vips/mutableimage.rb#82
  def respond_to_missing?(name, include_all = T.unsafe(nil)); end
end

# source://ruby-vips//lib/vips/mutableimage.rb#35
class Vips::MutableImage::ManagedStruct < ::Vips::Object::ManagedStruct
  include ::Vips::MutableImage::MutableImageLayout
end

# source://ruby-vips//lib/vips/mutableimage.rb#22
module Vips::MutableImage::MutableImageLayout
  class << self
    # source://ruby-vips//lib/vips/mutableimage.rb#23
    def included(base); end
  end
end

# source://ruby-vips//lib/vips/mutableimage.rb#31
class Vips::MutableImage::Struct < ::Vips::Object::Struct
  include ::Vips::MutableImage::MutableImageLayout
end

# source://ruby-vips//lib/vips/operation.rb#35
Vips::OPERATION_DEPRECATED = T.let(T.unsafe(nil), Integer)

# source://ruby-vips//lib/vips/operation.rb#37
Vips::OPERATION_FLAGS = T.let(T.unsafe(nil), Hash)

# source://ruby-vips//lib/vips/operation.rb#34
Vips::OPERATION_NOCACHE = T.let(T.unsafe(nil), Integer)

# source://ruby-vips//lib/vips/operation.rb#33
Vips::OPERATION_SEQUENTIAL = T.let(T.unsafe(nil), Integer)

# source://ruby-vips//lib/vips/object.rb#163
class Vips::Object < ::GObject::GObject
  # source://ruby-vips//lib/vips/object.rb#231
  def get(name); end

  # source://ruby-vips//lib/vips/object.rb#200
  def get_pspec(name); end

  # source://ruby-vips//lib/vips/object.rb#221
  def get_typeof(name); end

  # source://ruby-vips//lib/vips/object.rb#213
  def get_typeof_error(name); end

  # source://ruby-vips//lib/vips/object.rb#244
  def set(name, value); end

  # source://ruby-vips//lib/vips/object.rb#255
  def signal_connect(name, handler = T.unsafe(nil), &block); end

  class << self
    # source://ruby-vips//lib/vips/object.rb#166
    def print_all; end
  end
end

# source://ruby-vips//lib/vips/object.rb#194
class Vips::Object::ManagedStruct < ::GObject::GObject::ManagedStruct
  include ::Vips::Object::ObjectLayout
end

# source://ruby-vips//lib/vips/object.rb#172
module Vips::Object::ObjectLayout
  class << self
    # source://ruby-vips//lib/vips/object.rb#173
    def included(base); end
  end
end

# source://ruby-vips//lib/vips/object.rb#190
class Vips::Object::Struct < ::GObject::GObject::Struct
  include ::Vips::Object::ObjectLayout
end

# source://ruby-vips//lib/vips/object.rb#280
class Vips::ObjectClass < ::FFI::Struct; end

# source://ruby-vips//lib/vips/operation.rb#194
class Vips::Operation < ::Vips::Object
  # source://ruby-vips//lib/vips/operation.rb#213
  def initialize(value); end

  # source://ruby-vips//lib/vips/operation.rb#234
  def argument_map(&block); end

  # source://ruby-vips//lib/vips/operation.rb#224
  def build; end

  # source://ruby-vips//lib/vips/operation.rb#273
  def set(name, value, match_image, flags, gtype, destructive); end

  class << self
    # source://ruby-vips//lib/vips/operation.rb#358
    def call(name, supplied, optional = T.unsafe(nil), option_string = T.unsafe(nil)); end

    # source://ruby-vips//lib/vips/operation.rb#243
    def flat_find(object, &block); end

    # source://ruby-vips//lib/vips/operation.rb#257
    def imageize(match_image, value); end
  end
end

# source://ruby-vips//lib/vips/operation.rb#209
class Vips::Operation::ManagedStruct < ::Vips::Object::ManagedStruct
  include ::Vips::Operation::OperationLayout
end

# source://ruby-vips//lib/vips/operation.rb#196
module Vips::Operation::OperationLayout
  class << self
    # source://ruby-vips//lib/vips/operation.rb#197
    def included(base); end
  end
end

# source://ruby-vips//lib/vips/operation.rb#205
class Vips::Operation::Struct < ::Vips::Object::Struct
  include ::Vips::Operation::OperationLayout
end

# source://ruby-vips//lib/vips/object.rb#41
class Vips::Progress < ::FFI::Struct; end

# source://ruby-vips//lib/vips/object.rb#25
Vips::REFSTR_TYPE = T.let(T.unsafe(nil), Integer)

# source://ruby-vips//lib/vips/region.rb#27
class Vips::Region < ::Vips::Object
  # source://ruby-vips//lib/vips/region.rb#46
  def initialize(name); end

  # source://ruby-vips//lib/vips/region.rb#62
  def fetch(left, top, width, height); end

  # source://ruby-vips//lib/vips/region.rb#57
  def height; end

  # source://ruby-vips//lib/vips/region.rb#53
  def width; end
end

# source://ruby-vips//lib/vips/region.rb#42
class Vips::Region::ManagedStruct < ::Vips::Object::ManagedStruct
  include ::Vips::Region::RegionLayout
end

# source://ruby-vips//lib/vips/region.rb#29
module Vips::Region::RegionLayout
  class << self
    # source://ruby-vips//lib/vips/region.rb#30
    def included(base); end
  end
end

# source://ruby-vips//lib/vips/region.rb#38
class Vips::Region::Struct < ::Vips::Object::Struct
  include ::Vips::Region::RegionLayout
end

# source://ruby-vips//lib/vips/object.rb#142
class Vips::SizeStruct < ::FFI::Struct; end

# source://ruby-vips//lib/vips/source.rb#22
class Vips::Source < ::Vips::Connection
  class << self
    # source://ruby-vips//lib/vips/source.rb#48
    def new_from_descriptor(descriptor); end

    # source://ruby-vips//lib/vips/source.rb#62
    def new_from_file(filename); end

    # source://ruby-vips//lib/vips/source.rb#78
    def new_from_memory(data); end
  end
end

# source://ruby-vips//lib/vips/source.rb#36
class Vips::Source::ManagedStruct < ::Vips::Connection::ManagedStruct
  include ::Vips::Source::SourceLayout
end

# source://ruby-vips//lib/vips/source.rb#23
module Vips::Source::SourceLayout
  class << self
    # source://ruby-vips//lib/vips/source.rb#24
    def included(base); end
  end
end

# source://ruby-vips//lib/vips/source.rb#32
class Vips::Source::Struct < ::Vips::Connection::Struct
  include ::Vips::Source::SourceLayout
end

# source://ruby-vips//lib/vips/sourcecustom.rb#28
class Vips::SourceCustom < ::Vips::Source
  # source://ruby-vips//lib/vips/sourcecustom.rb#46
  def initialize; end

  # source://ruby-vips//lib/vips/sourcecustom.rb#60
  def on_read(&block); end

  # source://ruby-vips//lib/vips/sourcecustom.rb#83
  def on_seek(&block); end
end

# source://ruby-vips//lib/vips/sourcecustom.rb#42
class Vips::SourceCustom::ManagedStruct < ::Vips::Source::ManagedStruct
  include ::Vips::SourceCustom::SourceCustomLayout
end

# source://ruby-vips//lib/vips/sourcecustom.rb#29
module Vips::SourceCustom::SourceCustomLayout
  class << self
    # source://ruby-vips//lib/vips/sourcecustom.rb#30
    def included(base); end
  end
end

# source://ruby-vips//lib/vips/sourcecustom.rb#38
class Vips::SourceCustom::Struct < ::Vips::Source::Struct
  include ::Vips::SourceCustom::SourceCustomLayout
end

# source://ruby-vips//lib/vips/target.rb#22
class Vips::Target < ::Vips::Connection
  class << self
    # source://ruby-vips//lib/vips/target.rb#49
    def new_to_descriptor(descriptor); end

    # source://ruby-vips//lib/vips/target.rb#63
    def new_to_file(filename); end

    # source://ruby-vips//lib/vips/target.rb#80
    def new_to_memory; end
  end
end

# source://ruby-vips//lib/vips/target.rb#37
class Vips::Target::ManagedStruct < ::Vips::Connection::ManagedStruct
  include ::Vips::Target::TargetLayout
end

# source://ruby-vips//lib/vips/target.rb#33
class Vips::Target::Struct < ::Vips::Connection::Struct
  include ::Vips::Target::TargetLayout
end

# source://ruby-vips//lib/vips/target.rb#24
module Vips::Target::TargetLayout
  class << self
    # source://ruby-vips//lib/vips/target.rb#25
    def included(base); end
  end
end

# source://ruby-vips//lib/vips/targetcustom.rb#28
class Vips::TargetCustom < ::Vips::Target
  # source://ruby-vips//lib/vips/targetcustom.rb#46
  def initialize; end

  # source://ruby-vips//lib/vips/targetcustom.rb#71
  def on_finish(&block); end

  # source://ruby-vips//lib/vips/targetcustom.rb#59
  def on_write(&block); end
end

# source://ruby-vips//lib/vips/targetcustom.rb#42
class Vips::TargetCustom::ManagedStruct < ::Vips::Target::ManagedStruct
  include ::Vips::TargetCustom::TargetCustomLayout
end

# source://ruby-vips//lib/vips/targetcustom.rb#38
class Vips::TargetCustom::Struct < ::Vips::Target::Struct
  include ::Vips::TargetCustom::TargetCustomLayout
end

# source://ruby-vips//lib/vips/targetcustom.rb#29
module Vips::TargetCustom::TargetCustomLayout
  class << self
    # source://ruby-vips//lib/vips/targetcustom.rb#30
    def included(base); end
  end
end

# source://ruby-vips//lib/vips/version.rb#2
Vips::VERSION = T.let(T.unsafe(nil), String)

# source://ruby-vips//lib/vips/image.rb#1634
module Vips::Yard
  class << self
    # source://ruby-vips//lib/vips/image.rb#1746
    def generate; end

    # source://ruby-vips//lib/vips/image.rb#1678
    def generate_operation(introspect); end

    # source://ruby-vips//lib/vips/image.rb#1662
    def gtype_to_ruby(gtype); end
  end
end

# source://ruby-vips//lib/vips/image.rb#1659
Vips::Yard::ALIAS = T.let(T.unsafe(nil), Array)

# source://ruby-vips//lib/vips/image.rb#1636
Vips::Yard::MAP_GO_TO_RUBY = T.let(T.unsafe(nil), Hash)

# source://ruby-vips//lib/vips/image.rb#1656
Vips::Yard::NO_GENERATE = T.let(T.unsafe(nil), Array)
