# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `turbo-rails` gem.
# Please instead update this file by running `bin/tapioca gem turbo-rails`.


class ActionController::Base < ::ActionController::Metal
  include ::ActionDispatch::Routing::PolymorphicRoutes
  include ::ActionController::Head
  include ::AbstractController::Caching::ConfigMethods
  include ::ActionController::BasicImplicitRender
  extend ::AbstractController::Helpers::Resolution
  extend ::ActionController::Renderers::DeprecatedEscapeJsonResponses
end

module ActionController::Base::HelperMethods
  include ::ActionText::ContentHelper
  include ::ActionText::TagHelper
  include ::Turbo::DriveHelper
  include ::Turbo::FramesHelper
  include ::Turbo::IncludesHelper
  include ::Turbo::StreamsHelper
  include ::ActionView::Helpers::CaptureHelper
  include ::ActionView::Helpers::OutputSafetyHelper
  include ::ActionView::Helpers::TagHelper
  include ::Turbo::Streams::ActionHelper
end

# source://turbo-rails//lib/turbo/engine.rb#3
module Turbo
  extend ::ActiveSupport::Autoload

  # source://turbo-rails//lib/turbo-rails.rb#9
  def current_request_id; end

  # source://turbo-rails//lib/turbo-rails.rb#9
  def current_request_id=(obj); end

  # source://turbo-rails//lib/turbo-rails.rb#7
  def draw_routes; end

  # source://turbo-rails//lib/turbo-rails.rb#7
  def draw_routes=(val); end

  class << self
    # source://turbo-rails//lib/turbo-rails.rb#9
    def current_request_id; end

    # source://turbo-rails//lib/turbo-rails.rb#9
    def current_request_id=(obj); end

    # source://turbo-rails//lib/turbo-rails.rb#7
    def draw_routes; end

    # source://turbo-rails//lib/turbo-rails.rb#7
    def draw_routes=(val); end

    # source://turbo-rails//lib/turbo/engine.rb#5
    def railtie_helpers_paths; end

    # source://turbo-rails//lib/turbo/engine.rb#5
    def railtie_namespace; end

    # source://turbo-rails//lib/turbo/engine.rb#5
    def railtie_routes_url_helpers(include_path_helpers = T.unsafe(nil)); end

    # source://turbo-rails//lib/turbo-rails.rb#14
    def signed_stream_verifier; end

    # source://turbo-rails//lib/turbo-rails.rb#18
    def signed_stream_verifier_key; end

    # source://turbo-rails//lib/turbo-rails.rb#12
    def signed_stream_verifier_key=(_arg0); end

    # source://turbo-rails//lib/turbo/engine.rb#5
    def table_name_prefix; end

    # source://turbo-rails//lib/turbo/engine.rb#5
    def use_relative_model_naming?; end

    # source://turbo-rails//lib/turbo-rails.rb#22
    def with_request_id(request_id); end
  end
end

module Turbo::Broadcastable
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::Turbo::Broadcastable::ClassMethods

  def broadcast_action(action, target: T.unsafe(nil), attributes: T.unsafe(nil), **rendering); end
  def broadcast_action_later(action:, target: T.unsafe(nil), attributes: T.unsafe(nil), **rendering); end
  def broadcast_action_later_to(*streamables, action:, target: T.unsafe(nil), attributes: T.unsafe(nil), **rendering); end
  def broadcast_action_to(*streamables, action:, target: T.unsafe(nil), attributes: T.unsafe(nil), **rendering); end
  def broadcast_after_to(*streamables, target: T.unsafe(nil), targets: T.unsafe(nil), **rendering); end
  def broadcast_append(target: T.unsafe(nil), **rendering); end
  def broadcast_append_later(target: T.unsafe(nil), **rendering); end
  def broadcast_append_later_to(*streamables, target: T.unsafe(nil), **rendering); end
  def broadcast_append_to(*streamables, target: T.unsafe(nil), **rendering); end
  def broadcast_before_to(*streamables, target: T.unsafe(nil), targets: T.unsafe(nil), **rendering); end
  def broadcast_prepend(target: T.unsafe(nil), **rendering); end
  def broadcast_prepend_later(target: T.unsafe(nil), **rendering); end
  def broadcast_prepend_later_to(*streamables, target: T.unsafe(nil), **rendering); end
  def broadcast_prepend_to(*streamables, target: T.unsafe(nil), **rendering); end
  def broadcast_refresh; end
  def broadcast_refresh_later; end
  def broadcast_refresh_later_to(*streamables); end
  def broadcast_refresh_to(*streamables); end
  def broadcast_remove(**rendering); end
  def broadcast_remove_to(*streamables, target: T.unsafe(nil), **rendering); end
  def broadcast_render(**rendering); end
  def broadcast_render_later(**rendering); end
  def broadcast_render_later_to(*streamables, **rendering); end
  def broadcast_render_to(*streamables, **rendering); end
  def broadcast_replace(**rendering); end
  def broadcast_replace_later(**rendering); end
  def broadcast_replace_later_to(*streamables, **rendering); end
  def broadcast_replace_to(*streamables, **rendering); end
  def broadcast_update(**rendering); end
  def broadcast_update_later(**rendering); end
  def broadcast_update_later_to(*streamables, **rendering); end
  def broadcast_update_to(*streamables, **rendering); end

  private

  def broadcast_rendering_with_defaults(options); end
  def broadcast_target_default; end
  def extract_options_and_add_target(rendering = T.unsafe(nil), target: T.unsafe(nil)); end
end

module Turbo::Broadcastable::ClassMethods
  def broadcast_target_default; end
  def broadcasts(stream = T.unsafe(nil), inserts_by: T.unsafe(nil), target: T.unsafe(nil), **rendering); end
  def broadcasts_refreshes(stream = T.unsafe(nil)); end
  def broadcasts_refreshes_to(stream); end
  def broadcasts_to(stream, inserts_by: T.unsafe(nil), target: T.unsafe(nil), **rendering); end
  def suppressed_turbo_broadcasts?; end
  def suppressing_turbo_broadcasts(&block); end
end

# source://turbo-rails//lib/turbo/broadcastable/test_helper.rb#3
module Turbo::Broadcastable::TestHelper
  extend ::ActiveSupport::Concern
  include ::ActionCable::TestHelper
  include ::Turbo::Streams::StreamName

  # source://turbo-rails//lib/turbo/broadcastable/test_helper.rb#104
  def assert_no_turbo_stream_broadcasts(stream_name_or_object, &block); end

  # source://turbo-rails//lib/turbo/broadcastable/test_helper.rb#58
  def assert_turbo_stream_broadcasts(stream_name_or_object, count: T.unsafe(nil), &block); end

  # source://turbo-rails//lib/turbo/broadcastable/test_helper.rb#157
  def capture_turbo_stream_broadcasts(stream_name_or_object, &block); end
end

class Turbo::Debouncer
  def initialize(delay: T.unsafe(nil)); end

  def debounce(&block); end
  def delay; end
  def scheduled_task; end
  def wait; end

  private

  def wait_timeout; end
end

Turbo::Debouncer::DEFAULT_DELAY = T.let(T.unsafe(nil), Float)

module Turbo::DriveHelper
  def turbo_exempts_page_from_cache; end
  def turbo_exempts_page_from_cache_tag; end
  def turbo_exempts_page_from_preview; end
  def turbo_exempts_page_from_preview_tag; end
  def turbo_page_requires_reload; end
  def turbo_page_requires_reload_tag; end
  def turbo_refresh_method_tag(method = T.unsafe(nil)); end
  def turbo_refresh_scroll_tag(scroll = T.unsafe(nil)); end
  def turbo_refreshes_with(method: T.unsafe(nil), scroll: T.unsafe(nil)); end
end

# source://turbo-rails//lib/turbo/engine.rb#4
class Turbo::Engine < ::Rails::Engine; end

# source://turbo-rails//lib/turbo/engine.rb#67
Turbo::Engine::PRECOMPILE_ASSETS = T.let(T.unsafe(nil), Array)

module Turbo::Frames; end

module Turbo::Frames::FrameRequest
  extend ::ActiveSupport::Concern

  private

  def turbo_frame_request?; end
  def turbo_frame_request_id; end
end

module Turbo::FramesHelper
  def turbo_frame_tag(*ids, src: T.unsafe(nil), target: T.unsafe(nil), **attributes, &block); end
end

module Turbo::IncludesHelper
  def turbo_include_tags; end
end

module Turbo::Native; end

module Turbo::Native::Navigation
  extend ::ActiveSupport::Concern

  def hotwire_native_app?; end
  def recede_or_redirect_back_or_to(url, **options); end
  def recede_or_redirect_to(url, **options); end
  def refresh_or_redirect_back_or_to(url, **options); end
  def refresh_or_redirect_to(url, **options); end
  def resume_or_redirect_back_or_to(url, **options); end
  def resume_or_redirect_to(url, **options); end
  def turbo_native_app?; end

  private

  def turbo_native_action_or_redirect(url, action, redirect_type, options = T.unsafe(nil)); end
end

class Turbo::Native::NavigationController < ::ActionController::Base
  def recede; end
  def refresh; end
  def resume; end

  private

  def _layout(lookup_context, formats, keys); end
  def _layout_from_proc; end

  class << self
    private

    def __class_attr_config; end
    def __class_attr_config=(new_value); end
    def __class_attr_middleware_stack; end
    def __class_attr_middleware_stack=(new_value); end
  end
end

module Turbo::RequestIdTracking
  extend ::ActiveSupport::Concern

  private

  def turbo_tracking_request_id(&block); end
end

module Turbo::Streams; end

class Turbo::Streams::ActionBroadcastJob < ::ActiveJob::Base
  def perform(stream, action:, target:, attributes: T.unsafe(nil), **rendering); end

  class << self
    private

    def __class_attr_rescue_handlers; end
    def __class_attr_rescue_handlers=(new_value); end
  end
end

module Turbo::Streams::ActionHelper
  include ::ActionView::Helpers::CaptureHelper
  include ::ActionView::Helpers::OutputSafetyHelper
  include ::ActionView::Helpers::TagHelper

  def turbo_stream_action_tag(action, target: T.unsafe(nil), targets: T.unsafe(nil), template: T.unsafe(nil), **attributes); end
  def turbo_stream_refresh_tag(request_id: T.unsafe(nil), **attributes); end

  private

  def convert_to_turbo_stream_dom_id(target, include_selector: T.unsafe(nil)); end
end

class Turbo::Streams::BroadcastJob < ::ActiveJob::Base
  def perform(stream, **rendering); end

  class << self
    private

    def __class_attr_rescue_handlers; end
    def __class_attr_rescue_handlers=(new_value); end
  end
end

class Turbo::Streams::BroadcastStreamJob < ::ActiveJob::Base
  def perform(stream, content:); end

  class << self
    private

    def __class_attr_rescue_handlers; end
    def __class_attr_rescue_handlers=(new_value); end
  end
end

module Turbo::Streams::Broadcasts
  include ::ActionView::Helpers::CaptureHelper
  include ::ActionView::Helpers::OutputSafetyHelper
  include ::ActionView::Helpers::TagHelper
  include ::Turbo::Streams::ActionHelper

  def broadcast_action_later_to(*streamables, action:, target: T.unsafe(nil), targets: T.unsafe(nil), attributes: T.unsafe(nil), **rendering); end
  def broadcast_action_to(*streamables, action:, target: T.unsafe(nil), targets: T.unsafe(nil), attributes: T.unsafe(nil), **rendering); end
  def broadcast_after_later_to(*streamables, **opts); end
  def broadcast_after_to(*streamables, **opts); end
  def broadcast_append_later_to(*streamables, **opts); end
  def broadcast_append_to(*streamables, **opts); end
  def broadcast_before_later_to(*streamables, **opts); end
  def broadcast_before_to(*streamables, **opts); end
  def broadcast_prepend_later_to(*streamables, **opts); end
  def broadcast_prepend_to(*streamables, **opts); end
  def broadcast_refresh_later_to(*streamables, request_id: T.unsafe(nil), **opts); end
  def broadcast_refresh_to(*streamables, **opts); end
  def broadcast_remove_to(*streamables, **opts); end
  def broadcast_render_later_to(*streamables, **rendering); end
  def broadcast_render_to(*streamables, **rendering); end
  def broadcast_replace_later_to(*streamables, **opts); end
  def broadcast_replace_to(*streamables, **opts); end
  def broadcast_stream_to(*streamables, content:); end
  def broadcast_update_later_to(*streamables, **opts); end
  def broadcast_update_to(*streamables, **opts); end
  def refresh_debouncer_for(*streamables, request_id: T.unsafe(nil)); end

  private

  def render_broadcast_action(rendering); end
  def render_format(format, **rendering); end
end

module Turbo::Streams::StreamName
  def signed_stream_name(streamables); end
  def verified_stream_name(signed_stream_name); end

  private

  def stream_name_from(streamables); end
end

module Turbo::Streams::StreamName::ClassMethods
  def verified_stream_name_from_params; end
end

class Turbo::Streams::TagBuilder
  include ::ActionView::Helpers::CaptureHelper
  include ::ActionView::Helpers::OutputSafetyHelper
  include ::ActionView::Helpers::TagHelper
  include ::Turbo::Streams::ActionHelper

  def initialize(view_context); end

  def action(name, target, content = T.unsafe(nil), method: T.unsafe(nil), allow_inferred_rendering: T.unsafe(nil), **rendering, &block); end
  def action_all(name, targets, content = T.unsafe(nil), method: T.unsafe(nil), allow_inferred_rendering: T.unsafe(nil), **rendering, &block); end
  def after(target, content = T.unsafe(nil), **rendering, &block); end
  def after_all(targets, content = T.unsafe(nil), **rendering, &block); end
  def append(target, content = T.unsafe(nil), **rendering, &block); end
  def append_all(targets, content = T.unsafe(nil), **rendering, &block); end
  def before(target, content = T.unsafe(nil), **rendering, &block); end
  def before_all(targets, content = T.unsafe(nil), **rendering, &block); end
  def prepend(target, content = T.unsafe(nil), **rendering, &block); end
  def prepend_all(targets, content = T.unsafe(nil), **rendering, &block); end
  def refresh(*_arg0, **_arg1, &_arg2); end
  def remove(target); end
  def remove_all(targets); end
  def replace(target, content = T.unsafe(nil), method: T.unsafe(nil), **rendering, &block); end
  def replace_all(targets, content = T.unsafe(nil), method: T.unsafe(nil), **rendering, &block); end
  def update(target, content = T.unsafe(nil), method: T.unsafe(nil), **rendering, &block); end
  def update_all(targets, content = T.unsafe(nil), method: T.unsafe(nil), **rendering, &block); end

  private

  def render_record(possible_record); end
  def render_template(target, content = T.unsafe(nil), allow_inferred_rendering: T.unsafe(nil), **rendering, &block); end
end

module Turbo::Streams::TurboStreamsTagBuilder
  private

  def turbo_stream; end
end

class Turbo::StreamsChannel < ::ActionCable::Channel::Base
  include ::Turbo::Streams::StreamName::ClassMethods
  extend ::Turbo::Streams::StreamName
  extend ::ActionView::Helpers::CaptureHelper
  extend ::ActionView::Helpers::OutputSafetyHelper
  extend ::ActionView::Helpers::TagHelper
  extend ::Turbo::Streams::ActionHelper
  extend ::Turbo::Streams::Broadcasts

  def subscribed; end
end

module Turbo::StreamsHelper
  def turbo_stream; end
  def turbo_stream_from(*streamables, **attributes); end
end

# source://turbo-rails//lib/turbo/test_assertions.rb#2
module Turbo::TestAssertions
  extend ::ActiveSupport::Concern

  # source://turbo-rails//lib/turbo/test_assertions.rb#76
  def assert_no_turbo_stream(action:, target: T.unsafe(nil), targets: T.unsafe(nil)); end

  # source://turbo-rails//lib/turbo/test_assertions.rb#48
  def assert_turbo_stream(action:, target: T.unsafe(nil), targets: T.unsafe(nil), count: T.unsafe(nil), &block); end
end

# source://turbo-rails//lib/turbo/test_assertions/integration_test_assertions.rb#3
module Turbo::TestAssertions::IntegrationTestAssertions
  # source://turbo-rails//lib/turbo/test_assertions/integration_test_assertions.rb#69
  def assert_no_turbo_stream(status: T.unsafe(nil), **attributes); end

  # source://turbo-rails//lib/turbo/test_assertions/integration_test_assertions.rb#41
  def assert_turbo_stream(status: T.unsafe(nil), **attributes, &block); end
end

class Turbo::ThreadDebouncer
  def initialize(key, thread, delay:); end

  def debounce; end
  def wait(*_arg0, **_arg1, &_arg2); end

  private

  def debouncer; end
  def key; end
  def thread; end

  class << self
    def for(key, delay: T.unsafe(nil)); end

    private

    def new(*_arg0); end
  end
end
