// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

// NOTE: We use importmap module names (e.g., "controllers/application") instead of
// relative paths (e.g., "./application") to prevent 404 errors on controller assets.
// The stimulus:manifest:update command will revert these to relative paths, so they
// need to be manually fixed after running that command.

import { application } from "controllers/application"

import AutoSubmitController from "controllers/auto_submit_controller"
application.register("auto-submit", AutoSubmitController)

import MetadataFieldsController from "controllers/metadata_fields_controller"
application.register("metadata-fields", MetadataFieldsController)

import OfflineController from "controllers/offline_controller"
application.register("offline", OfflineController)

import ThemeController from "controllers/theme_controller"
application.register("theme", ThemeController)

import ViewToggleController from "controllers/view_toggle_controller"
application.register("view-toggle", ViewToggleController)
